/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_FrenSer_cost_y_e_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[61] = {57, 1, 0, 57, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56};
static const casadi_int casadi_s1[4] = {0, 1, 0, 0};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[117] = {57, 57, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56};
static const casadi_int casadi_s5[3] = {57, 0, 0};

/* drone_FrenSer_cost_y_e_fun_jac_ut_xt:(i0[57],i1[0],i2[0],i3[],i4)->(o0[57],o1[57x57,57nz],o2[57x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, *w1=w+1, *w2=w+58;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #4: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #6: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #7: output[0][3] = @0 */
  if (res[0]) res[0][3] = w0;
  /* #8: @0 = input[0][4] */
  w0 = arg[0] ? arg[0][4] : 0;
  /* #9: output[0][4] = @0 */
  if (res[0]) res[0][4] = w0;
  /* #10: @0 = input[0][5] */
  w0 = arg[0] ? arg[0][5] : 0;
  /* #11: output[0][5] = @0 */
  if (res[0]) res[0][5] = w0;
  /* #12: @0 = input[0][6] */
  w0 = arg[0] ? arg[0][6] : 0;
  /* #13: output[0][6] = @0 */
  if (res[0]) res[0][6] = w0;
  /* #14: @0 = input[0][7] */
  w0 = arg[0] ? arg[0][7] : 0;
  /* #15: output[0][7] = @0 */
  if (res[0]) res[0][7] = w0;
  /* #16: @0 = input[0][8] */
  w0 = arg[0] ? arg[0][8] : 0;
  /* #17: output[0][8] = @0 */
  if (res[0]) res[0][8] = w0;
  /* #18: @0 = input[0][9] */
  w0 = arg[0] ? arg[0][9] : 0;
  /* #19: output[0][9] = @0 */
  if (res[0]) res[0][9] = w0;
  /* #20: @0 = input[0][10] */
  w0 = arg[0] ? arg[0][10] : 0;
  /* #21: output[0][10] = @0 */
  if (res[0]) res[0][10] = w0;
  /* #22: @0 = input[0][11] */
  w0 = arg[0] ? arg[0][11] : 0;
  /* #23: output[0][11] = @0 */
  if (res[0]) res[0][11] = w0;
  /* #24: @0 = input[0][12] */
  w0 = arg[0] ? arg[0][12] : 0;
  /* #25: output[0][12] = @0 */
  if (res[0]) res[0][12] = w0;
  /* #26: @0 = input[0][13] */
  w0 = arg[0] ? arg[0][13] : 0;
  /* #27: output[0][13] = @0 */
  if (res[0]) res[0][13] = w0;
  /* #28: @0 = input[0][14] */
  w0 = arg[0] ? arg[0][14] : 0;
  /* #29: output[0][14] = @0 */
  if (res[0]) res[0][14] = w0;
  /* #30: @0 = input[0][15] */
  w0 = arg[0] ? arg[0][15] : 0;
  /* #31: output[0][15] = @0 */
  if (res[0]) res[0][15] = w0;
  /* #32: @0 = input[0][16] */
  w0 = arg[0] ? arg[0][16] : 0;
  /* #33: output[0][16] = @0 */
  if (res[0]) res[0][16] = w0;
  /* #34: @0 = input[0][17] */
  w0 = arg[0] ? arg[0][17] : 0;
  /* #35: output[0][17] = @0 */
  if (res[0]) res[0][17] = w0;
  /* #36: @0 = input[0][18] */
  w0 = arg[0] ? arg[0][18] : 0;
  /* #37: output[0][18] = @0 */
  if (res[0]) res[0][18] = w0;
  /* #38: @0 = input[0][19] */
  w0 = arg[0] ? arg[0][19] : 0;
  /* #39: output[0][19] = @0 */
  if (res[0]) res[0][19] = w0;
  /* #40: @0 = input[0][20] */
  w0 = arg[0] ? arg[0][20] : 0;
  /* #41: output[0][20] = @0 */
  if (res[0]) res[0][20] = w0;
  /* #42: @0 = input[0][21] */
  w0 = arg[0] ? arg[0][21] : 0;
  /* #43: output[0][21] = @0 */
  if (res[0]) res[0][21] = w0;
  /* #44: @0 = input[0][22] */
  w0 = arg[0] ? arg[0][22] : 0;
  /* #45: output[0][22] = @0 */
  if (res[0]) res[0][22] = w0;
  /* #46: @0 = input[0][23] */
  w0 = arg[0] ? arg[0][23] : 0;
  /* #47: output[0][23] = @0 */
  if (res[0]) res[0][23] = w0;
  /* #48: @0 = input[0][24] */
  w0 = arg[0] ? arg[0][24] : 0;
  /* #49: output[0][24] = @0 */
  if (res[0]) res[0][24] = w0;
  /* #50: @0 = input[0][25] */
  w0 = arg[0] ? arg[0][25] : 0;
  /* #51: output[0][25] = @0 */
  if (res[0]) res[0][25] = w0;
  /* #52: @0 = input[0][26] */
  w0 = arg[0] ? arg[0][26] : 0;
  /* #53: output[0][26] = @0 */
  if (res[0]) res[0][26] = w0;
  /* #54: @0 = input[0][27] */
  w0 = arg[0] ? arg[0][27] : 0;
  /* #55: output[0][27] = @0 */
  if (res[0]) res[0][27] = w0;
  /* #56: @0 = input[0][28] */
  w0 = arg[0] ? arg[0][28] : 0;
  /* #57: output[0][28] = @0 */
  if (res[0]) res[0][28] = w0;
  /* #58: @0 = input[0][29] */
  w0 = arg[0] ? arg[0][29] : 0;
  /* #59: output[0][29] = @0 */
  if (res[0]) res[0][29] = w0;
  /* #60: @0 = input[0][30] */
  w0 = arg[0] ? arg[0][30] : 0;
  /* #61: output[0][30] = @0 */
  if (res[0]) res[0][30] = w0;
  /* #62: @0 = input[0][31] */
  w0 = arg[0] ? arg[0][31] : 0;
  /* #63: output[0][31] = @0 */
  if (res[0]) res[0][31] = w0;
  /* #64: @0 = input[0][32] */
  w0 = arg[0] ? arg[0][32] : 0;
  /* #65: output[0][32] = @0 */
  if (res[0]) res[0][32] = w0;
  /* #66: @0 = input[0][33] */
  w0 = arg[0] ? arg[0][33] : 0;
  /* #67: output[0][33] = @0 */
  if (res[0]) res[0][33] = w0;
  /* #68: @0 = input[0][34] */
  w0 = arg[0] ? arg[0][34] : 0;
  /* #69: output[0][34] = @0 */
  if (res[0]) res[0][34] = w0;
  /* #70: @0 = input[0][35] */
  w0 = arg[0] ? arg[0][35] : 0;
  /* #71: output[0][35] = @0 */
  if (res[0]) res[0][35] = w0;
  /* #72: @0 = input[0][36] */
  w0 = arg[0] ? arg[0][36] : 0;
  /* #73: output[0][36] = @0 */
  if (res[0]) res[0][36] = w0;
  /* #74: @0 = input[0][37] */
  w0 = arg[0] ? arg[0][37] : 0;
  /* #75: output[0][37] = @0 */
  if (res[0]) res[0][37] = w0;
  /* #76: @0 = input[0][38] */
  w0 = arg[0] ? arg[0][38] : 0;
  /* #77: output[0][38] = @0 */
  if (res[0]) res[0][38] = w0;
  /* #78: @0 = input[0][39] */
  w0 = arg[0] ? arg[0][39] : 0;
  /* #79: output[0][39] = @0 */
  if (res[0]) res[0][39] = w0;
  /* #80: @0 = input[0][40] */
  w0 = arg[0] ? arg[0][40] : 0;
  /* #81: output[0][40] = @0 */
  if (res[0]) res[0][40] = w0;
  /* #82: @0 = input[0][41] */
  w0 = arg[0] ? arg[0][41] : 0;
  /* #83: output[0][41] = @0 */
  if (res[0]) res[0][41] = w0;
  /* #84: @0 = input[0][42] */
  w0 = arg[0] ? arg[0][42] : 0;
  /* #85: output[0][42] = @0 */
  if (res[0]) res[0][42] = w0;
  /* #86: @0 = input[0][43] */
  w0 = arg[0] ? arg[0][43] : 0;
  /* #87: output[0][43] = @0 */
  if (res[0]) res[0][43] = w0;
  /* #88: @0 = input[0][44] */
  w0 = arg[0] ? arg[0][44] : 0;
  /* #89: output[0][44] = @0 */
  if (res[0]) res[0][44] = w0;
  /* #90: @0 = input[0][45] */
  w0 = arg[0] ? arg[0][45] : 0;
  /* #91: output[0][45] = @0 */
  if (res[0]) res[0][45] = w0;
  /* #92: @0 = input[0][46] */
  w0 = arg[0] ? arg[0][46] : 0;
  /* #93: output[0][46] = @0 */
  if (res[0]) res[0][46] = w0;
  /* #94: @0 = input[0][47] */
  w0 = arg[0] ? arg[0][47] : 0;
  /* #95: output[0][47] = @0 */
  if (res[0]) res[0][47] = w0;
  /* #96: @0 = input[0][48] */
  w0 = arg[0] ? arg[0][48] : 0;
  /* #97: output[0][48] = @0 */
  if (res[0]) res[0][48] = w0;
  /* #98: @0 = input[0][49] */
  w0 = arg[0] ? arg[0][49] : 0;
  /* #99: output[0][49] = @0 */
  if (res[0]) res[0][49] = w0;
  /* #100: @0 = input[0][50] */
  w0 = arg[0] ? arg[0][50] : 0;
  /* #101: output[0][50] = @0 */
  if (res[0]) res[0][50] = w0;
  /* #102: @0 = input[0][51] */
  w0 = arg[0] ? arg[0][51] : 0;
  /* #103: output[0][51] = @0 */
  if (res[0]) res[0][51] = w0;
  /* #104: @0 = input[0][52] */
  w0 = arg[0] ? arg[0][52] : 0;
  /* #105: output[0][52] = @0 */
  if (res[0]) res[0][52] = w0;
  /* #106: @0 = input[0][53] */
  w0 = arg[0] ? arg[0][53] : 0;
  /* #107: output[0][53] = @0 */
  if (res[0]) res[0][53] = w0;
  /* #108: @0 = input[0][54] */
  w0 = arg[0] ? arg[0][54] : 0;
  /* #109: output[0][54] = @0 */
  if (res[0]) res[0][54] = w0;
  /* #110: @0 = input[0][55] */
  w0 = arg[0] ? arg[0][55] : 0;
  /* #111: output[0][55] = @0 */
  if (res[0]) res[0][55] = w0;
  /* #112: @0 = input[0][56] */
  w0 = arg[0] ? arg[0][56] : 0;
  /* #113: output[0][56] = @0 */
  if (res[0]) res[0][56] = w0;
  /* #114: @1 = zeros(57x57,57nz) */
  casadi_clear(w1, 57);
  /* #115: @2 = ones(57x1) */
  casadi_fill(w2, 57, 1.);
  /* #116: (@1[:57] = @2) */
  for (rr=w1+0, ss=w2; rr!=w1+57; rr+=1) *rr = *ss++;
  /* #117: output[1][0] = @1 */
  casadi_copy(w1, 57, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_cost_y_e_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_cost_y_e_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_cost_y_e_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_FrenSer_cost_y_e_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_cost_y_e_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_FrenSer_cost_y_e_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_FrenSer_cost_y_e_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_FrenSer_cost_y_e_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_FrenSer_cost_y_e_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int drone_FrenSer_cost_y_e_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real drone_FrenSer_cost_y_e_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_FrenSer_cost_y_e_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_FrenSer_cost_y_e_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_FrenSer_cost_y_e_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_FrenSer_cost_y_e_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_cost_y_e_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 115;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_cost_y_e_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 115*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
