/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) payload_nav_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

static const casadi_int casadi_s0[3] = {0, 1, 2};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[12] = {3, 3, 0, 3, 5, 6, 0, 1, 2, 1, 2, 2};
static const casadi_int casadi_s3[12] = {3, 3, 0, 1, 3, 6, 0, 0, 1, 0, 1, 2};
static const casadi_int casadi_s4[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s5[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s6[4] = {0, 1, 0, 0};
static const casadi_int casadi_s7[29] = {28, 1, 0, 25, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27};

static const casadi_real casadi_c0[3] = {0., 0., -2.4516624999999999e+00};
static const casadi_real casadi_c1[3] = {0., 0., 1.};
static const casadi_real casadi_c2[9] = {8.3333333333333326e-01, 0., 0., 0., 8.3333333333333326e-01, 0., 0., 0., 1.3333333333333333e+00};
static const casadi_real casadi_c3[3] = {0., 0., 5.0000000000000000e-01};
static const casadi_real casadi_c4[9] = {2.5083333333333338e-03, 0., 0., 0., 2.5083333333333338e-03, 0., 0., 0., 5.0000000000000010e-03};

/* payload_nav_expl_vde_adj:(i0[24],i1[24],i2[4],i3[0])->(o0[28x1,25nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+4, *w2=w+13, w3, *w4=w+17, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+35, *w21=w+38, *w22=w+41, *w23=w+44, *w24=w+53, *w25=w+62, *w26=w+65, *w27=w+89, *w28=w+93, *w29=w+96, *w30=w+99, *w31=w+103, w32, w33, w34, w35, w36, w37, w38, w39, w40, w41, *w42=w+116, *w43=w+119, w44, w45, w46, w47, w48, w49, w50, w51, w52, w53, w54, w55, w56, w57, w58, w59, w60, w61, w62, *w63=w+141;
  /* #0: @0 = input[0][4] */
  w0 = arg[0] ? arg[0][4] : 0;
  /* #1: @1 = zeros(3x3) */
  casadi_clear(w1, 9);
  /* #2: @2 = zeros(3x1) */
  casadi_clear(w2, 3);
  /* #3: @3 = 0 */
  w3 = 0.;
  /* #4: @4 = [0, 0, -2.45166] */
  casadi_copy(casadi_c0, 3, w4);
  /* #5: @5 = input[2][0] */
  w5 = arg[2] ? arg[2][0] : 0;
  /* #6: @6 = 1 */
  w6 = 1.;
  /* #7: @7 = input[0][15] */
  w7 = arg[0] ? arg[0][15] : 0;
  /* #8: @8 = sq(@7) */
  w8 = casadi_sq( w7 );
  /* #9: @9 = input[0][16] */
  w9 = arg[0] ? arg[0][16] : 0;
  /* #10: @10 = sq(@9) */
  w10 = casadi_sq( w9 );
  /* #11: @11 = (@8+@10) */
  w11  = (w8+w10);
  /* #12: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #13: @11 = (@6-@11) */
  w11  = (w6-w11);
  /* #14: @12 = input[0][14] */
  w12 = arg[0] ? arg[0][14] : 0;
  /* #15: @13 = (@12*@7) */
  w13  = (w12*w7);
  /* #16: @14 = input[0][13] */
  w14 = arg[0] ? arg[0][13] : 0;
  /* #17: @15 = (@9*@14) */
  w15  = (w9*w14);
  /* #18: @16 = (@13-@15) */
  w16  = (w13-w15);
  /* #19: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #20: @17 = (@12*@9) */
  w17  = (w12*w9);
  /* #21: @18 = (@7*@14) */
  w18  = (w7*w14);
  /* #22: @19 = (@17+@18) */
  w19  = (w17+w18);
  /* #23: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #24: @20 = horzcat(@11, @16, @19) */
  rr=w20;
  *rr++ = w11;
  *rr++ = w16;
  *rr++ = w19;
  /* #25: @20 = @20' */
  /* #26: @13 = (@13+@15) */
  w13 += w15;
  /* #27: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #28: @15 = sq(@12) */
  w15 = casadi_sq( w12 );
  /* #29: @10 = (@15+@10) */
  w10  = (w15+w10);
  /* #30: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #31: @10 = (@6-@10) */
  w10  = (w6-w10);
  /* #32: @11 = (@7*@9) */
  w11  = (w7*w9);
  /* #33: @16 = (@12*@14) */
  w16  = (w12*w14);
  /* #34: @19 = (@11-@16) */
  w19  = (w11-w16);
  /* #35: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #36: @21 = horzcat(@13, @10, @19) */
  rr=w21;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w19;
  /* #37: @21 = @21' */
  /* #38: @17 = (@17-@18) */
  w17 -= w18;
  /* #39: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #40: @11 = (@11+@16) */
  w11 += w16;
  /* #41: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #42: @15 = (@15+@8) */
  w15 += w8;
  /* #43: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #44: @15 = (@6-@15) */
  w15  = (w6-w15);
  /* #45: @22 = horzcat(@17, @11, @15) */
  rr=w22;
  *rr++ = w17;
  *rr++ = w11;
  *rr++ = w15;
  /* #46: @22 = @22' */
  /* #47: @23 = horzcat(@20, @21, @22) */
  rr=w23;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  /* #48: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #49: @20 = [0, 0, 1] */
  casadi_copy(casadi_c1, 3, w20);
  /* #50: @21 = mac(@24,@20,@2) */
  casadi_copy(w2, 3, w21);
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w24+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #51: @22 = (@5*@21) */
  for (i=0, rr=w22, cs=w21; i<3; ++i) (*rr++)  = (w5*(*cs++));
  /* #52: @4 = (@4+@22) */
  for (i=0, rr=w4, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #53: @22 = @4' */
  casadi_copy(w4, 3, w22);
  /* #54: @17 = input[0][20] */
  w17 = arg[0] ? arg[0][20] : 0;
  /* #55: @11 = sin(@17) */
  w11 = sin( w17 );
  /* #56: @15 = input[0][21] */
  w15 = arg[0] ? arg[0][21] : 0;
  /* #57: @8 = cos(@15) */
  w8 = cos( w15 );
  /* #58: @16 = (@11*@8) */
  w16  = (w11*w8);
  /* #59: @15 = sin(@15) */
  w15 = sin( w15 );
  /* #60: @18 = (@11*@15) */
  w18  = (w11*w15);
  /* #61: @17 = cos(@17) */
  w17 = cos( w17 );
  /* #62: @25 = vertcat(@16, @18, @17) */
  rr=w25;
  *rr++ = w16;
  *rr++ = w18;
  *rr++ = w17;
  /* #63: @16 = mac(@22,@25,@3) */
  casadi_copy((&w3), 1, (&w16));
  for (i=0, rr=(&w16); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w25+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #64: @22 = (@16*@25) */
  for (i=0, rr=w22, cs=w25; i<3; ++i) (*rr++)  = (w16*(*cs++));
  /* #65: @18 = @22[1] */
  for (rr=(&w18), ss=w22+1; ss!=w22+2; ss+=1) *rr++ = *ss;
  /* #66: @26 = input[1][0] */
  casadi_copy(arg[1], 24, w26);
  /* #67: {@13, @10, @19, @27, @28, @29, @30, @31, @32, @33, @34, @35} = vertsplit(@26) */
  w13 = w26[0];
  w10 = w26[1];
  w19 = w26[2];
  casadi_copy(w26+3, 4, w27);
  casadi_copy(w26+7, 3, w28);
  casadi_copy(w26+10, 3, w29);
  casadi_copy(w26+13, 4, w30);
  casadi_copy(w26+17, 3, w31);
  w32 = w26[20];
  w33 = w26[21];
  w34 = w26[22];
  w35 = w26[23];
  /* #68: @24 = 
  [[0.833333, 0, 0], 
   [0, 0.833333, 0], 
   [0, 0, 1.33333]] */
  casadi_copy(casadi_c2, 9, w24);
  /* #69: @29 = (@24'\@29) */
  rr = w29;
  ss = w24;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 1, 1, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #70: {@36, @37, @38} = vertsplit(@29) */
  w36 = w29[0];
  w37 = w29[1];
  w38 = w29[2];
  /* #71: @39 = (@18*@38) */
  w39  = (w18*w38);
  /* #72: @40 = @22[2] */
  for (rr=(&w40), ss=w22+2; ss!=w22+3; ss+=1) *rr++ = *ss;
  /* #73: @41 = (@40*@37) */
  w41  = (w40*w37);
  /* #74: @39 = (@39-@41) */
  w39 -= w41;
  /* #75: @29 = @2; (@29[0] += @39) */
  casadi_copy(w2, 3, w29);
  for (rr=w29+0, ss=(&w39); rr!=w29+1; rr+=1) *rr += *ss++;
  /* #76: @39 = @22[0] */
  for (rr=(&w39), ss=w22+0; ss!=w22+1; ss+=1) *rr++ = *ss;
  /* #77: @41 = (@39*@37) */
  w41  = (w39*w37);
  /* #78: @18 = (@18*@36) */
  w18 *= w36;
  /* #79: @41 = (@41-@18) */
  w41 -= w18;
  /* #80: (@29[2] += @41) */
  for (rr=w29+2, ss=(&w41); rr!=w29+3; rr+=1) *rr += *ss++;
  /* #81: @40 = (@40*@36) */
  w40 *= w36;
  /* #82: @39 = (@39*@38) */
  w39 *= w38;
  /* #83: @40 = (@40-@39) */
  w40 -= w39;
  /* #84: (@29[1] += @40) */
  for (rr=w29+1, ss=(&w40); rr!=w29+2; rr+=1) *rr += *ss++;
  /* #85: @22 = [0, 0, 0.5] */
  casadi_copy(casadi_c3, 3, w22);
  /* #86: @42 = @22' */
  casadi_copy(w22, 3, w42);
  /* #87: @24 = mac(@29,@42,@1) */
  casadi_copy(w1, 9, w24);
  for (i=0, rr=w24; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w29+j, tt=w42+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #88: @23 = @24' */
  for (i=0, rr=w23, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #89: {@29, @42, @43} = horzsplit(@23) */
  casadi_copy(w23, 3, w29);
  casadi_copy(w23+3, 3, w42);
  casadi_copy(w23+6, 3, w43);
  /* #90: @43 = @43' */
  /* #91: {@40, @39, @41} = horzsplit(@43) */
  w40 = w43[0];
  w39 = w43[1];
  w41 = w43[2];
  /* #92: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #93: @18 = (@0*@39) */
  w18  = (w0*w39);
  /* #94: @44 = input[0][5] */
  w44 = arg[0] ? arg[0][5] : 0;
  /* #95: @40 = (2.*@40) */
  w40 = (2.* w40 );
  /* #96: @45 = (@44*@40) */
  w45  = (w44*w40);
  /* #97: @18 = (@18-@45) */
  w18 -= w45;
  /* #98: @42 = @42' */
  /* #99: {@45, @46, @47} = horzsplit(@42) */
  w45 = w42[0];
  w46 = w42[1];
  w47 = w42[2];
  /* #100: @47 = (2.*@47) */
  w47 = (2.* w47 );
  /* #101: @48 = (@0*@47) */
  w48  = (w0*w47);
  /* #102: @18 = (@18-@48) */
  w18 -= w48;
  /* #103: @48 = input[0][6] */
  w48 = arg[0] ? arg[0][6] : 0;
  /* #104: @45 = (2.*@45) */
  w45 = (2.* w45 );
  /* #105: @49 = (@48*@45) */
  w49  = (w48*w45);
  /* #106: @18 = (@18+@49) */
  w18 += w49;
  /* #107: @29 = @29' */
  /* #108: {@49, @50, @51} = horzsplit(@29) */
  w49 = w29[0];
  w50 = w29[1];
  w51 = w29[2];
  /* #109: @51 = (2.*@51) */
  w51 = (2.* w51 );
  /* #110: @52 = (@44*@51) */
  w52  = (w44*w51);
  /* #111: @18 = (@18+@52) */
  w18 += w52;
  /* #112: @50 = (2.*@50) */
  w50 = (2.* w50 );
  /* #113: @52 = (@48*@50) */
  w52  = (w48*w50);
  /* #114: @18 = (@18-@52) */
  w18 -= w52;
  /* #115: @52 = input[0][12] */
  w52 = arg[0] ? arg[0][12] : 0;
  /* #116: @53 = 0.5 */
  w53 = 5.0000000000000000e-01;
  /* #117: @27 = (@53*@27) */
  for (i=0, rr=w27, cs=w27; i<4; ++i) (*rr++)  = (w53*(*cs++));
  /* #118: {@54, @55, @56, @57} = vertsplit(@27) */
  w54 = w27[0];
  w55 = w27[1];
  w56 = w27[2];
  w57 = w27[3];
  /* #119: @58 = (@52*@57) */
  w58  = (w52*w57);
  /* #120: @18 = (@18+@58) */
  w18 += w58;
  /* #121: @58 = input[0][11] */
  w58 = arg[0] ? arg[0][11] : 0;
  /* #122: @59 = (@58*@56) */
  w59  = (w58*w56);
  /* #123: @18 = (@18+@59) */
  w18 += w59;
  /* #124: @59 = input[0][10] */
  w59 = arg[0] ? arg[0][10] : 0;
  /* #125: @60 = (@59*@55) */
  w60  = (w59*w55);
  /* #126: @18 = (@18+@60) */
  w18 += w60;
  /* #127: output[0][0] = @18 */
  if (res[0]) res[0][0] = w18;
  /* #128: @18 = (2.*@0) */
  w18 = (2.* w0 );
  /* #129: @41 = (-@41) */
  w41 = (- w41 );
  /* #130: @41 = (2.*@41) */
  w41 = (2.* w41 );
  /* #131: @60 = (@18*@41) */
  w60  = (w18*w41);
  /* #132: @61 = input[0][3] */
  w61 = arg[0] ? arg[0][3] : 0;
  /* #133: @62 = (@61*@39) */
  w62  = (w61*w39);
  /* #134: @60 = (@60+@62) */
  w60 += w62;
  /* #135: @62 = (@48*@40) */
  w62  = (w48*w40);
  /* #136: @60 = (@60+@62) */
  w60 += w62;
  /* #137: @62 = (@61*@47) */
  w62  = (w61*w47);
  /* #138: @60 = (@60-@62) */
  w60 -= w62;
  /* #139: @46 = (-@46) */
  w46 = (- w46 );
  /* #140: @46 = (2.*@46) */
  w46 = (2.* w46 );
  /* #141: @18 = (@18*@46) */
  w18 *= w46;
  /* #142: @60 = (@60+@18) */
  w60 += w18;
  /* #143: @18 = (@44*@45) */
  w18  = (w44*w45);
  /* #144: @60 = (@60+@18) */
  w60 += w18;
  /* #145: @18 = (@48*@51) */
  w18  = (w48*w51);
  /* #146: @60 = (@60+@18) */
  w60 += w18;
  /* #147: @18 = (@44*@50) */
  w18  = (w44*w50);
  /* #148: @60 = (@60+@18) */
  w60 += w18;
  /* #149: @18 = (@58*@57) */
  w18  = (w58*w57);
  /* #150: @60 = (@60-@18) */
  w60 -= w18;
  /* #151: @18 = (@52*@56) */
  w18  = (w52*w56);
  /* #152: @60 = (@60+@18) */
  w60 += w18;
  /* #153: @18 = (@59*@54) */
  w18  = (w59*w54);
  /* #154: @60 = (@60-@18) */
  w60 -= w18;
  /* #155: output[0][1] = @60 */
  if (res[0]) res[0][1] = w60;
  /* #156: @60 = (2.*@44) */
  w60 = (2.* w44 );
  /* #157: @41 = (@60*@41) */
  w41  = (w60*w41);
  /* #158: @18 = (@48*@39) */
  w18  = (w48*w39);
  /* #159: @41 = (@41+@18) */
  w41 += w18;
  /* #160: @18 = (@61*@40) */
  w18  = (w61*w40);
  /* #161: @41 = (@41-@18) */
  w41 -= w18;
  /* #162: @18 = (@48*@47) */
  w18  = (w48*w47);
  /* #163: @41 = (@41+@18) */
  w41 += w18;
  /* #164: @18 = (@0*@45) */
  w18  = (w0*w45);
  /* #165: @41 = (@41+@18) */
  w41 += w18;
  /* #166: @18 = (@61*@51) */
  w18  = (w61*w51);
  /* #167: @41 = (@41+@18) */
  w41 += w18;
  /* #168: @18 = (@0*@50) */
  w18  = (w0*w50);
  /* #169: @41 = (@41+@18) */
  w41 += w18;
  /* #170: @49 = (-@49) */
  w49 = (- w49 );
  /* #171: @49 = (2.*@49) */
  w49 = (2.* w49 );
  /* #172: @60 = (@60*@49) */
  w60 *= w49;
  /* #173: @41 = (@41+@60) */
  w41 += w60;
  /* #174: @60 = (@59*@57) */
  w60  = (w59*w57);
  /* #175: @41 = (@41+@60) */
  w41 += w60;
  /* #176: @60 = (@52*@55) */
  w60  = (w52*w55);
  /* #177: @41 = (@41-@60) */
  w41 -= w60;
  /* #178: @60 = (@58*@54) */
  w60  = (w58*w54);
  /* #179: @41 = (@41-@60) */
  w41 -= w60;
  /* #180: output[0][2] = @41 */
  if (res[0]) res[0][2] = w41;
  /* #181: @39 = (@44*@39) */
  w39  = (w44*w39);
  /* #182: @40 = (@0*@40) */
  w40  = (w0*w40);
  /* #183: @39 = (@39+@40) */
  w39 += w40;
  /* #184: @47 = (@44*@47) */
  w47  = (w44*w47);
  /* #185: @39 = (@39+@47) */
  w39 += w47;
  /* #186: @47 = (2.*@48) */
  w47 = (2.* w48 );
  /* #187: @46 = (@47*@46) */
  w46  = (w47*w46);
  /* #188: @39 = (@39+@46) */
  w39 += w46;
  /* #189: @45 = (@61*@45) */
  w45  = (w61*w45);
  /* #190: @39 = (@39+@45) */
  w39 += w45;
  /* #191: @51 = (@0*@51) */
  w51  = (w0*w51);
  /* #192: @39 = (@39+@51) */
  w39 += w51;
  /* #193: @50 = (@61*@50) */
  w50  = (w61*w50);
  /* #194: @39 = (@39-@50) */
  w39 -= w50;
  /* #195: @47 = (@47*@49) */
  w47 *= w49;
  /* #196: @39 = (@39+@47) */
  w39 += w47;
  /* #197: @59 = (@59*@56) */
  w59 *= w56;
  /* #198: @39 = (@39-@59) */
  w39 -= w59;
  /* #199: @58 = (@58*@55) */
  w58 *= w55;
  /* #200: @39 = (@39+@58) */
  w39 += w58;
  /* #201: @52 = (@52*@54) */
  w52 *= w54;
  /* #202: @39 = (@39-@52) */
  w39 -= w52;
  /* #203: output[0][3] = @39 */
  if (res[0]) res[0][3] = w39;
  /* #204: @39 = 0.1 */
  w39 = 1.0000000000000001e-01;
  /* #205: @28 = (@53*@28) */
  for (i=0, rr=w28, cs=w28; i<3; ++i) (*rr++)  = (w53*(*cs++));
  /* #206: @29 = (@39*@28) */
  for (i=0, rr=w29, cs=w28; i<3; ++i) (*rr++)  = (w39*(*cs++));
  /* #207: @29 = (-@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) *rr++ = (- *cs++ );
  /* #208: {@39, @52, @58} = vertsplit(@29) */
  w39 = w29[0];
  w52 = w29[1];
  w58 = w29[2];
  /* #209: @39 = (@39+@13) */
  w39 += w13;
  /* #210: output[0][4] = @39 */
  if (res[0]) res[0][4] = w39;
  /* #211: @52 = (@52+@10) */
  w52 += w10;
  /* #212: output[0][5] = @52 */
  if (res[0]) res[0][5] = w52;
  /* #213: @58 = (@58+@19) */
  w58 += w19;
  /* #214: output[0][6] = @58 */
  if (res[0]) res[0][6] = w58;
  /* #215: @58 = (@44*@57) */
  w58  = (w44*w57);
  /* #216: @19 = (@48*@56) */
  w19  = (w48*w56);
  /* #217: @58 = (@58-@19) */
  w58 -= w19;
  /* #218: @19 = (@61*@55) */
  w19  = (w61*w55);
  /* #219: @58 = (@58+@19) */
  w58 += w19;
  /* #220: @19 = (@0*@54) */
  w19  = (w0*w54);
  /* #221: @58 = (@58-@19) */
  w58 -= w19;
  /* #222: output[0][7] = @58 */
  if (res[0]) res[0][7] = w58;
  /* #223: @58 = (@61*@56) */
  w58  = (w61*w56);
  /* #224: @19 = (@0*@57) */
  w19  = (w0*w57);
  /* #225: @58 = (@58-@19) */
  w58 -= w19;
  /* #226: @19 = (@48*@55) */
  w19  = (w48*w55);
  /* #227: @58 = (@58+@19) */
  w58 += w19;
  /* #228: @19 = (@44*@54) */
  w19  = (w44*w54);
  /* #229: @58 = (@58-@19) */
  w58 -= w19;
  /* #230: output[0][8] = @58 */
  if (res[0]) res[0][8] = w58;
  /* #231: @57 = (@61*@57) */
  w57  = (w61*w57);
  /* #232: @56 = (@0*@56) */
  w56  = (w0*w56);
  /* #233: @57 = (@57+@56) */
  w57 += w56;
  /* #234: @55 = (@44*@55) */
  w55  = (w44*w55);
  /* #235: @57 = (@57-@55) */
  w57 -= w55;
  /* #236: @54 = (@48*@54) */
  w54  = (w48*w54);
  /* #237: @57 = (@57-@54) */
  w57 -= w54;
  /* #238: output[0][9] = @57 */
  if (res[0]) res[0][9] = w57;
  /* #239: @57 = input[0][19] */
  w57 = arg[0] ? arg[0][19] : 0;
  /* #240: @30 = (@53*@30) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w53*(*cs++));
  /* #241: {@53, @54, @55, @56} = vertsplit(@30) */
  w53 = w30[0];
  w54 = w30[1];
  w55 = w30[2];
  w56 = w30[3];
  /* #242: @58 = (@57*@56) */
  w58  = (w57*w56);
  /* #243: @19 = input[0][18] */
  w19 = arg[0] ? arg[0][18] : 0;
  /* #244: @52 = (@19*@55) */
  w52  = (w19*w55);
  /* #245: @58 = (@58+@52) */
  w58 += w52;
  /* #246: @52 = input[0][17] */
  w52 = arg[0] ? arg[0][17] : 0;
  /* #247: @10 = (@52*@54) */
  w10  = (w52*w54);
  /* #248: @58 = (@58+@10) */
  w58 += w10;
  /* #249: @35 = (2.*@35) */
  w35 = (2.* w35 );
  /* #250: @10 = (-@15) */
  w10 = (- w15 );
  /* #251: @29 = vertcat(@10, @8, @3) */
  rr=w29;
  *rr++ = w10;
  *rr++ = w8;
  *rr++ = w3;
  /* #252: @29 = @29' */
  /* #253: @29 = (@35*@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) (*rr++)  = (w35*(*cs++));
  /* #254: @29 = @29' */
  /* #255: @34 = (2.*@34) */
  w34 = (2.* w34 );
  /* #256: @10 = (@17*@8) */
  w10  = (w17*w8);
  /* #257: @3 = (@17*@15) */
  w3  = (w17*w15);
  /* #258: @39 = (-@11) */
  w39 = (- w11 );
  /* #259: @42 = vertcat(@10, @3, @39) */
  rr=w42;
  *rr++ = w10;
  *rr++ = w3;
  *rr++ = w39;
  /* #260: @42 = @42' */
  /* #261: @42 = (@34*@42) */
  for (i=0, rr=w42, cs=w42; i<3; ++i) (*rr++)  = (w34*(*cs++));
  /* #262: @42 = @42' */
  /* #263: @29 = (@29+@42) */
  for (i=0, rr=w29, cs=w42; i<3; ++i) (*rr++) += (*cs++);
  /* #264: @10 = sq(@44) */
  w10 = casadi_sq( w44 );
  /* #265: @3 = sq(@48) */
  w3 = casadi_sq( w48 );
  /* #266: @39 = (@10+@3) */
  w39  = (w10+w3);
  /* #267: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #268: @39 = (@6-@39) */
  w39  = (w6-w39);
  /* #269: @13 = (@0*@44) */
  w13  = (w0*w44);
  /* #270: @59 = (@48*@61) */
  w59  = (w48*w61);
  /* #271: @47 = (@13-@59) */
  w47  = (w13-w59);
  /* #272: @47 = (2.*@47) */
  w47 = (2.* w47 );
  /* #273: @49 = (@0*@48) */
  w49  = (w0*w48);
  /* #274: @50 = (@44*@61) */
  w50  = (w44*w61);
  /* #275: @51 = (@49+@50) */
  w51  = (w49+w50);
  /* #276: @51 = (2.*@51) */
  w51 = (2.* w51 );
  /* #277: @42 = horzcat(@39, @47, @51) */
  rr=w42;
  *rr++ = w39;
  *rr++ = w47;
  *rr++ = w51;
  /* #278: @42 = @42' */
  /* #279: @13 = (@13+@59) */
  w13 += w59;
  /* #280: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #281: @59 = sq(@0) */
  w59 = casadi_sq( w0 );
  /* #282: @3 = (@59+@3) */
  w3  = (w59+w3);
  /* #283: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #284: @3 = (@6-@3) */
  w3  = (w6-w3);
  /* #285: @44 = (@44*@48) */
  w44 *= w48;
  /* #286: @0 = (@0*@61) */
  w0 *= w61;
  /* #287: @61 = (@44-@0) */
  w61  = (w44-w0);
  /* #288: @61 = (2.*@61) */
  w61 = (2.* w61 );
  /* #289: @43 = horzcat(@13, @3, @61) */
  rr=w43;
  *rr++ = w13;
  *rr++ = w3;
  *rr++ = w61;
  /* #290: @43 = @43' */
  /* #291: @49 = (@49-@50) */
  w49 -= w50;
  /* #292: @49 = (2.*@49) */
  w49 = (2.* w49 );
  /* #293: @44 = (@44+@0) */
  w44 += w0;
  /* #294: @44 = (2.*@44) */
  w44 = (2.* w44 );
  /* #295: @59 = (@59+@10) */
  w59 += w10;
  /* #296: @59 = (2.*@59) */
  w59 = (2.* w59 );
  /* #297: @6 = (@6-@59) */
  w6 -= w59;
  /* #298: @63 = horzcat(@49, @44, @6) */
  rr=w63;
  *rr++ = w49;
  *rr++ = w44;
  *rr++ = w6;
  /* #299: @63 = @63' */
  /* #300: @23 = horzcat(@42, @43, @63) */
  rr=w23;
  for (i=0, cs=w42; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w63; i<3; ++i) *rr++ = *cs++;
  /* #301: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #302: @42 = mac(@24,@22,@2) */
  casadi_copy(w2, 3, w42);
  for (i=0, rr=w42; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w24+j, tt=w22+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #303: @49 = @42[2] */
  for (rr=(&w49), ss=w42+2; ss!=w42+3; ss+=1) *rr++ = *ss;
  /* #304: @44 = (@49*@37) */
  w44  = (w49*w37);
  /* #305: @6 = @42[1] */
  for (rr=(&w6), ss=w42+1; ss!=w42+2; ss+=1) *rr++ = *ss;
  /* #306: @59 = (@6*@38) */
  w59  = (w6*w38);
  /* #307: @44 = (@44-@59) */
  w44 -= w59;
  /* #308: (@2[0] += @44) */
  for (rr=w2+0, ss=(&w44); rr!=w2+1; rr+=1) *rr += *ss++;
  /* #309: @44 = @42[0] */
  for (rr=(&w44), ss=w42+0; ss!=w42+1; ss+=1) *rr++ = *ss;
  /* #310: @38 = (@44*@38) */
  w38  = (w44*w38);
  /* #311: @49 = (@49*@36) */
  w49 *= w36;
  /* #312: @38 = (@38-@49) */
  w38 -= w49;
  /* #313: (@2[1] += @38) */
  for (rr=w2+1, ss=(&w38); rr!=w2+2; rr+=1) *rr += *ss++;
  /* #314: @6 = (@6*@36) */
  w6 *= w36;
  /* #315: @44 = (@44*@37) */
  w44 *= w37;
  /* #316: @6 = (@6-@44) */
  w6 -= w44;
  /* #317: (@2[2] += @6) */
  for (rr=w2+2, ss=(&w6); rr!=w2+3; rr+=1) *rr += *ss++;
  /* #318: @2 = (@2+@28) */
  for (i=0, rr=w2, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #319: @6 = dot(@25, @2) */
  w6 = casadi_dot(3, w25, w2);
  /* #320: @25 = @25' */
  /* #321: @25 = (@6*@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) (*rr++)  = (w6*(*cs++));
  /* #322: @25 = @25' */
  /* #323: @29 = (@29+@25) */
  for (i=0, rr=w29, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #324: @25 = (@5*@29) */
  for (i=0, rr=w25, cs=w29; i<3; ++i) (*rr++)  = (w5*(*cs++));
  /* #325: @20 = @20' */
  /* #326: @1 = mac(@25,@20,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w25+j, tt=w20+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #327: @24 = @1' */
  for (i=0, rr=w24, cs=w1; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #328: {@25, @20, @28} = horzsplit(@24) */
  casadi_copy(w24, 3, w25);
  casadi_copy(w24+3, 3, w20);
  casadi_copy(w24+6, 3, w28);
  /* #329: @28 = @28' */
  /* #330: {@5, @44, @37} = horzsplit(@28) */
  w5 = w28[0];
  w44 = w28[1];
  w37 = w28[2];
  /* #331: @44 = (2.*@44) */
  w44 = (2.* w44 );
  /* #332: @36 = (@12*@44) */
  w36  = (w12*w44);
  /* #333: @58 = (@58+@36) */
  w58 += w36;
  /* #334: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #335: @36 = (@7*@5) */
  w36  = (w7*w5);
  /* #336: @58 = (@58-@36) */
  w58 -= w36;
  /* #337: @20 = @20' */
  /* #338: {@36, @38, @49} = horzsplit(@20) */
  w36 = w20[0];
  w38 = w20[1];
  w49 = w20[2];
  /* #339: @49 = (2.*@49) */
  w49 = (2.* w49 );
  /* #340: @59 = (@12*@49) */
  w59  = (w12*w49);
  /* #341: @58 = (@58-@59) */
  w58 -= w59;
  /* #342: @36 = (2.*@36) */
  w36 = (2.* w36 );
  /* #343: @59 = (@9*@36) */
  w59  = (w9*w36);
  /* #344: @58 = (@58+@59) */
  w58 += w59;
  /* #345: @25 = @25' */
  /* #346: {@59, @10, @0} = horzsplit(@25) */
  w59 = w25[0];
  w10 = w25[1];
  w0 = w25[2];
  /* #347: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #348: @50 = (@7*@0) */
  w50  = (w7*w0);
  /* #349: @58 = (@58+@50) */
  w58 += w50;
  /* #350: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #351: @50 = (@9*@10) */
  w50  = (w9*w10);
  /* #352: @58 = (@58-@50) */
  w58 -= w50;
  /* #353: output[0][10] = @58 */
  if (res[0]) res[0][10] = w58;
  /* #354: @58 = (@57*@55) */
  w58  = (w57*w55);
  /* #355: @50 = (@19*@56) */
  w50  = (w19*w56);
  /* #356: @58 = (@58-@50) */
  w58 -= w50;
  /* #357: @50 = (@52*@53) */
  w50  = (w52*w53);
  /* #358: @58 = (@58-@50) */
  w58 -= w50;
  /* #359: @50 = (2.*@12) */
  w50 = (2.* w12 );
  /* #360: @37 = (-@37) */
  w37 = (- w37 );
  /* #361: @37 = (2.*@37) */
  w37 = (2.* w37 );
  /* #362: @13 = (@50*@37) */
  w13  = (w50*w37);
  /* #363: @58 = (@58+@13) */
  w58 += w13;
  /* #364: @13 = (@14*@44) */
  w13  = (w14*w44);
  /* #365: @58 = (@58+@13) */
  w58 += w13;
  /* #366: @13 = (@9*@5) */
  w13  = (w9*w5);
  /* #367: @58 = (@58+@13) */
  w58 += w13;
  /* #368: @13 = (@14*@49) */
  w13  = (w14*w49);
  /* #369: @58 = (@58-@13) */
  w58 -= w13;
  /* #370: @38 = (-@38) */
  w38 = (- w38 );
  /* #371: @38 = (2.*@38) */
  w38 = (2.* w38 );
  /* #372: @50 = (@50*@38) */
  w50 *= w38;
  /* #373: @58 = (@58+@50) */
  w58 += w50;
  /* #374: @50 = (@7*@36) */
  w50  = (w7*w36);
  /* #375: @58 = (@58+@50) */
  w58 += w50;
  /* #376: @50 = (@9*@0) */
  w50  = (w9*w0);
  /* #377: @58 = (@58+@50) */
  w58 += w50;
  /* #378: @50 = (@7*@10) */
  w50  = (w7*w10);
  /* #379: @58 = (@58+@50) */
  w58 += w50;
  /* #380: output[0][11] = @58 */
  if (res[0]) res[0][11] = w58;
  /* #381: @58 = (@52*@56) */
  w58  = (w52*w56);
  /* #382: @50 = (@57*@54) */
  w50  = (w57*w54);
  /* #383: @58 = (@58-@50) */
  w58 -= w50;
  /* #384: @50 = (@19*@53) */
  w50  = (w19*w53);
  /* #385: @58 = (@58-@50) */
  w58 -= w50;
  /* #386: @50 = (2.*@7) */
  w50 = (2.* w7 );
  /* #387: @37 = (@50*@37) */
  w37  = (w50*w37);
  /* #388: @58 = (@58+@37) */
  w58 += w37;
  /* #389: @37 = (@9*@44) */
  w37  = (w9*w44);
  /* #390: @58 = (@58+@37) */
  w58 += w37;
  /* #391: @37 = (@14*@5) */
  w37  = (w14*w5);
  /* #392: @58 = (@58-@37) */
  w58 -= w37;
  /* #393: @37 = (@9*@49) */
  w37  = (w9*w49);
  /* #394: @58 = (@58+@37) */
  w58 += w37;
  /* #395: @37 = (@12*@36) */
  w37  = (w12*w36);
  /* #396: @58 = (@58+@37) */
  w58 += w37;
  /* #397: @37 = (@14*@0) */
  w37  = (w14*w0);
  /* #398: @58 = (@58+@37) */
  w58 += w37;
  /* #399: @37 = (@12*@10) */
  w37  = (w12*w10);
  /* #400: @58 = (@58+@37) */
  w58 += w37;
  /* #401: @59 = (-@59) */
  w59 = (- w59 );
  /* #402: @59 = (2.*@59) */
  w59 = (2.* w59 );
  /* #403: @50 = (@50*@59) */
  w50 *= w59;
  /* #404: @58 = (@58+@50) */
  w58 += w50;
  /* #405: output[0][12] = @58 */
  if (res[0]) res[0][12] = w58;
  /* #406: @19 = (@19*@54) */
  w19 *= w54;
  /* #407: @52 = (@52*@55) */
  w52 *= w55;
  /* #408: @19 = (@19-@52) */
  w19 -= w52;
  /* #409: @57 = (@57*@53) */
  w57 *= w53;
  /* #410: @19 = (@19-@57) */
  w19 -= w57;
  /* #411: @44 = (@7*@44) */
  w44  = (w7*w44);
  /* #412: @19 = (@19+@44) */
  w19 += w44;
  /* #413: @5 = (@12*@5) */
  w5  = (w12*w5);
  /* #414: @19 = (@19+@5) */
  w19 += w5;
  /* #415: @49 = (@7*@49) */
  w49  = (w7*w49);
  /* #416: @19 = (@19+@49) */
  w19 += w49;
  /* #417: @49 = (2.*@9) */
  w49 = (2.* w9 );
  /* #418: @38 = (@49*@38) */
  w38  = (w49*w38);
  /* #419: @19 = (@19+@38) */
  w19 += w38;
  /* #420: @36 = (@14*@36) */
  w36  = (w14*w36);
  /* #421: @19 = (@19+@36) */
  w19 += w36;
  /* #422: @0 = (@12*@0) */
  w0  = (w12*w0);
  /* #423: @19 = (@19+@0) */
  w19 += w0;
  /* #424: @10 = (@14*@10) */
  w10  = (w14*w10);
  /* #425: @19 = (@19-@10) */
  w19 -= w10;
  /* #426: @49 = (@49*@59) */
  w49 *= w59;
  /* #427: @19 = (@19+@49) */
  w19 += w49;
  /* #428: output[0][13] = @19 */
  if (res[0]) res[0][13] = w19;
  /* #429: @19 = 0.01 */
  w19 = 1.0000000000000000e-02;
  /* #430: @24 = 
  [[0.00250833, 0, 0], 
   [0, 0.00250833, 0], 
   [0, 0, 0.005]] */
  casadi_copy(casadi_c4, 9, w24);
  /* #431: @31 = (@24'\@31) */
  rr = w31;
  ss = w24;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 1, 1, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #432: @25 = (@19*@31) */
  for (i=0, rr=w25, cs=w31; i<3; ++i) (*rr++)  = (w19*(*cs++));
  /* #433: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) *rr++ = (- *cs++ );
  /* #434: {@19, @49, @59} = vertsplit(@25) */
  w19 = w25[0];
  w49 = w25[1];
  w59 = w25[2];
  /* #435: @10 = (@7*@56) */
  w10  = (w7*w56);
  /* #436: @19 = (@19+@10) */
  w19 += w10;
  /* #437: @10 = (@9*@55) */
  w10  = (w9*w55);
  /* #438: @19 = (@19-@10) */
  w19 -= w10;
  /* #439: @10 = (@14*@54) */
  w10  = (w14*w54);
  /* #440: @19 = (@19+@10) */
  w19 += w10;
  /* #441: @10 = (@12*@53) */
  w10  = (w12*w53);
  /* #442: @19 = (@19-@10) */
  w19 -= w10;
  /* #443: output[0][14] = @19 */
  if (res[0]) res[0][14] = w19;
  /* #444: @19 = (@12*@56) */
  w19  = (w12*w56);
  /* #445: @49 = (@49-@19) */
  w49 -= w19;
  /* #446: @19 = (@14*@55) */
  w19  = (w14*w55);
  /* #447: @49 = (@49+@19) */
  w49 += w19;
  /* #448: @19 = (@9*@54) */
  w19  = (w9*w54);
  /* #449: @49 = (@49+@19) */
  w49 += w19;
  /* #450: @19 = (@7*@53) */
  w19  = (w7*w53);
  /* #451: @49 = (@49-@19) */
  w49 -= w19;
  /* #452: output[0][15] = @49 */
  if (res[0]) res[0][15] = w49;
  /* #453: @14 = (@14*@56) */
  w14 *= w56;
  /* #454: @59 = (@59+@14) */
  w59 += w14;
  /* #455: @12 = (@12*@55) */
  w12 *= w55;
  /* #456: @59 = (@59+@12) */
  w59 += w12;
  /* #457: @7 = (@7*@54) */
  w7 *= w54;
  /* #458: @59 = (@59-@7) */
  w59 -= w7;
  /* #459: @9 = (@9*@53) */
  w9 *= w53;
  /* #460: @59 = (@59-@9) */
  w59 -= w9;
  /* #461: output[0][16] = @59 */
  if (res[0]) res[0][16] = w59;
  /* #462: @25 = (@4*@34) */
  for (i=0, rr=w25, cr=w4; i<3; ++i) (*rr++)  = ((*cr++)*w34);
  /* #463: {@34, @59, @9} = vertsplit(@25) */
  w34 = w25[0];
  w59 = w25[1];
  w9 = w25[2];
  /* #464: @53 = (@15*@59) */
  w53  = (w15*w59);
  /* #465: @53 = (@11*@53) */
  w53  = (w11*w53);
  /* #466: @53 = (-@53) */
  w53 = (- w53 );
  /* #467: @9 = (@17*@9) */
  w9  = (w17*w9);
  /* #468: @53 = (@53-@9) */
  w53 -= w9;
  /* #469: @9 = (@8*@34) */
  w9  = (w8*w34);
  /* #470: @9 = (@11*@9) */
  w9  = (w11*w9);
  /* #471: @53 = (@53-@9) */
  w53 -= w9;
  /* #472: @2 = (@16*@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) (*rr++)  = (w16*(*cs++));
  /* #473: @25 = (@4*@6) */
  for (i=0, rr=w25, cr=w4; i<3; ++i) (*rr++)  = ((*cr++)*w6);
  /* #474: @2 = (@2+@25) */
  for (i=0, rr=w2, cs=w25; i<3; ++i) (*rr++) += (*cs++);
  /* #475: {@6, @16, @9} = vertsplit(@2) */
  w6 = w2[0];
  w16 = w2[1];
  w9 = w2[2];
  /* #476: @9 = (@11*@9) */
  w9  = (w11*w9);
  /* #477: @53 = (@53-@9) */
  w53 -= w9;
  /* #478: @9 = (@15*@16) */
  w9  = (w15*w16);
  /* #479: @9 = (@17*@9) */
  w9  = (w17*w9);
  /* #480: @53 = (@53+@9) */
  w53 += w9;
  /* #481: @9 = (@8*@6) */
  w9  = (w8*w6);
  /* #482: @9 = (@17*@9) */
  w9  = (w17*w9);
  /* #483: @53 = (@53+@9) */
  w53 += w9;
  /* #484: output[0][17] = @53 */
  if (res[0]) res[0][17] = w53;
  /* #485: @4 = (@4*@35) */
  for (i=0, rr=w4; i<3; ++i) (*rr++) *= w35;
  /* #486: {@35, @53, NULL} = vertsplit(@4) */
  w35 = w4[0];
  w53 = w4[1];
  /* #487: @35 = (@8*@35) */
  w35  = (w8*w35);
  /* #488: @35 = (-@35) */
  w35 = (- w35 );
  /* #489: @53 = (@15*@53) */
  w53  = (w15*w53);
  /* #490: @35 = (@35-@53) */
  w35 -= w53;
  /* #491: @59 = (@17*@59) */
  w59  = (w17*w59);
  /* #492: @59 = (@8*@59) */
  w59  = (w8*w59);
  /* #493: @35 = (@35+@59) */
  w35 += w59;
  /* #494: @17 = (@17*@34) */
  w17 *= w34;
  /* #495: @17 = (@15*@17) */
  w17  = (w15*w17);
  /* #496: @35 = (@35-@17) */
  w35 -= w17;
  /* #497: @16 = (@11*@16) */
  w16  = (w11*w16);
  /* #498: @8 = (@8*@16) */
  w8 *= w16;
  /* #499: @35 = (@35+@8) */
  w35 += w8;
  /* #500: @11 = (@11*@6) */
  w11 *= w6;
  /* #501: @15 = (@15*@11) */
  w15 *= w11;
  /* #502: @35 = (@35-@15) */
  w35 -= w15;
  /* #503: output[0][18] = @35 */
  if (res[0]) res[0][18] = w35;
  /* #504: output[0][19] = @32 */
  if (res[0]) res[0][19] = w32;
  /* #505: output[0][20] = @33 */
  if (res[0]) res[0][20] = w33;
  /* #506: @33 = dot(@21, @29) */
  w33 = casadi_dot(3, w21, w29);
  /* #507: output[0][21] = @33 */
  if (res[0]) res[0][21] = w33;
  /* #508: {@33, @32, @35} = vertsplit(@31) */
  w33 = w31[0];
  w32 = w31[1];
  w35 = w31[2];
  /* #509: output[0][22] = @33 */
  if (res[0]) res[0][22] = w33;
  /* #510: output[0][23] = @32 */
  if (res[0]) res[0][23] = w32;
  /* #511: output[0][24] = @35 */
  if (res[0]) res[0][24] = w35;
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_nav_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int payload_nav_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_nav_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void payload_nav_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int payload_nav_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void payload_nav_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void payload_nav_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void payload_nav_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int payload_nav_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int payload_nav_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real payload_nav_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* payload_nav_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* payload_nav_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* payload_nav_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* payload_nav_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int payload_nav_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 144;
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_nav_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 13*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 144*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
