/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_FrenSer_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[61] = {57, 1, 0, 57, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56};
static const casadi_int casadi_s1[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[8] = {73, 1, 0, 4, 19, 20, 21, 22};
static const casadi_int casadi_s5[3] = {1, 0, 0};

/* drone_FrenSer_constr_h_fun_jac_uxt_zt:(i0[57],i1[16],i2[0],i3)->(o0,o1[73x1,4nz],o2[1x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35, w36, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46, w47, w48, w49, w50, w51, w52, w53, w54, w55, w56, *w57=w+57, *w58=w+114, *w59=w+118;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = input[0][4] */
  w4 = arg[0] ? arg[0][4] : 0;
  /* #5: @5 = input[0][5] */
  w5 = arg[0] ? arg[0][5] : 0;
  /* #6: @6 = input[0][6] */
  w6 = arg[0] ? arg[0][6] : 0;
  /* #7: @7 = input[0][7] */
  w7 = arg[0] ? arg[0][7] : 0;
  /* #8: @8 = input[0][8] */
  w8 = arg[0] ? arg[0][8] : 0;
  /* #9: @9 = input[0][9] */
  w9 = arg[0] ? arg[0][9] : 0;
  /* #10: @10 = input[0][10] */
  w10 = arg[0] ? arg[0][10] : 0;
  /* #11: @11 = input[0][11] */
  w11 = arg[0] ? arg[0][11] : 0;
  /* #12: @12 = input[0][12] */
  w12 = arg[0] ? arg[0][12] : 0;
  /* #13: @13 = input[0][13] */
  w13 = arg[0] ? arg[0][13] : 0;
  /* #14: @14 = input[0][14] */
  w14 = arg[0] ? arg[0][14] : 0;
  /* #15: @15 = input[0][15] */
  w15 = arg[0] ? arg[0][15] : 0;
  /* #16: @16 = input[0][16] */
  w16 = arg[0] ? arg[0][16] : 0;
  /* #17: @17 = input[0][17] */
  w17 = arg[0] ? arg[0][17] : 0;
  /* #18: @18 = input[0][18] */
  w18 = arg[0] ? arg[0][18] : 0;
  /* #19: @19 = input[0][19] */
  w19 = arg[0] ? arg[0][19] : 0;
  /* #20: @20 = input[0][20] */
  w20 = arg[0] ? arg[0][20] : 0;
  /* #21: @21 = input[0][21] */
  w21 = arg[0] ? arg[0][21] : 0;
  /* #22: @22 = input[0][22] */
  w22 = arg[0] ? arg[0][22] : 0;
  /* #23: @23 = input[0][23] */
  w23 = arg[0] ? arg[0][23] : 0;
  /* #24: @24 = input[0][24] */
  w24 = arg[0] ? arg[0][24] : 0;
  /* #25: @25 = input[0][25] */
  w25 = arg[0] ? arg[0][25] : 0;
  /* #26: @26 = input[0][26] */
  w26 = arg[0] ? arg[0][26] : 0;
  /* #27: @27 = input[0][27] */
  w27 = arg[0] ? arg[0][27] : 0;
  /* #28: @28 = input[0][28] */
  w28 = arg[0] ? arg[0][28] : 0;
  /* #29: @29 = input[0][29] */
  w29 = arg[0] ? arg[0][29] : 0;
  /* #30: @30 = input[0][30] */
  w30 = arg[0] ? arg[0][30] : 0;
  /* #31: @31 = input[0][31] */
  w31 = arg[0] ? arg[0][31] : 0;
  /* #32: @32 = input[0][32] */
  w32 = arg[0] ? arg[0][32] : 0;
  /* #33: @33 = input[0][33] */
  w33 = arg[0] ? arg[0][33] : 0;
  /* #34: @34 = input[0][34] */
  w34 = arg[0] ? arg[0][34] : 0;
  /* #35: @35 = input[0][35] */
  w35 = arg[0] ? arg[0][35] : 0;
  /* #36: @36 = input[0][36] */
  w36 = arg[0] ? arg[0][36] : 0;
  /* #37: @37 = input[0][37] */
  w37 = arg[0] ? arg[0][37] : 0;
  /* #38: @38 = input[0][38] */
  w38 = arg[0] ? arg[0][38] : 0;
  /* #39: @39 = input[0][39] */
  w39 = arg[0] ? arg[0][39] : 0;
  /* #40: @40 = input[0][40] */
  w40 = arg[0] ? arg[0][40] : 0;
  /* #41: @41 = input[0][41] */
  w41 = arg[0] ? arg[0][41] : 0;
  /* #42: @42 = input[0][42] */
  w42 = arg[0] ? arg[0][42] : 0;
  /* #43: @43 = input[0][43] */
  w43 = arg[0] ? arg[0][43] : 0;
  /* #44: @44 = input[0][44] */
  w44 = arg[0] ? arg[0][44] : 0;
  /* #45: @45 = input[0][45] */
  w45 = arg[0] ? arg[0][45] : 0;
  /* #46: @46 = input[0][46] */
  w46 = arg[0] ? arg[0][46] : 0;
  /* #47: @47 = input[0][47] */
  w47 = arg[0] ? arg[0][47] : 0;
  /* #48: @48 = input[0][48] */
  w48 = arg[0] ? arg[0][48] : 0;
  /* #49: @49 = input[0][49] */
  w49 = arg[0] ? arg[0][49] : 0;
  /* #50: @50 = input[0][50] */
  w50 = arg[0] ? arg[0][50] : 0;
  /* #51: @51 = input[0][51] */
  w51 = arg[0] ? arg[0][51] : 0;
  /* #52: @52 = input[0][52] */
  w52 = arg[0] ? arg[0][52] : 0;
  /* #53: @53 = input[0][53] */
  w53 = arg[0] ? arg[0][53] : 0;
  /* #54: @54 = input[0][54] */
  w54 = arg[0] ? arg[0][54] : 0;
  /* #55: @55 = input[0][55] */
  w55 = arg[0] ? arg[0][55] : 0;
  /* #56: @56 = input[0][56] */
  w56 = arg[0] ? arg[0][56] : 0;
  /* #57: @57 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29, @30, @31, @32, @33, @34, @35, @36, @37, @38, @39, @40, @41, @42, @43, @44, @45, @46, @47, @48, @49, @50, @51, @52, @53, @54, @55, @56) */
  rr=w57;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w33;
  *rr++ = w34;
  *rr++ = w35;
  *rr++ = w36;
  *rr++ = w37;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w42;
  *rr++ = w43;
  *rr++ = w44;
  *rr++ = w45;
  *rr++ = w46;
  *rr++ = w47;
  *rr++ = w48;
  *rr++ = w49;
  *rr++ = w50;
  *rr++ = w51;
  *rr++ = w52;
  *rr++ = w53;
  *rr++ = w54;
  *rr++ = w55;
  *rr++ = w56;
  /* #58: @58 = @57[3:7] */
  for (rr=w58, ss=w57+3; ss!=w57+7; ss+=1) *rr++ = *ss;
  /* #59: @0 = dot(@58, @58) */
  w0 = casadi_dot(4, w58, w58);
  /* #60: @1 = 1 */
  w1 = 1.;
  /* #61: @0 = (@0-@1) */
  w0 -= w1;
  /* #62: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #63: @59 = zeros(73x1,4nz) */
  casadi_clear(w59, 4);
  /* #64: @57 = zeros(57x1) */
  casadi_clear(w57, 57);
  /* #65: @58 = (2.*@58) */
  for (i=0, rr=w58, cs=w58; i<4; ++i) *rr++ = (2.* *cs++ );
  /* #66: (@57[3:7] += @58) */
  for (rr=w57+3, ss=w58; rr!=w57+7; rr+=1) *rr += *ss++;
  /* #67: {NULL, NULL, NULL, @0, @1, @2, @3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@57) */
  w0 = w57[3];
  w1 = w57[4];
  w2 = w57[5];
  w3 = w57[6];
  /* #68: (@59[0] = @0) */
  for (rr=w59+0, ss=(&w0); rr!=w59+1; rr+=1) *rr = *ss++;
  /* #69: (@59[1] = @1) */
  for (rr=w59+1, ss=(&w1); rr!=w59+2; rr+=1) *rr = *ss++;
  /* #70: (@59[2] = @2) */
  for (rr=w59+2, ss=(&w2); rr!=w59+3; rr+=1) *rr = *ss++;
  /* #71: (@59[3] = @3) */
  for (rr=w59+3, ss=(&w3); rr!=w59+4; rr+=1) *rr = *ss++;
  /* #72: output[1][0] = @59 */
  casadi_copy(w59, 4, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_FrenSer_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_FrenSer_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_FrenSer_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_FrenSer_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_FrenSer_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int drone_FrenSer_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real drone_FrenSer_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_FrenSer_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_FrenSer_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_FrenSer_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_FrenSer_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 61;
  if (sz_res) *sz_res = 60;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 122;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 61*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 60*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 122*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
