/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) payload_accel_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

static const casadi_int casadi_s0[3] = {0, 1, 2};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[12] = {3, 3, 0, 3, 5, 6, 0, 1, 2, 1, 2, 2};
static const casadi_int casadi_s3[12] = {3, 3, 0, 1, 3, 6, 0, 0, 1, 0, 1, 2};
static const casadi_int casadi_s4[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s5[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s6[4] = {0, 1, 0, 0};

static const casadi_real casadi_c0[3] = {0., 0., -1.9613299999999999e+01};
static const casadi_real casadi_c1[3] = {0., 0., -2.4516624999999999e+00};
static const casadi_real casadi_c2[3] = {0., 0., 1.};
static const casadi_real casadi_c3[3] = {0., 0., 5.0000000000000000e-01};
static const casadi_real casadi_c4[9] = {8.3333333333333326e-01, 0., 0., 0., 8.3333333333333326e-01, 0., 0., 0., 1.3333333333333333e+00};
static const casadi_real casadi_c5[9] = {2.5083333333333338e-03, 0., 0., 0., 2.5083333333333338e-03, 0., 0., 0., 5.0000000000000010e-03};

/* payload_accel_expl_ode_fun:(i0[24],i1[4],i2[0])->(o0[24]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, *w15=w+18, *w16=w+22, *w17=w+25, *w18=w+28, w19, w20, w21, w22, w23, w24, w25, w26, w27, *w28=w+40, *w29=w+43, *w30=w+46, *w31=w+49, *w32=w+58;
  /* #0: @0 = input[0][7] */
  w0 = arg[0] ? arg[0][7] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @1 = input[0][8] */
  w1 = arg[0] ? arg[0][8] : 0;
  /* #3: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #4: @2 = input[0][9] */
  w2 = arg[0] ? arg[0][9] : 0;
  /* #5: output[0][2] = @2 */
  if (res[0]) res[0][2] = w2;
  /* #6: @3 = 0.5 */
  w3 = 5.0000000000000000e-01;
  /* #7: @4 = input[0][10] */
  w4 = arg[0] ? arg[0][10] : 0;
  /* #8: @5 = input[0][4] */
  w5 = arg[0] ? arg[0][4] : 0;
  /* #9: @6 = (@4*@5) */
  w6  = (w4*w5);
  /* #10: @6 = (-@6) */
  w6 = (- w6 );
  /* #11: @7 = input[0][11] */
  w7 = arg[0] ? arg[0][11] : 0;
  /* #12: @8 = input[0][5] */
  w8 = arg[0] ? arg[0][5] : 0;
  /* #13: @9 = (@7*@8) */
  w9  = (w7*w8);
  /* #14: @6 = (@6-@9) */
  w6 -= w9;
  /* #15: @9 = input[0][12] */
  w9 = arg[0] ? arg[0][12] : 0;
  /* #16: @10 = input[0][6] */
  w10 = arg[0] ? arg[0][6] : 0;
  /* #17: @11 = (@9*@10) */
  w11  = (w9*w10);
  /* #18: @6 = (@6-@11) */
  w6 -= w11;
  /* #19: @11 = input[0][3] */
  w11 = arg[0] ? arg[0][3] : 0;
  /* #20: @12 = (@4*@11) */
  w12  = (w4*w11);
  /* #21: @13 = (@7*@10) */
  w13  = (w7*w10);
  /* #22: @12 = (@12+@13) */
  w12 += w13;
  /* #23: @13 = (@9*@8) */
  w13  = (w9*w8);
  /* #24: @12 = (@12-@13) */
  w12 -= w13;
  /* #25: @13 = (@7*@11) */
  w13  = (w7*w11);
  /* #26: @14 = (@4*@10) */
  w14  = (w4*w10);
  /* #27: @13 = (@13-@14) */
  w13 -= w14;
  /* #28: @14 = (@9*@5) */
  w14  = (w9*w5);
  /* #29: @13 = (@13+@14) */
  w13 += w14;
  /* #30: @4 = (@4*@8) */
  w4 *= w8;
  /* #31: @7 = (@7*@5) */
  w7 *= w5;
  /* #32: @4 = (@4-@7) */
  w4 -= w7;
  /* #33: @9 = (@9*@11) */
  w9 *= w11;
  /* #34: @4 = (@4+@9) */
  w4 += w9;
  /* #35: @15 = vertcat(@6, @12, @13, @4) */
  rr=w15;
  *rr++ = w6;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w4;
  /* #36: @15 = (@3*@15) */
  for (i=0, rr=w15, cs=w15; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #37: output[0][3] = @15 */
  if (res[0]) casadi_copy(w15, 4, res[0]+3);
  /* #38: @16 = [0, 0, -19.6133] */
  casadi_copy(casadi_c0, 3, w16);
  /* #39: @6 = 0 */
  w6 = 0.;
  /* #40: @17 = [0, 0, -2.45166] */
  casadi_copy(casadi_c1, 3, w17);
  /* #41: @12 = input[1][0] */
  w12 = arg[1] ? arg[1][0] : 0;
  /* #42: @18 = zeros(3x1) */
  casadi_clear(w18, 3);
  /* #43: @13 = 1 */
  w13 = 1.;
  /* #44: @4 = input[0][15] */
  w4 = arg[0] ? arg[0][15] : 0;
  /* #45: @9 = sq(@4) */
  w9 = casadi_sq( w4 );
  /* #46: @7 = input[0][16] */
  w7 = arg[0] ? arg[0][16] : 0;
  /* #47: @14 = sq(@7) */
  w14 = casadi_sq( w7 );
  /* #48: @19 = (@9+@14) */
  w19  = (w9+w14);
  /* #49: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #50: @19 = (@13-@19) */
  w19  = (w13-w19);
  /* #51: @20 = input[0][14] */
  w20 = arg[0] ? arg[0][14] : 0;
  /* #52: @21 = (@20*@4) */
  w21  = (w20*w4);
  /* #53: @22 = input[0][13] */
  w22 = arg[0] ? arg[0][13] : 0;
  /* #54: @23 = (@7*@22) */
  w23  = (w7*w22);
  /* #55: @24 = (@21-@23) */
  w24  = (w21-w23);
  /* #56: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #57: @25 = (@20*@7) */
  w25  = (w20*w7);
  /* #58: @26 = (@4*@22) */
  w26  = (w4*w22);
  /* #59: @27 = (@25+@26) */
  w27  = (w25+w26);
  /* #60: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #61: @28 = horzcat(@19, @24, @27) */
  rr=w28;
  *rr++ = w19;
  *rr++ = w24;
  *rr++ = w27;
  /* #62: @28 = @28' */
  /* #63: @21 = (@21+@23) */
  w21 += w23;
  /* #64: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #65: @23 = sq(@20) */
  w23 = casadi_sq( w20 );
  /* #66: @14 = (@23+@14) */
  w14  = (w23+w14);
  /* #67: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #68: @14 = (@13-@14) */
  w14  = (w13-w14);
  /* #69: @19 = (@4*@7) */
  w19  = (w4*w7);
  /* #70: @24 = (@20*@22) */
  w24  = (w20*w22);
  /* #71: @27 = (@19-@24) */
  w27  = (w19-w24);
  /* #72: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #73: @29 = horzcat(@21, @14, @27) */
  rr=w29;
  *rr++ = w21;
  *rr++ = w14;
  *rr++ = w27;
  /* #74: @29 = @29' */
  /* #75: @25 = (@25-@26) */
  w25 -= w26;
  /* #76: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #77: @19 = (@19+@24) */
  w19 += w24;
  /* #78: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #79: @23 = (@23+@9) */
  w23 += w9;
  /* #80: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #81: @23 = (@13-@23) */
  w23  = (w13-w23);
  /* #82: @30 = horzcat(@25, @19, @23) */
  rr=w30;
  *rr++ = w25;
  *rr++ = w19;
  *rr++ = w23;
  /* #83: @30 = @30' */
  /* #84: @31 = horzcat(@28, @29, @30) */
  rr=w31;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<3; ++i) *rr++ = *cs++;
  /* #85: @32 = @31' */
  for (i=0, rr=w32, cs=w31; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #86: @28 = [0, 0, 1] */
  casadi_copy(casadi_c2, 3, w28);
  /* #87: @29 = mac(@32,@28,@18) */
  casadi_copy(w18, 3, w29);
  for (i=0, rr=w29; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w32+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #88: @29 = (@12*@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #89: @17 = (@17+@29) */
  for (i=0, rr=w17, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #90: @17 = @17' */
  /* #91: @12 = input[0][20] */
  w12 = arg[0] ? arg[0][20] : 0;
  /* #92: @25 = sin(@12) */
  w25 = sin( w12 );
  /* #93: @19 = input[0][21] */
  w19 = arg[0] ? arg[0][21] : 0;
  /* #94: @23 = cos(@19) */
  w23 = cos( w19 );
  /* #95: @9 = (@25*@23) */
  w9  = (w25*w23);
  /* #96: @19 = sin(@19) */
  w19 = sin( w19 );
  /* #97: @24 = (@25*@19) */
  w24  = (w25*w19);
  /* #98: @12 = cos(@12) */
  w12 = cos( w12 );
  /* #99: @29 = vertcat(@9, @24, @12) */
  rr=w29;
  *rr++ = w9;
  *rr++ = w24;
  *rr++ = w12;
  /* #100: @9 = mac(@17,@29,@6) */
  casadi_copy((&w6), 1, (&w9));
  for (i=0, rr=(&w9); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w29+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #101: @29 = (@9*@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #102: @16 = (@16+@29) */
  for (i=0, rr=w16, cs=w29; i<3; ++i) (*rr++) += (*cs++);
  /* #103: @9 = 0.1 */
  w9 = 1.0000000000000001e-01;
  /* #104: @28 = vertcat(@0, @1, @2) */
  rr=w28;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  /* #105: @28 = (@9*@28) */
  for (i=0, rr=w28, cs=w28; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #106: @16 = (@16-@28) */
  for (i=0, rr=w16, cs=w28; i<3; ++i) (*rr++) -= (*cs++);
  /* #107: @9 = 2 */
  w9 = 2.;
  /* #108: @16 = (@16/@9) */
  for (i=0, rr=w16; i<3; ++i) (*rr++) /= w9;
  /* #109: output[0][4] = @16 */
  if (res[0]) casadi_copy(w16, 3, res[0]+7);
  /* #110: @9 = sq(@8) */
  w9 = casadi_sq( w8 );
  /* #111: @0 = sq(@10) */
  w0 = casadi_sq( w10 );
  /* #112: @1 = (@9+@0) */
  w1  = (w9+w0);
  /* #113: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #114: @1 = (@13-@1) */
  w1  = (w13-w1);
  /* #115: @2 = (@5*@8) */
  w2  = (w5*w8);
  /* #116: @24 = (@10*@11) */
  w24  = (w10*w11);
  /* #117: @26 = (@2-@24) */
  w26  = (w2-w24);
  /* #118: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #119: @21 = (@5*@10) */
  w21  = (w5*w10);
  /* #120: @14 = (@8*@11) */
  w14  = (w8*w11);
  /* #121: @27 = (@21+@14) */
  w27  = (w21+w14);
  /* #122: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #123: @16 = horzcat(@1, @26, @27) */
  rr=w16;
  *rr++ = w1;
  *rr++ = w26;
  *rr++ = w27;
  /* #124: @16 = @16' */
  /* #125: @2 = (@2+@24) */
  w2 += w24;
  /* #126: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #127: @24 = sq(@5) */
  w24 = casadi_sq( w5 );
  /* #128: @0 = (@24+@0) */
  w0  = (w24+w0);
  /* #129: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #130: @0 = (@13-@0) */
  w0  = (w13-w0);
  /* #131: @8 = (@8*@10) */
  w8 *= w10;
  /* #132: @5 = (@5*@11) */
  w5 *= w11;
  /* #133: @11 = (@8-@5) */
  w11  = (w8-w5);
  /* #134: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #135: @28 = horzcat(@2, @0, @11) */
  rr=w28;
  *rr++ = w2;
  *rr++ = w0;
  *rr++ = w11;
  /* #136: @28 = @28' */
  /* #137: @21 = (@21-@14) */
  w21 -= w14;
  /* #138: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #139: @8 = (@8+@5) */
  w8 += w5;
  /* #140: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #141: @24 = (@24+@9) */
  w24 += w9;
  /* #142: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #143: @13 = (@13-@24) */
  w13 -= w24;
  /* #144: @30 = horzcat(@21, @8, @13) */
  rr=w30;
  *rr++ = w21;
  *rr++ = w8;
  *rr++ = w13;
  /* #145: @30 = @30' */
  /* #146: @32 = horzcat(@16, @28, @30) */
  rr=w32;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<3; ++i) *rr++ = *cs++;
  /* #147: @31 = @32' */
  for (i=0, rr=w31, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #148: @16 = [0, 0, 0.5] */
  casadi_copy(casadi_c3, 3, w16);
  /* #149: @18 = mac(@31,@16,@18) */
  for (i=0, rr=w18; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w31+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #150: @21 = @18[1] */
  for (rr=(&w21), ss=w18+1; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #151: @8 = @29[2] */
  for (rr=(&w8), ss=w29+2; ss!=w29+3; ss+=1) *rr++ = *ss;
  /* #152: @13 = (@21*@8) */
  w13  = (w21*w8);
  /* #153: @24 = @18[2] */
  for (rr=(&w24), ss=w18+2; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #154: @9 = @29[1] */
  for (rr=(&w9), ss=w29+1; ss!=w29+2; ss+=1) *rr++ = *ss;
  /* #155: @5 = (@24*@9) */
  w5  = (w24*w9);
  /* #156: @13 = (@13-@5) */
  w13 -= w5;
  /* #157: @5 = @29[0] */
  for (rr=(&w5), ss=w29+0; ss!=w29+1; ss+=1) *rr++ = *ss;
  /* #158: @24 = (@24*@5) */
  w24 *= w5;
  /* #159: @14 = @18[0] */
  for (rr=(&w14), ss=w18+0; ss!=w18+1; ss+=1) *rr++ = *ss;
  /* #160: @8 = (@14*@8) */
  w8  = (w14*w8);
  /* #161: @24 = (@24-@8) */
  w24 -= w8;
  /* #162: @14 = (@14*@9) */
  w14 *= w9;
  /* #163: @21 = (@21*@5) */
  w21 *= w5;
  /* #164: @14 = (@14-@21) */
  w14 -= w21;
  /* #165: @18 = vertcat(@13, @24, @14) */
  rr=w18;
  *rr++ = w13;
  *rr++ = w24;
  *rr++ = w14;
  /* #166: @31 = 
  [[0.833333, 0, 0], 
   [0, 0.833333, 0], 
   [0, 0, 1.33333]] */
  casadi_copy(casadi_c4, 9, w31);
  /* #167: @18 = (@31\@18) */
  rr = w18;
  ss = w31;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 1, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #168: output[0][5] = @18 */
  if (res[0]) casadi_copy(w18, 3, res[0]+10);
  /* #169: @13 = input[0][17] */
  w13 = arg[0] ? arg[0][17] : 0;
  /* #170: @24 = (@13*@20) */
  w24  = (w13*w20);
  /* #171: @24 = (-@24) */
  w24 = (- w24 );
  /* #172: @14 = input[0][18] */
  w14 = arg[0] ? arg[0][18] : 0;
  /* #173: @21 = (@14*@4) */
  w21  = (w14*w4);
  /* #174: @24 = (@24-@21) */
  w24 -= w21;
  /* #175: @21 = input[0][19] */
  w21 = arg[0] ? arg[0][19] : 0;
  /* #176: @5 = (@21*@7) */
  w5  = (w21*w7);
  /* #177: @24 = (@24-@5) */
  w24 -= w5;
  /* #178: @5 = (@13*@22) */
  w5  = (w13*w22);
  /* #179: @9 = (@14*@7) */
  w9  = (w14*w7);
  /* #180: @5 = (@5+@9) */
  w5 += w9;
  /* #181: @9 = (@21*@4) */
  w9  = (w21*w4);
  /* #182: @5 = (@5-@9) */
  w5 -= w9;
  /* #183: @9 = (@14*@22) */
  w9  = (w14*w22);
  /* #184: @7 = (@13*@7) */
  w7  = (w13*w7);
  /* #185: @9 = (@9-@7) */
  w9 -= w7;
  /* #186: @7 = (@21*@20) */
  w7  = (w21*w20);
  /* #187: @9 = (@9+@7) */
  w9 += w7;
  /* #188: @4 = (@13*@4) */
  w4  = (w13*w4);
  /* #189: @20 = (@14*@20) */
  w20  = (w14*w20);
  /* #190: @4 = (@4-@20) */
  w4 -= w20;
  /* #191: @22 = (@21*@22) */
  w22  = (w21*w22);
  /* #192: @4 = (@4+@22) */
  w4 += w22;
  /* #193: @15 = vertcat(@24, @5, @9, @4) */
  rr=w15;
  *rr++ = w24;
  *rr++ = w5;
  *rr++ = w9;
  *rr++ = w4;
  /* #194: @15 = (@3*@15) */
  for (i=0, rr=w15, cs=w15; i<4; ++i) (*rr++)  = (w3*(*cs++));
  /* #195: output[0][6] = @15 */
  if (res[0]) casadi_copy(w15, 4, res[0]+13);
  /* #196: @3 = input[1][1] */
  w3 = arg[1] ? arg[1][1] : 0;
  /* #197: @24 = input[1][2] */
  w24 = arg[1] ? arg[1][2] : 0;
  /* #198: @5 = input[1][3] */
  w5 = arg[1] ? arg[1][3] : 0;
  /* #199: @18 = vertcat(@3, @24, @5) */
  rr=w18;
  *rr++ = w3;
  *rr++ = w24;
  *rr++ = w5;
  /* #200: @3 = 0.01 */
  w3 = 1.0000000000000000e-02;
  /* #201: @29 = vertcat(@13, @14, @21) */
  rr=w29;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w21;
  /* #202: @29 = (@3*@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) (*rr++)  = (w3*(*cs++));
  /* #203: @18 = (@18-@29) */
  for (i=0, rr=w18, cs=w29; i<3; ++i) (*rr++) -= (*cs++);
  /* #204: @31 = 
  [[0.00250833, 0, 0], 
   [0, 0.00250833, 0], 
   [0, 0, 0.005]] */
  casadi_copy(casadi_c5, 9, w31);
  /* #205: @18 = (@31\@18) */
  rr = w18;
  ss = w31;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 1, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #206: output[0][7] = @18 */
  if (res[0]) casadi_copy(w18, 3, res[0]+17);
  /* #207: @3 = input[0][22] */
  w3 = arg[0] ? arg[0][22] : 0;
  /* #208: output[0][8] = @3 */
  if (res[0]) res[0][20] = w3;
  /* #209: @3 = input[0][23] */
  w3 = arg[0] ? arg[0][23] : 0;
  /* #210: output[0][9] = @3 */
  if (res[0]) res[0][21] = w3;
  /* #211: @3 = (@12*@23) */
  w3  = (w12*w23);
  /* #212: @12 = (@12*@19) */
  w12 *= w19;
  /* #213: @25 = (-@25) */
  w25 = (- w25 );
  /* #214: @18 = vertcat(@3, @12, @25) */
  rr=w18;
  *rr++ = w3;
  *rr++ = w12;
  *rr++ = w25;
  /* #215: @3 = mac(@17,@18,@6) */
  casadi_copy((&w6), 1, (&w3));
  for (i=0, rr=(&w3); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #216: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #217: output[0][10] = @3 */
  if (res[0]) res[0][22] = w3;
  /* #218: @19 = (-@19) */
  w19 = (- w19 );
  /* #219: @18 = vertcat(@19, @23, @6) */
  rr=w18;
  *rr++ = w19;
  *rr++ = w23;
  *rr++ = w6;
  /* #220: @6 = mac(@17,@18,@6) */
  for (i=0, rr=(&w6); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #221: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #222: output[0][11] = @6 */
  if (res[0]) res[0][23] = w6;
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_accel_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int payload_accel_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_accel_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void payload_accel_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int payload_accel_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void payload_accel_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void payload_accel_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void payload_accel_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int payload_accel_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int payload_accel_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real payload_accel_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* payload_accel_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* payload_accel_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* payload_accel_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* payload_accel_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int payload_accel_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 67;
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_accel_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 67*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
