/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) payload_nav_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[3] = {0, 0, 0};
static const casadi_int casadi_s4[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s5[25] = {28, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3};
static const casadi_int casadi_s6[3] = {11, 0, 0};

/* payload_nav_cost_y_0_fun_jac_ut_xt:(i0[24],i1[4],i2[0],i3[],i4[0])->(o0[11],o1[28x11,11nz],o2[11x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, *w24=w+24, *w25=w+48, *w26=w+51, *w27=w+55, *w28=w+66, w29, w30, w31, w32, *w33=w+98;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = input[0][4] */
  w4 = arg[0] ? arg[0][4] : 0;
  /* #5: @5 = input[0][5] */
  w5 = arg[0] ? arg[0][5] : 0;
  /* #6: @6 = input[0][6] */
  w6 = arg[0] ? arg[0][6] : 0;
  /* #7: @7 = input[0][7] */
  w7 = arg[0] ? arg[0][7] : 0;
  /* #8: @8 = input[0][8] */
  w8 = arg[0] ? arg[0][8] : 0;
  /* #9: @9 = input[0][9] */
  w9 = arg[0] ? arg[0][9] : 0;
  /* #10: @10 = input[0][10] */
  w10 = arg[0] ? arg[0][10] : 0;
  /* #11: @11 = input[0][11] */
  w11 = arg[0] ? arg[0][11] : 0;
  /* #12: @12 = input[0][12] */
  w12 = arg[0] ? arg[0][12] : 0;
  /* #13: @13 = input[0][13] */
  w13 = arg[0] ? arg[0][13] : 0;
  /* #14: @14 = input[0][14] */
  w14 = arg[0] ? arg[0][14] : 0;
  /* #15: @15 = input[0][15] */
  w15 = arg[0] ? arg[0][15] : 0;
  /* #16: @16 = input[0][16] */
  w16 = arg[0] ? arg[0][16] : 0;
  /* #17: @17 = input[0][17] */
  w17 = arg[0] ? arg[0][17] : 0;
  /* #18: @18 = input[0][18] */
  w18 = arg[0] ? arg[0][18] : 0;
  /* #19: @19 = input[0][19] */
  w19 = arg[0] ? arg[0][19] : 0;
  /* #20: @20 = input[0][20] */
  w20 = arg[0] ? arg[0][20] : 0;
  /* #21: @21 = input[0][21] */
  w21 = arg[0] ? arg[0][21] : 0;
  /* #22: @22 = input[0][22] */
  w22 = arg[0] ? arg[0][22] : 0;
  /* #23: @23 = input[0][23] */
  w23 = arg[0] ? arg[0][23] : 0;
  /* #24: @24 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23) */
  rr=w24;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  /* #25: @25 = @24[:3] */
  for (rr=w25, ss=w24+0; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #26: output[0][0] = @25 */
  casadi_copy(w25, 3, res[0]);
  /* #27: @26 = @24[3:7] */
  for (rr=w26, ss=w24+3; ss!=w24+7; ss+=1) *rr++ = *ss;
  /* #28: output[0][1] = @26 */
  if (res[0]) casadi_copy(w26, 4, res[0]+3);
  /* #29: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #30: output[0][2] = @0 */
  if (res[0]) res[0][7] = w0;
  /* #31: @0 = input[1][1] */
  w0 = arg[1] ? arg[1][1] : 0;
  /* #32: output[0][3] = @0 */
  if (res[0]) res[0][8] = w0;
  /* #33: @0 = input[1][2] */
  w0 = arg[1] ? arg[1][2] : 0;
  /* #34: output[0][4] = @0 */
  if (res[0]) res[0][9] = w0;
  /* #35: @0 = input[1][3] */
  w0 = arg[1] ? arg[1][3] : 0;
  /* #36: output[0][5] = @0 */
  if (res[0]) res[0][10] = w0;
  /* #37: @27 = zeros(28x11,11nz) */
  casadi_clear(w27, 11);
  /* #38: @28 = ones(28x1) */
  casadi_fill(w28, 28, 1.);
  /* #39: {@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @29, @30, @31, @32} = vertsplit(@28) */
  w0 = w28[0];
  w1 = w28[1];
  w2 = w28[2];
  w3 = w28[3];
  w4 = w28[4];
  w5 = w28[5];
  w6 = w28[6];
  w7 = w28[7];
  w8 = w28[8];
  w9 = w28[9];
  w10 = w28[10];
  w11 = w28[11];
  w12 = w28[12];
  w13 = w28[13];
  w14 = w28[14];
  w15 = w28[15];
  w16 = w28[16];
  w17 = w28[17];
  w18 = w28[18];
  w19 = w28[19];
  w20 = w28[20];
  w21 = w28[21];
  w22 = w28[22];
  w23 = w28[23];
  w29 = w28[24];
  w30 = w28[25];
  w31 = w28[26];
  w32 = w28[27];
  /* #40: @24 = vertcat(@4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @29, @30, @31, @32) */
  rr=w24;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  /* #41: @25 = @24[:3] */
  for (rr=w25, ss=w24+0; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #42: @26 = @24[3:7] */
  for (rr=w26, ss=w24+3; ss!=w24+7; ss+=1) *rr++ = *ss;
  /* #43: @33 = vertcat(@25, @26, @0, @1, @2, @3) */
  rr=w33;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<4; ++i) *rr++ = *cs++;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  /* #44: (@27[:11] = @33) */
  for (rr=w27+0, ss=w33; rr!=w27+11; rr+=1) *rr = *ss++;
  /* #45: output[1][0] = @27 */
  casadi_copy(w27, 11, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_nav_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int payload_nav_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_nav_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void payload_nav_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int payload_nav_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void payload_nav_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void payload_nav_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void payload_nav_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int payload_nav_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int payload_nav_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real payload_nav_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* payload_nav_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* payload_nav_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* payload_nav_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* payload_nav_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int payload_nav_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 29;
  if (sz_res) *sz_res = 31;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 109;
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_nav_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 29*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 31*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 109*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
