/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) payload_accel_cost_y_0_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[6] = {6, 12, 19, 26, 33, 40};
static const casadi_int casadi_s1[12] = {3, 3, 0, 2, 4, 6, 1, 2, 0, 2, 0, 1};
static const casadi_int casadi_s2[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s3[6] = {0, 13, 20, 27, 34, 41};
static const casadi_int casadi_s4[14] = {3, 3, 0, 2, 5, 8, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s5[7] = {1, 7, 14, 21, 28, 35, 42};
static const casadi_int casadi_s6[14] = {3, 3, 0, 3, 5, 8, 0, 1, 2, 0, 2, 0, 1, 2};
static const casadi_int casadi_s7[7] = {2, 8, 15, 22, 29, 36, 43};
static const casadi_int casadi_s8[14] = {3, 3, 0, 3, 6, 8, 0, 1, 2, 0, 1, 2, 0, 1};
static const casadi_int casadi_s9[7] = {3, 9, 16, 23, 30, 37, 44};
static const casadi_int casadi_s10[7] = {4, 10, 17, 24, 31, 38, 45};
static const casadi_int casadi_s11[6] = {3, 1, 0, 2, 0, 1};
static const casadi_int casadi_s12[8] = {1, 3, 0, 1, 2, 2, 0, 0};
static const casadi_int casadi_s13[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s14[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s15[7] = {5, 11, 18, 25, 32, 39, 46};
static const casadi_int casadi_s16[78] = {28, 28, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 12, 19, 26, 33, 33, 33, 33, 40, 47, 47, 47, 17, 18, 19, 20, 24, 25, 0, 18, 19, 20, 24, 25, 0, 17, 18, 19, 20, 24, 25, 0, 17, 18, 19, 20, 24, 25, 0, 17, 18, 19, 20, 24, 25, 0, 17, 18, 19, 20, 24, 25, 0, 17, 18, 19, 20, 24, 25};
static const casadi_int casadi_s17[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s18[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s19[4] = {0, 1, 0, 0};
static const casadi_int casadi_s20[3] = {0, 0, 0};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[3] = {0., 0., -2.4516624999999999e+00};

/* payload_accel_cost_y_0_hess:(i0[24],i1[4],i2[0],i3[3],i4[],i5[0])->(o0[28x28,47nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+3, w2, *w3=w+51, w4, w5, w6, w7, w8, w9, *w10=w+66, *w11=w+69, *w12=w+72, *w13=w+75, *w14=w+78, *w15=w+100, *w16=w+103, *w17=w+106, *w18=w+109, *w19=w+118, *w20=w+127, *w21=w+130, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35, w36, w37, w38, w39, w40, w41, w42, *w43=w+154, *w44=w+157, *w45=w+163, *w46=w+169, *w47=w+171, *w48=w+173, *w49=w+175, *w50=w+178, w51, w52, w53, *w54=w+184, *w55=w+192, w56, *w57=w+201, *w58=w+208, *w59=w+215;
  /* #0: @0 = zeros(28x28,47nz) */
  casadi_clear(w0, 47);
  /* #1: @1 = 00 */
  /* #2: @2 = input[0][14] */
  w2 = arg[0] ? arg[0][14] : 0;
  /* #3: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #4: @4 = input[0][20] */
  w4 = arg[0] ? arg[0][20] : 0;
  /* #5: @5 = sin(@4) */
  w5 = sin( w4 );
  /* #6: @6 = input[0][21] */
  w6 = arg[0] ? arg[0][21] : 0;
  /* #7: @7 = cos(@6) */
  w7 = cos( w6 );
  /* #8: @8 = (@5*@7) */
  w8  = (w5*w7);
  /* #9: @6 = sin(@6) */
  w6 = sin( w6 );
  /* #10: @9 = (@5*@6) */
  w9  = (w5*w6);
  /* #11: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #12: @10 = vertcat(@8, @9, @4) */
  rr=w10;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w4;
  /* #13: @8 = 0.5 */
  w8 = 5.0000000000000000e-01;
  /* #14: @11 = input[3][0] */
  casadi_copy(arg[3], 3, w11);
  /* #15: @11 = (@8*@11) */
  for (i=0, rr=w11, cs=w11; i<3; ++i) (*rr++)  = (w8*(*cs++));
  /* #16: @8 = dot(@10, @11) */
  w8 = casadi_dot(3, w10, w11);
  /* #17: @12 = @10' */
  casadi_copy(w10, 3, w12);
  /* #18: @13 = (@8*@12) */
  for (i=0, rr=w13, cs=w12; i<3; ++i) (*rr++)  = (w8*(*cs++));
  /* #19: @13 = @13' */
  /* #20: @14 = ones(28x1,22nz) */
  casadi_fill(w14, 22, 1.);
  /* #21: {@9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@14) */
  w9 = w14[0];
  /* #22: @15 = (@13*@9) */
  for (i=0, rr=w15, cr=w13; i<3; ++i) (*rr++)  = ((*cr++)*w9);
  /* #23: @16 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w16);
  /* #24: @17 = @16' */
  casadi_copy(w16, 3, w17);
  /* #25: @18 = mac(@15,@17,@3) */
  casadi_copy(w3, 9, w18);
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w17+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #26: @19 = @18' */
  for (i=0, rr=w19, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #27: {@15, @20, @21} = horzsplit(@19) */
  casadi_copy(w19, 3, w15);
  casadi_copy(w19+3, 3, w20);
  casadi_copy(w19+6, 3, w21);
  /* #28: @21 = @21' */
  /* #29: {@22, @23, @24} = horzsplit(@21) */
  w22 = w21[0];
  w23 = w21[1];
  w24 = w21[2];
  /* #30: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #31: @25 = (@2*@23) */
  w25  = (w2*w23);
  /* #32: @26 = input[0][15] */
  w26 = arg[0] ? arg[0][15] : 0;
  /* #33: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #34: @27 = (@26*@22) */
  w27  = (w26*w22);
  /* #35: @25 = (@25-@27) */
  w25 -= w27;
  /* #36: @20 = @20' */
  /* #37: {@27, @28, @29} = horzsplit(@20) */
  w27 = w20[0];
  w28 = w20[1];
  w29 = w20[2];
  /* #38: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #39: @30 = (@2*@29) */
  w30  = (w2*w29);
  /* #40: @25 = (@25-@30) */
  w25 -= w30;
  /* #41: @30 = input[0][16] */
  w30 = arg[0] ? arg[0][16] : 0;
  /* #42: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #43: @31 = (@30*@27) */
  w31  = (w30*w27);
  /* #44: @25 = (@25+@31) */
  w25 += w31;
  /* #45: @15 = @15' */
  /* #46: {@31, @32, @33} = horzsplit(@15) */
  w31 = w15[0];
  w32 = w15[1];
  w33 = w15[2];
  /* #47: @33 = (2.*@33) */
  w33 = (2.* w33 );
  /* #48: @34 = (@26*@33) */
  w34  = (w26*w33);
  /* #49: @25 = (@25+@34) */
  w25 += w34;
  /* #50: @32 = (2.*@32) */
  w32 = (2.* w32 );
  /* #51: @34 = (@30*@32) */
  w34  = (w30*w32);
  /* #52: @25 = (@25-@34) */
  w25 -= w34;
  /* #53: @34 = (2.*@2) */
  w34 = (2.* w2 );
  /* #54: @24 = (-@24) */
  w24 = (- w24 );
  /* #55: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #56: @35 = (@34*@24) */
  w35  = (w34*w24);
  /* #57: @36 = input[0][13] */
  w36 = arg[0] ? arg[0][13] : 0;
  /* #58: @37 = (@36*@23) */
  w37  = (w36*w23);
  /* #59: @35 = (@35+@37) */
  w35 += w37;
  /* #60: @37 = (@30*@22) */
  w37  = (w30*w22);
  /* #61: @35 = (@35+@37) */
  w35 += w37;
  /* #62: @37 = (@36*@29) */
  w37  = (w36*w29);
  /* #63: @35 = (@35-@37) */
  w35 -= w37;
  /* #64: @28 = (-@28) */
  w28 = (- w28 );
  /* #65: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #66: @37 = (@34*@28) */
  w37  = (w34*w28);
  /* #67: @35 = (@35+@37) */
  w35 += w37;
  /* #68: @37 = (@26*@27) */
  w37  = (w26*w27);
  /* #69: @35 = (@35+@37) */
  w35 += w37;
  /* #70: @37 = (@30*@33) */
  w37  = (w30*w33);
  /* #71: @35 = (@35+@37) */
  w35 += w37;
  /* #72: @37 = (@26*@32) */
  w37  = (w26*w32);
  /* #73: @35 = (@35+@37) */
  w35 += w37;
  /* #74: @37 = (2.*@26) */
  w37 = (2.* w26 );
  /* #75: @24 = (@37*@24) */
  w24  = (w37*w24);
  /* #76: @38 = (@30*@23) */
  w38  = (w30*w23);
  /* #77: @24 = (@24+@38) */
  w24 += w38;
  /* #78: @38 = (@36*@22) */
  w38  = (w36*w22);
  /* #79: @24 = (@24-@38) */
  w24 -= w38;
  /* #80: @38 = (@30*@29) */
  w38  = (w30*w29);
  /* #81: @24 = (@24+@38) */
  w24 += w38;
  /* #82: @38 = (@2*@27) */
  w38  = (w2*w27);
  /* #83: @24 = (@24+@38) */
  w24 += w38;
  /* #84: @38 = (@36*@33) */
  w38  = (w36*w33);
  /* #85: @24 = (@24+@38) */
  w24 += w38;
  /* #86: @38 = (@2*@32) */
  w38  = (w2*w32);
  /* #87: @24 = (@24+@38) */
  w24 += w38;
  /* #88: @31 = (-@31) */
  w31 = (- w31 );
  /* #89: @31 = (2.*@31) */
  w31 = (2.* w31 );
  /* #90: @38 = (@37*@31) */
  w38  = (w37*w31);
  /* #91: @24 = (@24+@38) */
  w24 += w38;
  /* #92: @23 = (@26*@23) */
  w23  = (w26*w23);
  /* #93: @22 = (@2*@22) */
  w22  = (w2*w22);
  /* #94: @23 = (@23+@22) */
  w23 += w22;
  /* #95: @29 = (@26*@29) */
  w29  = (w26*w29);
  /* #96: @23 = (@23+@29) */
  w23 += w29;
  /* #97: @29 = (2.*@30) */
  w29 = (2.* w30 );
  /* #98: @28 = (@29*@28) */
  w28  = (w29*w28);
  /* #99: @23 = (@23+@28) */
  w23 += w28;
  /* #100: @27 = (@36*@27) */
  w27  = (w36*w27);
  /* #101: @23 = (@23+@27) */
  w23 += w27;
  /* #102: @33 = (@2*@33) */
  w33  = (w2*w33);
  /* #103: @23 = (@23+@33) */
  w23 += w33;
  /* #104: @32 = (@36*@32) */
  w32  = (w36*w32);
  /* #105: @23 = (@23-@32) */
  w23 -= w32;
  /* #106: @31 = (@29*@31) */
  w31  = (w29*w31);
  /* #107: @23 = (@23+@31) */
  w23 += w31;
  /* #108: @31 = 0 */
  w31 = 0.;
  /* #109: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #110: @32 = 1 */
  w32 = 1.;
  /* #111: @33 = sq(@26) */
  w33 = casadi_sq( w26 );
  /* #112: @27 = sq(@30) */
  w27 = casadi_sq( w30 );
  /* #113: @28 = (@33+@27) */
  w28  = (w33+w27);
  /* #114: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #115: @28 = (@32-@28) */
  w28  = (w32-w28);
  /* #116: @22 = (@2*@26) */
  w22  = (w2*w26);
  /* #117: @38 = (@30*@36) */
  w38  = (w30*w36);
  /* #118: @39 = (@22-@38) */
  w39  = (w22-w38);
  /* #119: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #120: @40 = (@2*@30) */
  w40  = (w2*w30);
  /* #121: @41 = (@26*@36) */
  w41  = (w26*w36);
  /* #122: @42 = (@40+@41) */
  w42  = (w40+w41);
  /* #123: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #124: @20 = horzcat(@28, @39, @42) */
  rr=w20;
  *rr++ = w28;
  *rr++ = w39;
  *rr++ = w42;
  /* #125: @20 = @20' */
  /* #126: @22 = (@22+@38) */
  w22 += w38;
  /* #127: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #128: @38 = sq(@2) */
  w38 = casadi_sq( w2 );
  /* #129: @27 = (@38+@27) */
  w27  = (w38+w27);
  /* #130: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #131: @27 = (@32-@27) */
  w27  = (w32-w27);
  /* #132: @28 = (@26*@30) */
  w28  = (w26*w30);
  /* #133: @39 = (@2*@36) */
  w39  = (w2*w36);
  /* #134: @42 = (@28-@39) */
  w42  = (w28-w39);
  /* #135: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #136: @21 = horzcat(@22, @27, @42) */
  rr=w21;
  *rr++ = w22;
  *rr++ = w27;
  *rr++ = w42;
  /* #137: @21 = @21' */
  /* #138: @40 = (@40-@41) */
  w40 -= w41;
  /* #139: @40 = (2.*@40) */
  w40 = (2.* w40 );
  /* #140: @28 = (@28+@39) */
  w28 += w39;
  /* #141: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #142: @38 = (@38+@33) */
  w38 += w33;
  /* #143: @38 = (2.*@38) */
  w38 = (2.* w38 );
  /* #144: @32 = (@32-@38) */
  w32 -= w38;
  /* #145: @43 = horzcat(@40, @28, @32) */
  rr=w43;
  *rr++ = w40;
  *rr++ = w28;
  *rr++ = w32;
  /* #146: @43 = @43' */
  /* #147: @19 = horzcat(@20, @21, @43) */
  rr=w19;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<3; ++i) *rr++ = *cs++;
  /* #148: @18 = @19' */
  for (i=0, rr=w18, cs=w19; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #149: @20 = mac(@18,@16,@15) */
  casadi_copy(w15, 3, w20);
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w16+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #150: @21 = (@20*@9) */
  for (i=0, rr=w21, cr=w20; i<3; ++i) (*rr++)  = ((*cr++)*w9);
  /* #151: @43 = @21' */
  casadi_copy(w21, 3, w43);
  /* #152: @9 = mac(@43,@10,@31) */
  casadi_copy((&w31), 1, (&w9));
  for (i=0, rr=(&w9); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w43+j, tt=w10+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #153: @43 = (@11*@9) */
  for (i=0, rr=w43, cr=w11; i<3; ++i) (*rr++)  = ((*cr++)*w9);
  /* #154: @21 = (@8*@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) (*rr++)  = (w8*(*cs++));
  /* #155: @43 = (@43+@21) */
  for (i=0, rr=w43, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #156: {@9, @40, @28} = vertsplit(@43) */
  w9 = w43[0];
  w40 = w43[1];
  w28 = w43[2];
  /* #157: @32 = (@6*@40) */
  w32  = (w6*w40);
  /* #158: @32 = (@4*@32) */
  w32  = (w4*w32);
  /* #159: @28 = (@5*@28) */
  w28  = (w5*w28);
  /* #160: @32 = (@32-@28) */
  w32 -= w28;
  /* #161: @28 = (@7*@9) */
  w28  = (w7*w9);
  /* #162: @28 = (@4*@28) */
  w28  = (w4*w28);
  /* #163: @32 = (@32+@28) */
  w32 += w28;
  /* #164: @40 = (@5*@40) */
  w40  = (w5*w40);
  /* #165: @40 = (@7*@40) */
  w40  = (w7*w40);
  /* #166: @9 = (@5*@9) */
  w9  = (w5*w9);
  /* #167: @9 = (@6*@9) */
  w9  = (w6*w9);
  /* #168: @40 = (@40-@9) */
  w40 -= w9;
  /* #169: @44 = vertcat(@1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @25, @35, @24, @23, @1, @1, @1, @32, @40, @1, @1) */
  rr=w44;
  *rr++ = w25;
  *rr++ = w35;
  *rr++ = w24;
  *rr++ = w23;
  *rr++ = w32;
  *rr++ = w40;
  /* #170: @45 = @44[:6] */
  for (rr=w45, ss=w44+0; ss!=w44+6; ss+=1) *rr++ = *ss;
  /* #171: (@0[6, 12, 19, 26, 33, 40] = @45) */
  for (cii=casadi_s0, rr=w0, ss=w45; cii!=casadi_s0+6; ++cii, ++ss) rr[*cii] = *ss;
  /* #172: @25 = ones(28x1,1nz) */
  w25 = 1.;
  /* #173: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @35, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@25) */
  w35 = w25;
  /* #174: @25 = (@30*@35) */
  w25  = (w30*w35);
  /* #175: @24 = (-@25) */
  w24 = (- w25 );
  /* #176: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #177: @23 = (@26*@35) */
  w23  = (w26*w35);
  /* #178: @32 = (2.*@23) */
  w32 = (2.* w23 );
  /* #179: @46 = horzcat(@1, @24, @32) */
  rr=w46;
  *rr++ = w24;
  *rr++ = w32;
  /* #180: @46 = @46' */
  /* #181: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #182: @24 = (@2*@35) */
  w24  = (w2*w35);
  /* #183: @32 = (-@24) */
  w32 = (- w24 );
  /* #184: @32 = (2.*@32) */
  w32 = (2.* w32 );
  /* #185: @47 = horzcat(@25, @1, @32) */
  rr=w47;
  *rr++ = w25;
  *rr++ = w32;
  /* #186: @47 = @47' */
  /* #187: @23 = (-@23) */
  w23 = (- w23 );
  /* #188: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #189: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #190: @48 = horzcat(@23, @24, @1) */
  rr=w48;
  *rr++ = w23;
  *rr++ = w24;
  /* #191: @48 = @48' */
  /* #192: @45 = horzcat(@46, @47, @48) */
  rr=w45;
  for (i=0, cs=w46; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w47; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w48; i<2; ++i) *rr++ = *cs++;
  /* #193: @44 = @45' */
  casadi_trans(w45,casadi_s1, w44, casadi_s1, iw);
  /* #194: @43 = mac(@44,@16,@15) */
  casadi_copy(w15, 3, w43);
  casadi_mtimes(w44, casadi_s1, w16, casadi_s2, w43, casadi_s2, w, 0);
  /* #195: @23 = dot(@43, @13) */
  w23 = casadi_dot(3, w43, w13);
  /* #196: @24 = input[1][0] */
  w24 = arg[1] ? arg[1][0] : 0;
  /* #197: @21 = (@24*@13) */
  for (i=0, rr=w21, cs=w13; i<3; ++i) (*rr++)  = (w24*(*cs++));
  /* #198: @18 = mac(@21,@17,@3) */
  casadi_copy(w3, 9, w18);
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w17+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #199: @19 = @18' */
  for (i=0, rr=w19, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #200: {@21, @49, @50} = horzsplit(@19) */
  casadi_copy(w19, 3, w21);
  casadi_copy(w19+3, 3, w49);
  casadi_copy(w19+6, 3, w50);
  /* #201: @50 = @50' */
  /* #202: {@25, @32, @40} = horzsplit(@50) */
  w25 = w50[0];
  w32 = w50[1];
  w40 = w50[2];
  /* #203: @32 = (2.*@32) */
  w32 = (2.* w32 );
  /* #204: @9 = (@32*@35) */
  w9  = (w32*w35);
  /* #205: @49 = @49' */
  /* #206: {@28, @38, @33} = horzsplit(@49) */
  w28 = w49[0];
  w38 = w49[1];
  w33 = w49[2];
  /* #207: @33 = (2.*@33) */
  w33 = (2.* w33 );
  /* #208: @39 = (@33*@35) */
  w39  = (w33*w35);
  /* #209: @9 = (@9-@39) */
  w9 -= w39;
  /* #210: @21 = @21' */
  /* #211: {@39, @41, @22} = horzsplit(@21) */
  w39 = w21[0];
  w41 = w21[1];
  w22 = w21[2];
  /* #212: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #213: @27 = (@22*@35) */
  w27  = (w22*w35);
  /* #214: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #215: @42 = (@25*@35) */
  w42  = (w25*w35);
  /* #216: @27 = (@27-@42) */
  w27 -= w42;
  /* #217: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #218: @42 = (@28*@35) */
  w42  = (w28*w35);
  /* #219: @41 = (2.*@41) */
  w41 = (2.* w41 );
  /* #220: @35 = (@41*@35) */
  w35  = (w41*w35);
  /* #221: @42 = (@42-@35) */
  w42 -= w35;
  /* #222: @43 = (@24*@43) */
  for (i=0, rr=w43, cs=w43; i<3; ++i) (*rr++)  = (w24*(*cs++));
  /* #223: @21 = @43' */
  casadi_copy(w43, 3, w21);
  /* #224: @35 = mac(@21,@10,@31) */
  casadi_copy((&w31), 1, (&w35));
  for (i=0, rr=(&w35); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w21+j, tt=w10+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #225: @21 = (@11*@35) */
  for (i=0, rr=w21, cr=w11; i<3; ++i) (*rr++)  = ((*cr++)*w35);
  /* #226: @43 = (@8*@43) */
  for (i=0, rr=w43, cs=w43; i<3; ++i) (*rr++)  = (w8*(*cs++));
  /* #227: @21 = (@21+@43) */
  for (i=0, rr=w21, cs=w43; i<3; ++i) (*rr++) += (*cs++);
  /* #228: {@35, @51, @52} = vertsplit(@21) */
  w35 = w21[0];
  w51 = w21[1];
  w52 = w21[2];
  /* #229: @53 = (@6*@51) */
  w53  = (w6*w51);
  /* #230: @53 = (@4*@53) */
  w53  = (w4*w53);
  /* #231: @52 = (@5*@52) */
  w52  = (w5*w52);
  /* #232: @53 = (@53-@52) */
  w53 -= w52;
  /* #233: @52 = (@7*@35) */
  w52  = (w7*w35);
  /* #234: @52 = (@4*@52) */
  w52  = (w4*w52);
  /* #235: @53 = (@53+@52) */
  w53 += w52;
  /* #236: @51 = (@5*@51) */
  w51  = (w5*w51);
  /* #237: @51 = (@7*@51) */
  w51  = (w7*w51);
  /* #238: @35 = (@5*@35) */
  w35  = (w5*w35);
  /* #239: @35 = (@6*@35) */
  w35  = (w6*w35);
  /* #240: @51 = (@51-@35) */
  w51 -= w35;
  /* #241: @44 = vertcat(@23, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @9, @27, @42, @1, @1, @1, @53, @51, @1, @1) */
  rr=w44;
  *rr++ = w23;
  *rr++ = w9;
  *rr++ = w27;
  *rr++ = w42;
  *rr++ = w53;
  *rr++ = w51;
  /* #242: @45 = @44[:6] */
  for (rr=w45, ss=w44+0; ss!=w44+6; ss+=1) *rr++ = *ss;
  /* #243: (@0[0, 13, 20, 27, 34, 41] = @45) */
  for (cii=casadi_s3, rr=w0, ss=w45; cii!=casadi_s3+6; ++cii, ++ss) rr[*cii] = *ss;
  /* #244: @23 = ones(28x1,1nz) */
  w23 = 1.;
  /* #245: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@23) */
  w9 = w23;
  /* #246: @23 = (@26*@9) */
  w23  = (w26*w9);
  /* #247: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #248: @27 = (@30*@9) */
  w27  = (w30*w9);
  /* #249: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #250: @46 = horzcat(@1, @23, @27) */
  rr=w46;
  *rr++ = w23;
  *rr++ = w27;
  /* #251: @46 = @46' */
  /* #252: @42 = (@34*@9) */
  w42  = (w34*w9);
  /* #253: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #254: @42 = (-@42) */
  w42 = (- w42 );
  /* #255: @53 = (@36*@9) */
  w53  = (w36*w9);
  /* #256: @51 = (-@53) */
  w51 = (- w53 );
  /* #257: @51 = (2.*@51) */
  w51 = (2.* w51 );
  /* #258: @21 = horzcat(@23, @42, @51) */
  rr=w21;
  *rr++ = w23;
  *rr++ = w42;
  *rr++ = w51;
  /* #259: @21 = @21' */
  /* #260: @53 = (2.*@53) */
  w53 = (2.* w53 );
  /* #261: @43 = horzcat(@27, @53, @42) */
  rr=w43;
  *rr++ = w27;
  *rr++ = w53;
  *rr++ = w42;
  /* #262: @43 = @43' */
  /* #263: @54 = horzcat(@46, @21, @43) */
  rr=w54;
  for (i=0, cs=w46; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<3; ++i) *rr++ = *cs++;
  /* #264: @55 = @54' */
  casadi_trans(w54,casadi_s4, w55, casadi_s4, iw);
  /* #265: @21 = mac(@55,@16,@15) */
  casadi_copy(w15, 3, w21);
  casadi_mtimes(w55, casadi_s4, w16, casadi_s2, w21, casadi_s2, w, 0);
  /* #266: @27 = dot(@21, @13) */
  w27 = casadi_dot(3, w21, w13);
  /* #267: @53 = (@32*@9) */
  w53  = (w32*w9);
  /* #268: @42 = (@33*@9) */
  w42  = (w33*w9);
  /* #269: @53 = (@53-@42) */
  w53 -= w42;
  /* #270: @40 = (-@40) */
  w40 = (- w40 );
  /* #271: @40 = (2.*@40) */
  w40 = (2.* w40 );
  /* #272: @42 = (2.*@9) */
  w42 = (2.* w9 );
  /* #273: @23 = (@40*@42) */
  w23  = (w40*w42);
  /* #274: @38 = (-@38) */
  w38 = (- w38 );
  /* #275: @38 = (2.*@38) */
  w38 = (2.* w38 );
  /* #276: @42 = (@38*@42) */
  w42  = (w38*w42);
  /* #277: @23 = (@23+@42) */
  w23 += w42;
  /* #278: @42 = (@28*@9) */
  w42  = (w28*w9);
  /* #279: @51 = (@41*@9) */
  w51  = (w41*w9);
  /* #280: @42 = (@42+@51) */
  w42 += w51;
  /* #281: @51 = (@25*@9) */
  w51  = (w25*w9);
  /* #282: @9 = (@22*@9) */
  w9  = (w22*w9);
  /* #283: @51 = (@51+@9) */
  w51 += w9;
  /* #284: @21 = (@24*@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) (*rr++)  = (w24*(*cs++));
  /* #285: @43 = @21' */
  casadi_copy(w21, 3, w43);
  /* #286: @9 = mac(@43,@10,@31) */
  casadi_copy((&w31), 1, (&w9));
  for (i=0, rr=(&w9); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w43+j, tt=w10+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #287: @43 = (@11*@9) */
  for (i=0, rr=w43, cr=w11; i<3; ++i) (*rr++)  = ((*cr++)*w9);
  /* #288: @21 = (@8*@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) (*rr++)  = (w8*(*cs++));
  /* #289: @43 = (@43+@21) */
  for (i=0, rr=w43, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #290: {@9, @35, @52} = vertsplit(@43) */
  w9 = w43[0];
  w35 = w43[1];
  w52 = w43[2];
  /* #291: @56 = (@6*@35) */
  w56  = (w6*w35);
  /* #292: @56 = (@4*@56) */
  w56  = (w4*w56);
  /* #293: @52 = (@5*@52) */
  w52  = (w5*w52);
  /* #294: @56 = (@56-@52) */
  w56 -= w52;
  /* #295: @52 = (@7*@9) */
  w52  = (w7*w9);
  /* #296: @52 = (@4*@52) */
  w52  = (w4*w52);
  /* #297: @56 = (@56+@52) */
  w56 += w52;
  /* #298: @35 = (@5*@35) */
  w35  = (w5*w35);
  /* #299: @35 = (@7*@35) */
  w35  = (w7*w35);
  /* #300: @9 = (@5*@9) */
  w9  = (w5*w9);
  /* #301: @9 = (@6*@9) */
  w9  = (w6*w9);
  /* #302: @35 = (@35-@9) */
  w35 -= w9;
  /* #303: @57 = vertcat(@27, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @53, @23, @42, @51, @1, @1, @1, @56, @35, @1, @1) */
  rr=w57;
  *rr++ = w27;
  *rr++ = w53;
  *rr++ = w23;
  *rr++ = w42;
  *rr++ = w51;
  *rr++ = w56;
  *rr++ = w35;
  /* #304: @58 = @57[:7] */
  for (rr=w58, ss=w57+0; ss!=w57+7; ss+=1) *rr++ = *ss;
  /* #305: (@0[1, 7, 14, 21, 28, 35, 42] = @58) */
  for (cii=casadi_s5, rr=w0, ss=w58; cii!=casadi_s5+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #306: @27 = ones(28x1,1nz) */
  w27 = 1.;
  /* #307: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @53, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@27) */
  w53 = w27;
  /* #308: @27 = (@37*@53) */
  w27  = (w37*w53);
  /* #309: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #310: @27 = (-@27) */
  w27 = (- w27 );
  /* #311: @23 = (@2*@53) */
  w23  = (w2*w53);
  /* #312: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #313: @42 = (@36*@53) */
  w42  = (w36*w53);
  /* #314: @51 = (2.*@42) */
  w51 = (2.* w42 );
  /* #315: @43 = horzcat(@27, @23, @51) */
  rr=w43;
  *rr++ = w27;
  *rr++ = w23;
  *rr++ = w51;
  /* #316: @43 = @43' */
  /* #317: @51 = (@30*@53) */
  w51  = (w30*w53);
  /* #318: @51 = (2.*@51) */
  w51 = (2.* w51 );
  /* #319: @46 = horzcat(@23, @1, @51) */
  rr=w46;
  *rr++ = w23;
  *rr++ = w51;
  /* #320: @46 = @46' */
  /* #321: @42 = (-@42) */
  w42 = (- w42 );
  /* #322: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #323: @21 = horzcat(@42, @51, @27) */
  rr=w21;
  *rr++ = w42;
  *rr++ = w51;
  *rr++ = w27;
  /* #324: @21 = @21' */
  /* #325: @55 = horzcat(@43, @46, @21) */
  rr=w55;
  for (i=0, cs=w43; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  /* #326: @54 = @55' */
  casadi_trans(w55,casadi_s6, w54, casadi_s6, iw);
  /* #327: @43 = mac(@54,@16,@15) */
  casadi_copy(w15, 3, w43);
  casadi_mtimes(w54, casadi_s6, w16, casadi_s2, w43, casadi_s2, w, 0);
  /* #328: @42 = dot(@43, @13) */
  w42 = casadi_dot(3, w43, w13);
  /* #329: @51 = (@22*@53) */
  w51  = (w22*w53);
  /* #330: @27 = (@25*@53) */
  w27  = (w25*w53);
  /* #331: @51 = (@51-@27) */
  w51 -= w27;
  /* #332: @27 = (@28*@53) */
  w27  = (w28*w53);
  /* #333: @23 = (@41*@53) */
  w23  = (w41*w53);
  /* #334: @27 = (@27+@23) */
  w27 += w23;
  /* #335: @23 = (2.*@53) */
  w23 = (2.* w53 );
  /* #336: @40 = (@40*@23) */
  w40 *= w23;
  /* #337: @39 = (-@39) */
  w39 = (- w39 );
  /* #338: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #339: @23 = (@39*@23) */
  w23  = (w39*w23);
  /* #340: @40 = (@40+@23) */
  w40 += w23;
  /* #341: @23 = (@32*@53) */
  w23  = (w32*w53);
  /* #342: @53 = (@33*@53) */
  w53  = (w33*w53);
  /* #343: @23 = (@23+@53) */
  w23 += w53;
  /* #344: @43 = (@24*@43) */
  for (i=0, rr=w43, cs=w43; i<3; ++i) (*rr++)  = (w24*(*cs++));
  /* #345: @21 = @43' */
  casadi_copy(w43, 3, w21);
  /* #346: @53 = mac(@21,@10,@31) */
  casadi_copy((&w31), 1, (&w53));
  for (i=0, rr=(&w53); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w21+j, tt=w10+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #347: @21 = (@11*@53) */
  for (i=0, rr=w21, cr=w11; i<3; ++i) (*rr++)  = ((*cr++)*w53);
  /* #348: @43 = (@8*@43) */
  for (i=0, rr=w43, cs=w43; i<3; ++i) (*rr++)  = (w8*(*cs++));
  /* #349: @21 = (@21+@43) */
  for (i=0, rr=w21, cs=w43; i<3; ++i) (*rr++) += (*cs++);
  /* #350: {@53, @56, @35} = vertsplit(@21) */
  w53 = w21[0];
  w56 = w21[1];
  w35 = w21[2];
  /* #351: @9 = (@6*@56) */
  w9  = (w6*w56);
  /* #352: @9 = (@4*@9) */
  w9  = (w4*w9);
  /* #353: @35 = (@5*@35) */
  w35  = (w5*w35);
  /* #354: @9 = (@9-@35) */
  w9 -= w35;
  /* #355: @35 = (@7*@53) */
  w35  = (w7*w53);
  /* #356: @35 = (@4*@35) */
  w35  = (w4*w35);
  /* #357: @9 = (@9+@35) */
  w9 += w35;
  /* #358: @56 = (@5*@56) */
  w56  = (w5*w56);
  /* #359: @56 = (@7*@56) */
  w56  = (w7*w56);
  /* #360: @53 = (@5*@53) */
  w53  = (w5*w53);
  /* #361: @53 = (@6*@53) */
  w53  = (w6*w53);
  /* #362: @56 = (@56-@53) */
  w56 -= w53;
  /* #363: @58 = vertcat(@42, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @51, @27, @40, @23, @1, @1, @1, @9, @56, @1, @1) */
  rr=w58;
  *rr++ = w42;
  *rr++ = w51;
  *rr++ = w27;
  *rr++ = w40;
  *rr++ = w23;
  *rr++ = w9;
  *rr++ = w56;
  /* #364: @57 = @58[:7] */
  for (rr=w57, ss=w58+0; ss!=w58+7; ss+=1) *rr++ = *ss;
  /* #365: (@0[2, 8, 15, 22, 29, 36, 43] = @57) */
  for (cii=casadi_s7, rr=w0, ss=w57; cii!=casadi_s7+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #366: @42 = ones(28x1,1nz) */
  w42 = 1.;
  /* #367: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @51, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@42) */
  w51 = w42;
  /* #368: @42 = (@29*@51) */
  w42  = (w29*w51);
  /* #369: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #370: @42 = (-@42) */
  w42 = (- w42 );
  /* #371: @27 = (@36*@51) */
  w27  = (w36*w51);
  /* #372: @40 = (-@27) */
  w40 = (- w27 );
  /* #373: @40 = (2.*@40) */
  w40 = (2.* w40 );
  /* #374: @23 = (@2*@51) */
  w23  = (w2*w51);
  /* #375: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #376: @21 = horzcat(@42, @40, @23) */
  rr=w21;
  *rr++ = w42;
  *rr++ = w40;
  *rr++ = w23;
  /* #377: @21 = @21' */
  /* #378: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #379: @40 = (@26*@51) */
  w40  = (w26*w51);
  /* #380: @40 = (2.*@40) */
  w40 = (2.* w40 );
  /* #381: @43 = horzcat(@27, @42, @40) */
  rr=w43;
  *rr++ = w27;
  *rr++ = w42;
  *rr++ = w40;
  /* #382: @43 = @43' */
  /* #383: @46 = horzcat(@23, @40, @1) */
  rr=w46;
  *rr++ = w23;
  *rr++ = w40;
  /* #384: @46 = @46' */
  /* #385: @54 = horzcat(@21, @43, @46) */
  rr=w54;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<2; ++i) *rr++ = *cs++;
  /* #386: @55 = @54' */
  casadi_trans(w54,casadi_s8, w55, casadi_s8, iw);
  /* #387: @15 = mac(@55,@16,@15) */
  casadi_mtimes(w55, casadi_s8, w16, casadi_s2, w15, casadi_s2, w, 0);
  /* #388: @23 = dot(@15, @13) */
  w23 = casadi_dot(3, w15, w13);
  /* #389: @28 = (@28*@51) */
  w28 *= w51;
  /* #390: @41 = (@41*@51) */
  w41 *= w51;
  /* #391: @28 = (@28-@41) */
  w28 -= w41;
  /* #392: @25 = (@25*@51) */
  w25 *= w51;
  /* #393: @22 = (@22*@51) */
  w22 *= w51;
  /* #394: @25 = (@25+@22) */
  w25 += w22;
  /* #395: @32 = (@32*@51) */
  w32 *= w51;
  /* #396: @33 = (@33*@51) */
  w33 *= w51;
  /* #397: @32 = (@32+@33) */
  w32 += w33;
  /* #398: @51 = (2.*@51) */
  w51 = (2.* w51 );
  /* #399: @38 = (@38*@51) */
  w38 *= w51;
  /* #400: @39 = (@39*@51) */
  w39 *= w51;
  /* #401: @38 = (@38+@39) */
  w38 += w39;
  /* #402: @15 = (@24*@15) */
  for (i=0, rr=w15, cs=w15; i<3; ++i) (*rr++)  = (w24*(*cs++));
  /* #403: @13 = @15' */
  casadi_copy(w15, 3, w13);
  /* #404: @39 = mac(@13,@10,@31) */
  casadi_copy((&w31), 1, (&w39));
  for (i=0, rr=(&w39); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w13+j, tt=w10+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #405: @13 = (@11*@39) */
  for (i=0, rr=w13, cr=w11; i<3; ++i) (*rr++)  = ((*cr++)*w39);
  /* #406: @15 = (@8*@15) */
  for (i=0, rr=w15, cs=w15; i<3; ++i) (*rr++)  = (w8*(*cs++));
  /* #407: @13 = (@13+@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) += (*cs++);
  /* #408: {@39, @51, @33} = vertsplit(@13) */
  w39 = w13[0];
  w51 = w13[1];
  w33 = w13[2];
  /* #409: @22 = (@6*@51) */
  w22  = (w6*w51);
  /* #410: @22 = (@4*@22) */
  w22  = (w4*w22);
  /* #411: @33 = (@5*@33) */
  w33  = (w5*w33);
  /* #412: @22 = (@22-@33) */
  w22 -= w33;
  /* #413: @33 = (@7*@39) */
  w33  = (w7*w39);
  /* #414: @33 = (@4*@33) */
  w33  = (w4*w33);
  /* #415: @22 = (@22+@33) */
  w22 += w33;
  /* #416: @51 = (@5*@51) */
  w51  = (w5*w51);
  /* #417: @51 = (@7*@51) */
  w51  = (w7*w51);
  /* #418: @39 = (@5*@39) */
  w39  = (w5*w39);
  /* #419: @39 = (@6*@39) */
  w39  = (w6*w39);
  /* #420: @51 = (@51-@39) */
  w51 -= w39;
  /* #421: @57 = vertcat(@23, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @28, @25, @32, @38, @1, @1, @1, @22, @51, @1, @1) */
  rr=w57;
  *rr++ = w23;
  *rr++ = w28;
  *rr++ = w25;
  *rr++ = w32;
  *rr++ = w38;
  *rr++ = w22;
  *rr++ = w51;
  /* #422: @58 = @57[:7] */
  for (rr=w58, ss=w57+0; ss!=w57+7; ss+=1) *rr++ = *ss;
  /* #423: (@0[3, 9, 16, 23, 30, 37, 44] = @58) */
  for (cii=casadi_s9, rr=w0, ss=w58; cii!=casadi_s9+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #424: @23 = ones(28x1,1nz) */
  w23 = 1.;
  /* #425: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @28, NULL, NULL, NULL} = vertsplit(@23) */
  w28 = w23;
  /* #426: @23 = (@4*@28) */
  w23  = (w4*w28);
  /* #427: @25 = (@7*@23) */
  w25  = (w7*w23);
  /* #428: @32 = (@6*@23) */
  w32  = (w6*w23);
  /* #429: @28 = (@5*@28) */
  w28  = (w5*w28);
  /* #430: @38 = (-@28) */
  w38 = (- w28 );
  /* #431: @13 = vertcat(@25, @32, @38) */
  rr=w13;
  *rr++ = w25;
  *rr++ = w32;
  *rr++ = w38;
  /* #432: @25 = dot(@13, @11) */
  w25 = casadi_dot(3, w13, w11);
  /* #433: @15 = (@12*@25) */
  for (i=0, rr=w15, cr=w12; i<3; ++i) (*rr++)  = ((*cr++)*w25);
  /* #434: @16 = @13' */
  casadi_copy(w13, 3, w16);
  /* #435: @16 = (@8*@16) */
  for (i=0, rr=w16, cs=w16; i<3; ++i) (*rr++)  = (w8*(*cs++));
  /* #436: @15 = (@15+@16) */
  for (i=0, rr=w15, cs=w16; i<3; ++i) (*rr++) += (*cs++);
  /* #437: @15 = @15' */
  /* #438: @32 = dot(@20, @15) */
  w32 = casadi_dot(3, w20, w15);
  /* #439: @15 = (@24*@15) */
  for (i=0, rr=w15, cs=w15; i<3; ++i) (*rr++)  = (w24*(*cs++));
  /* #440: @19 = mac(@15,@17,@3) */
  casadi_copy(w3, 9, w19);
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w17+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #441: @18 = @19' */
  for (i=0, rr=w18, cs=w19; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #442: {@15, @16, @21} = horzsplit(@18) */
  casadi_copy(w18, 3, w15);
  casadi_copy(w18+3, 3, w16);
  casadi_copy(w18+6, 3, w21);
  /* #443: @21 = @21' */
  /* #444: {@38, @22, @51} = horzsplit(@21) */
  w38 = w21[0];
  w22 = w21[1];
  w51 = w21[2];
  /* #445: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #446: @39 = (@2*@22) */
  w39  = (w2*w22);
  /* #447: @38 = (2.*@38) */
  w38 = (2.* w38 );
  /* #448: @33 = (@26*@38) */
  w33  = (w26*w38);
  /* #449: @39 = (@39-@33) */
  w39 -= w33;
  /* #450: @16 = @16' */
  /* #451: {@33, @41, @40} = horzsplit(@16) */
  w33 = w16[0];
  w41 = w16[1];
  w40 = w16[2];
  /* #452: @40 = (2.*@40) */
  w40 = (2.* w40 );
  /* #453: @27 = (@2*@40) */
  w27  = (w2*w40);
  /* #454: @39 = (@39-@27) */
  w39 -= w27;
  /* #455: @33 = (2.*@33) */
  w33 = (2.* w33 );
  /* #456: @27 = (@30*@33) */
  w27  = (w30*w33);
  /* #457: @39 = (@39+@27) */
  w39 += w27;
  /* #458: @15 = @15' */
  /* #459: {@27, @42, @9} = horzsplit(@15) */
  w27 = w15[0];
  w42 = w15[1];
  w9 = w15[2];
  /* #460: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #461: @56 = (@26*@9) */
  w56  = (w26*w9);
  /* #462: @39 = (@39+@56) */
  w39 += w56;
  /* #463: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #464: @56 = (@30*@42) */
  w56  = (w30*w42);
  /* #465: @39 = (@39-@56) */
  w39 -= w56;
  /* #466: @51 = (-@51) */
  w51 = (- w51 );
  /* #467: @51 = (2.*@51) */
  w51 = (2.* w51 );
  /* #468: @56 = (@34*@51) */
  w56  = (w34*w51);
  /* #469: @53 = (@36*@22) */
  w53  = (w36*w22);
  /* #470: @56 = (@56+@53) */
  w56 += w53;
  /* #471: @53 = (@30*@38) */
  w53  = (w30*w38);
  /* #472: @56 = (@56+@53) */
  w56 += w53;
  /* #473: @53 = (@36*@40) */
  w53  = (w36*w40);
  /* #474: @56 = (@56-@53) */
  w56 -= w53;
  /* #475: @41 = (-@41) */
  w41 = (- w41 );
  /* #476: @41 = (2.*@41) */
  w41 = (2.* w41 );
  /* #477: @53 = (@34*@41) */
  w53  = (w34*w41);
  /* #478: @56 = (@56+@53) */
  w56 += w53;
  /* #479: @53 = (@26*@33) */
  w53  = (w26*w33);
  /* #480: @56 = (@56+@53) */
  w56 += w53;
  /* #481: @53 = (@30*@9) */
  w53  = (w30*w9);
  /* #482: @56 = (@56+@53) */
  w56 += w53;
  /* #483: @53 = (@26*@42) */
  w53  = (w26*w42);
  /* #484: @56 = (@56+@53) */
  w56 += w53;
  /* #485: @51 = (@37*@51) */
  w51  = (w37*w51);
  /* #486: @53 = (@30*@22) */
  w53  = (w30*w22);
  /* #487: @51 = (@51+@53) */
  w51 += w53;
  /* #488: @53 = (@36*@38) */
  w53  = (w36*w38);
  /* #489: @51 = (@51-@53) */
  w51 -= w53;
  /* #490: @53 = (@30*@40) */
  w53  = (w30*w40);
  /* #491: @51 = (@51+@53) */
  w51 += w53;
  /* #492: @53 = (@2*@33) */
  w53  = (w2*w33);
  /* #493: @51 = (@51+@53) */
  w51 += w53;
  /* #494: @53 = (@36*@9) */
  w53  = (w36*w9);
  /* #495: @51 = (@51+@53) */
  w51 += w53;
  /* #496: @53 = (@2*@42) */
  w53  = (w2*w42);
  /* #497: @51 = (@51+@53) */
  w51 += w53;
  /* #498: @27 = (-@27) */
  w27 = (- w27 );
  /* #499: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #500: @53 = (@37*@27) */
  w53  = (w37*w27);
  /* #501: @51 = (@51+@53) */
  w51 += w53;
  /* #502: @22 = (@26*@22) */
  w22  = (w26*w22);
  /* #503: @38 = (@2*@38) */
  w38  = (w2*w38);
  /* #504: @22 = (@22+@38) */
  w22 += w38;
  /* #505: @40 = (@26*@40) */
  w40  = (w26*w40);
  /* #506: @22 = (@22+@40) */
  w22 += w40;
  /* #507: @41 = (@29*@41) */
  w41  = (w29*w41);
  /* #508: @22 = (@22+@41) */
  w22 += w41;
  /* #509: @33 = (@36*@33) */
  w33  = (w36*w33);
  /* #510: @22 = (@22+@33) */
  w22 += w33;
  /* #511: @9 = (@2*@9) */
  w9  = (w2*w9);
  /* #512: @22 = (@22+@9) */
  w22 += w9;
  /* #513: @42 = (@36*@42) */
  w42  = (w36*w42);
  /* #514: @22 = (@22-@42) */
  w22 -= w42;
  /* #515: @27 = (@29*@27) */
  w27  = (w29*w27);
  /* #516: @22 = (@22+@27) */
  w22 += w27;
  /* #517: @15 = [0, 0, -2.45166] */
  casadi_copy(casadi_c1, 3, w15);
  /* #518: @16 = (@24*@20) */
  for (i=0, rr=w16, cs=w20; i<3; ++i) (*rr++)  = (w24*(*cs++));
  /* #519: @15 = (@15+@16) */
  for (i=0, rr=w15, cs=w16; i<3; ++i) (*rr++) += (*cs++);
  /* #520: @16 = @15' */
  casadi_copy(w15, 3, w16);
  /* #521: @27 = mac(@16,@13,@31) */
  casadi_copy((&w31), 1, (&w27));
  for (i=0, rr=(&w27); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #522: @13 = (@11*@27) */
  for (i=0, rr=w13, cr=w11; i<3; ++i) (*rr++)  = ((*cr++)*w27);
  /* #523: @21 = (@15*@25) */
  for (i=0, rr=w21, cr=w15; i<3; ++i) (*rr++)  = ((*cr++)*w25);
  /* #524: @13 = (@13+@21) */
  for (i=0, rr=w13, cs=w21; i<3; ++i) (*rr++) += (*cs++);
  /* #525: {@25, @27, @42} = vertsplit(@13) */
  w25 = w13[0];
  w27 = w13[1];
  w42 = w13[2];
  /* #526: @9 = (@6*@27) */
  w9  = (w6*w27);
  /* #527: @9 = (@4*@9) */
  w9  = (w4*w9);
  /* #528: @33 = mac(@16,@10,@31) */
  casadi_copy((&w31), 1, (&w33));
  for (i=0, rr=(&w33); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w10+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #529: @10 = (@33*@11) */
  for (i=0, rr=w10, cs=w11; i<3; ++i) (*rr++)  = (w33*(*cs++));
  /* #530: @13 = (@15*@8) */
  for (i=0, rr=w13, cr=w15; i<3; ++i) (*rr++)  = ((*cr++)*w8);
  /* #531: @10 = (@10+@13) */
  for (i=0, rr=w10, cs=w13; i<3; ++i) (*rr++) += (*cs++);
  /* #532: {@33, @41, @40} = vertsplit(@10) */
  w33 = w10[0];
  w41 = w10[1];
  w40 = w10[2];
  /* #533: @38 = (@6*@41) */
  w38  = (w6*w41);
  /* #534: @38 = (@38*@28) */
  w38 *= w28;
  /* #535: @9 = (@9-@38) */
  w9 -= w38;
  /* #536: @40 = (@40*@23) */
  w40 *= w23;
  /* #537: @42 = (@5*@42) */
  w42  = (w5*w42);
  /* #538: @40 = (@40+@42) */
  w40 += w42;
  /* #539: @9 = (@9-@40) */
  w9 -= w40;
  /* #540: @40 = (@7*@25) */
  w40  = (w7*w25);
  /* #541: @40 = (@4*@40) */
  w40  = (w4*w40);
  /* #542: @42 = (@7*@33) */
  w42  = (w7*w33);
  /* #543: @42 = (@42*@28) */
  w42 *= w28;
  /* #544: @40 = (@40-@42) */
  w40 -= w42;
  /* #545: @9 = (@9+@40) */
  w9 += w40;
  /* #546: @40 = (@41*@23) */
  w40  = (w41*w23);
  /* #547: @27 = (@5*@27) */
  w27  = (w5*w27);
  /* #548: @40 = (@40+@27) */
  w40 += w27;
  /* #549: @40 = (@7*@40) */
  w40  = (w7*w40);
  /* #550: @23 = (@33*@23) */
  w23  = (w33*w23);
  /* #551: @25 = (@5*@25) */
  w25  = (w5*w25);
  /* #552: @23 = (@23+@25) */
  w23 += w25;
  /* #553: @23 = (@6*@23) */
  w23  = (w6*w23);
  /* #554: @40 = (@40-@23) */
  w40 -= w23;
  /* #555: @58 = vertcat(@32, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @39, @56, @51, @22, @1, @1, @1, @9, @40, @1, @1) */
  rr=w58;
  *rr++ = w32;
  *rr++ = w39;
  *rr++ = w56;
  *rr++ = w51;
  *rr++ = w22;
  *rr++ = w9;
  *rr++ = w40;
  /* #556: @57 = @58[:7] */
  for (rr=w57, ss=w58+0; ss!=w58+7; ss+=1) *rr++ = *ss;
  /* #557: (@0[4, 10, 17, 24, 31, 38, 45] = @57) */
  for (cii=casadi_s10, rr=w0, ss=w57; cii!=casadi_s10+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #558: @32 = ones(28x1,1nz) */
  w32 = 1.;
  /* #559: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @39, NULL, NULL} = vertsplit(@32) */
  w39 = w32;
  /* #560: @32 = (@6*@39) */
  w32  = (w6*w39);
  /* #561: @56 = (@5*@32) */
  w56  = (w5*w32);
  /* #562: @56 = (-@56) */
  w56 = (- w56 );
  /* #563: @39 = (@7*@39) */
  w39  = (w7*w39);
  /* #564: @51 = (@5*@39) */
  w51  = (w5*w39);
  /* #565: @46 = vertcat(@56, @51, @1) */
  rr=w46;
  *rr++ = w56;
  *rr++ = w51;
  /* #566: @47 = project(@11) */
  casadi_sparsify(w11, w47, casadi_s11, 0);
  /* #567: @56 = dot(@46, @47) */
  w56 = casadi_dot(2, w46, w47);
  /* #568: @12 = (@12*@56) */
  for (i=0, rr=w12; i<3; ++i) (*rr++) *= w56;
  /* #569: @47 = @46' */
  casadi_copy(w46, 2, w47);
  /* #570: @47 = (@8*@47) */
  for (i=0, rr=w47, cs=w47; i<2; ++i) (*rr++)  = (w8*(*cs++));
  /* #571: @10 = dense(@47) */
  casadi_densify(w47, casadi_s12, w10, 0);
  /* #572: @12 = (@12+@10) */
  for (i=0, rr=w12, cs=w10; i<3; ++i) (*rr++) += (*cs++);
  /* #573: @12 = @12' */
  /* #574: @8 = dot(@20, @12) */
  w8 = casadi_dot(3, w20, w12);
  /* #575: @12 = (@24*@12) */
  for (i=0, rr=w12, cs=w12; i<3; ++i) (*rr++)  = (w24*(*cs++));
  /* #576: @3 = mac(@12,@17,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w12+j, tt=w17+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #577: @18 = @3' */
  for (i=0, rr=w18, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #578: {@12, @17, @20} = horzsplit(@18) */
  casadi_copy(w18, 3, w12);
  casadi_copy(w18+3, 3, w17);
  casadi_copy(w18+6, 3, w20);
  /* #579: @20 = @20' */
  /* #580: {@24, @51, @22} = horzsplit(@20) */
  w24 = w20[0];
  w51 = w20[1];
  w22 = w20[2];
  /* #581: @51 = (2.*@51) */
  w51 = (2.* w51 );
  /* #582: @9 = (@2*@51) */
  w9  = (w2*w51);
  /* #583: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #584: @40 = (@26*@24) */
  w40  = (w26*w24);
  /* #585: @9 = (@9-@40) */
  w9 -= w40;
  /* #586: @17 = @17' */
  /* #587: {@40, @23, @25} = horzsplit(@17) */
  w40 = w17[0];
  w23 = w17[1];
  w25 = w17[2];
  /* #588: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #589: @27 = (@2*@25) */
  w27  = (w2*w25);
  /* #590: @9 = (@9-@27) */
  w9 -= w27;
  /* #591: @40 = (2.*@40) */
  w40 = (2.* w40 );
  /* #592: @27 = (@30*@40) */
  w27  = (w30*w40);
  /* #593: @9 = (@9+@27) */
  w9 += w27;
  /* #594: @12 = @12' */
  /* #595: {@27, @42, @28} = horzsplit(@12) */
  w27 = w12[0];
  w42 = w12[1];
  w28 = w12[2];
  /* #596: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #597: @38 = (@26*@28) */
  w38  = (w26*w28);
  /* #598: @9 = (@9+@38) */
  w9 += w38;
  /* #599: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #600: @38 = (@30*@42) */
  w38  = (w30*w42);
  /* #601: @9 = (@9-@38) */
  w9 -= w38;
  /* #602: @22 = (-@22) */
  w22 = (- w22 );
  /* #603: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #604: @38 = (@34*@22) */
  w38  = (w34*w22);
  /* #605: @53 = (@36*@51) */
  w53  = (w36*w51);
  /* #606: @38 = (@38+@53) */
  w38 += w53;
  /* #607: @53 = (@30*@24) */
  w53  = (w30*w24);
  /* #608: @38 = (@38+@53) */
  w38 += w53;
  /* #609: @53 = (@36*@25) */
  w53  = (w36*w25);
  /* #610: @38 = (@38-@53) */
  w38 -= w53;
  /* #611: @23 = (-@23) */
  w23 = (- w23 );
  /* #612: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #613: @34 = (@34*@23) */
  w34 *= w23;
  /* #614: @38 = (@38+@34) */
  w38 += w34;
  /* #615: @34 = (@26*@40) */
  w34  = (w26*w40);
  /* #616: @38 = (@38+@34) */
  w38 += w34;
  /* #617: @34 = (@30*@28) */
  w34  = (w30*w28);
  /* #618: @38 = (@38+@34) */
  w38 += w34;
  /* #619: @34 = (@26*@42) */
  w34  = (w26*w42);
  /* #620: @38 = (@38+@34) */
  w38 += w34;
  /* #621: @22 = (@37*@22) */
  w22  = (w37*w22);
  /* #622: @34 = (@30*@51) */
  w34  = (w30*w51);
  /* #623: @22 = (@22+@34) */
  w22 += w34;
  /* #624: @34 = (@36*@24) */
  w34  = (w36*w24);
  /* #625: @22 = (@22-@34) */
  w22 -= w34;
  /* #626: @30 = (@30*@25) */
  w30 *= w25;
  /* #627: @22 = (@22+@30) */
  w22 += w30;
  /* #628: @30 = (@2*@40) */
  w30  = (w2*w40);
  /* #629: @22 = (@22+@30) */
  w22 += w30;
  /* #630: @30 = (@36*@28) */
  w30  = (w36*w28);
  /* #631: @22 = (@22+@30) */
  w22 += w30;
  /* #632: @30 = (@2*@42) */
  w30  = (w2*w42);
  /* #633: @22 = (@22+@30) */
  w22 += w30;
  /* #634: @27 = (-@27) */
  w27 = (- w27 );
  /* #635: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #636: @37 = (@37*@27) */
  w37 *= w27;
  /* #637: @22 = (@22+@37) */
  w22 += w37;
  /* #638: @51 = (@26*@51) */
  w51  = (w26*w51);
  /* #639: @24 = (@2*@24) */
  w24  = (w2*w24);
  /* #640: @51 = (@51+@24) */
  w51 += w24;
  /* #641: @26 = (@26*@25) */
  w26 *= w25;
  /* #642: @51 = (@51+@26) */
  w51 += w26;
  /* #643: @23 = (@29*@23) */
  w23  = (w29*w23);
  /* #644: @51 = (@51+@23) */
  w51 += w23;
  /* #645: @40 = (@36*@40) */
  w40  = (w36*w40);
  /* #646: @51 = (@51+@40) */
  w51 += w40;
  /* #647: @2 = (@2*@28) */
  w2 *= w28;
  /* #648: @51 = (@51+@2) */
  w51 += w2;
  /* #649: @36 = (@36*@42) */
  w36 *= w42;
  /* #650: @51 = (@51-@36) */
  w51 -= w36;
  /* #651: @29 = (@29*@27) */
  w29 *= w27;
  /* #652: @51 = (@51+@29) */
  w51 += w29;
  /* #653: @29 = (@41*@39) */
  w29  = (w41*w39);
  /* #654: @31 = mac(@16,@46,@31) */
  casadi_mtimes(w16, casadi_s14, w46, casadi_s11, (&w31), casadi_s13, w, 0);
  /* #655: @11 = (@11*@31) */
  for (i=0, rr=w11; i<3; ++i) (*rr++) *= w31;
  /* #656: @15 = (@15*@56) */
  for (i=0, rr=w15; i<3; ++i) (*rr++) *= w56;
  /* #657: @11 = (@11+@15) */
  for (i=0, rr=w11, cs=w15; i<3; ++i) (*rr++) += (*cs++);
  /* #658: {@56, @31, @27} = vertsplit(@11) */
  w56 = w11[0];
  w31 = w11[1];
  w27 = w11[2];
  /* #659: @36 = (@6*@31) */
  w36  = (w6*w31);
  /* #660: @29 = (@29+@36) */
  w29 += w36;
  /* #661: @29 = (@4*@29) */
  w29  = (w4*w29);
  /* #662: @27 = (@5*@27) */
  w27  = (w5*w27);
  /* #663: @29 = (@29-@27) */
  w29 -= w27;
  /* #664: @27 = (@7*@56) */
  w27  = (w7*w56);
  /* #665: @36 = (@33*@32) */
  w36  = (w33*w32);
  /* #666: @27 = (@27-@36) */
  w27 -= w36;
  /* #667: @4 = (@4*@27) */
  w4 *= w27;
  /* #668: @29 = (@29+@4) */
  w29 += w4;
  /* #669: @31 = (@5*@31) */
  w31  = (w5*w31);
  /* #670: @7 = (@7*@31) */
  w7 *= w31;
  /* #671: @41 = (@5*@41) */
  w41  = (w5*w41);
  /* #672: @41 = (@41*@32) */
  w41 *= w32;
  /* #673: @7 = (@7-@41) */
  w7 -= w41;
  /* #674: @33 = (@5*@33) */
  w33  = (w5*w33);
  /* #675: @33 = (@33*@39) */
  w33 *= w39;
  /* #676: @5 = (@5*@56) */
  w5 *= w56;
  /* #677: @6 = (@6*@5) */
  w6 *= w5;
  /* #678: @33 = (@33+@6) */
  w33 += w6;
  /* #679: @7 = (@7-@33) */
  w7 -= w33;
  /* #680: @57 = vertcat(@8, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @1, @9, @38, @22, @51, @1, @1, @1, @29, @7, @1, @1) */
  rr=w57;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w38;
  *rr++ = w22;
  *rr++ = w51;
  *rr++ = w29;
  *rr++ = w7;
  /* #681: @58 = @57[:7] */
  for (rr=w58, ss=w57+0; ss!=w57+7; ss+=1) *rr++ = *ss;
  /* #682: (@0[5, 11, 18, 25, 32, 39, 46] = @58) */
  for (cii=casadi_s15, rr=w0, ss=w58; cii!=casadi_s15+7; ++cii, ++ss) rr[*cii] = *ss;
  /* #683: @59 = @0' */
  casadi_trans(w0,casadi_s16, w59, casadi_s16, iw);
  /* #684: output[0][0] = @59 */
  casadi_copy(w59, 47, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_accel_cost_y_0_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int payload_accel_cost_y_0_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_accel_cost_y_0_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void payload_accel_cost_y_0_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int payload_accel_cost_y_0_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void payload_accel_cost_y_0_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void payload_accel_cost_y_0_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void payload_accel_cost_y_0_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int payload_accel_cost_y_0_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int payload_accel_cost_y_0_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real payload_accel_cost_y_0_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* payload_accel_cost_y_0_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* payload_accel_cost_y_0_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* payload_accel_cost_y_0_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s17;
    case 1: return casadi_s18;
    case 2: return casadi_s19;
    case 3: return casadi_s2;
    case 4: return casadi_s20;
    case 5: return casadi_s19;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* payload_accel_cost_y_0_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s16;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int payload_accel_cost_y_0_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 34;
  if (sz_res) *sz_res = 29;
  if (sz_iw) *sz_iw = 29;
  if (sz_w) *sz_w = 262;
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_accel_cost_y_0_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 34*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 29*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 29*sizeof(casadi_int);
  if (sz_w) *sz_w = 262*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
