/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) payload_accel_cost_y_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

#define CASADI_CAST(x,y) ((x) y)

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s1[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s2[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s3[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s4[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s5[4] = {0, 1, 0, 0};
static const casadi_int casadi_s6[3] = {0, 0, 0};
static const casadi_int casadi_s7[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s8[30] = {28, 3, 0, 8, 16, 24, 0, 11, 17, 18, 19, 20, 24, 25, 0, 12, 17, 18, 19, 20, 24, 25, 0, 13, 17, 18, 19, 20, 24, 25};
static const casadi_int casadi_s9[3] = {3, 0, 0};

static const casadi_real casadi_c0[3] = {0., 0., -1.9613299999999999e+01};
static const casadi_real casadi_c1[3] = {0., 0., -2.4516624999999999e+00};
static const casadi_real casadi_c2[3] = {0., 0., 1.};

/* payload_accel_cost_y_fun_jac_ut_xt:(i0[24],i1[4],i2[0],i3[],i4[0])->(o0[3],o1[28x3,24nz],o2[3x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+3, w1, *w2=w+7, w3, *w4=w+11, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+28, *w20=w+31, *w21=w+34, *w22=w+37, *w23=w+46, *w24=w+55, *w25=w+79, *w26=w+88, *w27=w+91, w28, w29, w30, w31, w32, w33, w34, w35, w36, w37;
  /* #0: @0 = [0, 0, -19.6133] */
  casadi_copy(casadi_c0, 3, w0);
  /* #1: @1 = 0 */
  w1 = 0.;
  /* #2: @2 = [0, 0, -2.45166] */
  casadi_copy(casadi_c1, 3, w2);
  /* #3: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #4: @4 = zeros(3x1) */
  casadi_clear(w4, 3);
  /* #5: @5 = 1 */
  w5 = 1.;
  /* #6: @6 = input[0][15] */
  w6 = arg[0] ? arg[0][15] : 0;
  /* #7: @7 = sq(@6) */
  w7 = casadi_sq( w6 );
  /* #8: @8 = input[0][16] */
  w8 = arg[0] ? arg[0][16] : 0;
  /* #9: @9 = sq(@8) */
  w9 = casadi_sq( w8 );
  /* #10: @10 = (@7+@9) */
  w10  = (w7+w9);
  /* #11: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #12: @10 = (@5-@10) */
  w10  = (w5-w10);
  /* #13: @11 = input[0][14] */
  w11 = arg[0] ? arg[0][14] : 0;
  /* #14: @12 = (@11*@6) */
  w12  = (w11*w6);
  /* #15: @13 = input[0][13] */
  w13 = arg[0] ? arg[0][13] : 0;
  /* #16: @14 = (@8*@13) */
  w14  = (w8*w13);
  /* #17: @15 = (@12-@14) */
  w15  = (w12-w14);
  /* #18: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #19: @16 = (@11*@8) */
  w16  = (w11*w8);
  /* #20: @17 = (@6*@13) */
  w17  = (w6*w13);
  /* #21: @18 = (@16+@17) */
  w18  = (w16+w17);
  /* #22: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #23: @19 = horzcat(@10, @15, @18) */
  rr=w19;
  *rr++ = w10;
  *rr++ = w15;
  *rr++ = w18;
  /* #24: @19 = @19' */
  /* #25: @12 = (@12+@14) */
  w12 += w14;
  /* #26: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #27: @14 = sq(@11) */
  w14 = casadi_sq( w11 );
  /* #28: @9 = (@14+@9) */
  w9  = (w14+w9);
  /* #29: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #30: @9 = (@5-@9) */
  w9  = (w5-w9);
  /* #31: @10 = (@6*@8) */
  w10  = (w6*w8);
  /* #32: @15 = (@11*@13) */
  w15  = (w11*w13);
  /* #33: @18 = (@10-@15) */
  w18  = (w10-w15);
  /* #34: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #35: @20 = horzcat(@12, @9, @18) */
  rr=w20;
  *rr++ = w12;
  *rr++ = w9;
  *rr++ = w18;
  /* #36: @20 = @20' */
  /* #37: @16 = (@16-@17) */
  w16 -= w17;
  /* #38: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #39: @10 = (@10+@15) */
  w10 += w15;
  /* #40: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #41: @14 = (@14+@7) */
  w14 += w7;
  /* #42: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #43: @5 = (@5-@14) */
  w5 -= w14;
  /* #44: @21 = horzcat(@16, @10, @5) */
  rr=w21;
  *rr++ = w16;
  *rr++ = w10;
  *rr++ = w5;
  /* #45: @21 = @21' */
  /* #46: @22 = horzcat(@19, @20, @21) */
  rr=w22;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  /* #47: @23 = @22' */
  for (i=0, rr=w23, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #48: @19 = [0, 0, 1] */
  casadi_copy(casadi_c2, 3, w19);
  /* #49: @4 = mac(@23,@19,@4) */
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #50: @20 = (@3*@4) */
  for (i=0, rr=w20, cs=w4; i<3; ++i) (*rr++)  = (w3*(*cs++));
  /* #51: @2 = (@2+@20) */
  for (i=0, rr=w2, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #52: @20 = @2' */
  casadi_copy(w2, 3, w20);
  /* #53: @16 = input[0][20] */
  w16 = arg[0] ? arg[0][20] : 0;
  /* #54: @10 = sin(@16) */
  w10 = sin( w16 );
  /* #55: @5 = input[0][21] */
  w5 = arg[0] ? arg[0][21] : 0;
  /* #56: @14 = cos(@5) */
  w14 = cos( w5 );
  /* #57: @7 = (@10*@14) */
  w7  = (w10*w14);
  /* #58: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #59: @15 = (@10*@5) */
  w15  = (w10*w5);
  /* #60: @16 = cos(@16) */
  w16 = cos( w16 );
  /* #61: @21 = vertcat(@7, @15, @16) */
  rr=w21;
  *rr++ = w7;
  *rr++ = w15;
  *rr++ = w16;
  /* #62: @1 = mac(@20,@21,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w21+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #63: @20 = (@1*@21) */
  for (i=0, rr=w20, cs=w21; i<3; ++i) (*rr++)  = (w1*(*cs++));
  /* #64: @0 = (@0+@20) */
  for (i=0, rr=w0, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #65: @7 = 0.1 */
  w7 = 1.0000000000000001e-01;
  /* #66: @15 = input[0][7] */
  w15 = arg[0] ? arg[0][7] : 0;
  /* #67: @17 = input[0][8] */
  w17 = arg[0] ? arg[0][8] : 0;
  /* #68: @12 = input[0][9] */
  w12 = arg[0] ? arg[0][9] : 0;
  /* #69: @20 = vertcat(@15, @17, @12) */
  rr=w20;
  *rr++ = w15;
  *rr++ = w17;
  *rr++ = w12;
  /* #70: @20 = (@7*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w7*(*cs++));
  /* #71: @0 = (@0-@20) */
  for (i=0, rr=w0, cs=w20; i<3; ++i) (*rr++) -= (*cs++);
  /* #72: @7 = 2 */
  w7 = 2.;
  /* #73: @0 = (@0/@7) */
  for (i=0, rr=w0; i<3; ++i) (*rr++) /= w7;
  /* #74: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #75: @24 = zeros(28x3,24nz) */
  casadi_clear(w24, 24);
  /* #76: @7 = project(@21) */
  casadi_sparsify(w21, (&w7), casadi_s0, 0);
  /* #77: @15 = all_0.5(3x1,1nz) */
  w15 = 5.0000000000000000e-01;
  /* #78: @17 = dot(@7, @15) */
  w17 = casadi_dot(1, (&w7), (&w15));
  /* #79: @0 = @21' */
  casadi_copy(w21, 3, w0);
  /* #80: @20 = (@17*@0) */
  for (i=0, rr=w20, cs=w0; i<3; ++i) (*rr++)  = (w17*(*cs++));
  /* #81: @20 = @20' */
  /* #82: @7 = dot(@4, @20) */
  w7 = casadi_dot(3, w4, w20);
  /* #83: (@24[0] = @7) */
  for (rr=w24+0, ss=(&w7); rr!=w24+1; rr+=1) *rr = *ss++;
  /* #84: @7 = all_-0.05(3x1,1nz) */
  w7 = -5.0000000000000003e-02;
  /* #85: {@12, NULL, NULL} = vertsplit(@7) */
  w12 = w7;
  /* #86: (@24[1] = @12) */
  for (rr=w24+1, ss=(&w12); rr!=w24+2; rr+=1) *rr = *ss++;
  /* #87: @23 = zeros(3x3) */
  casadi_clear(w23, 9);
  /* #88: @20 = (@3*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w3*(*cs++));
  /* #89: @19 = @19' */
  /* #90: @22 = mac(@20,@19,@23) */
  casadi_copy(w23, 9, w22);
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w19+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #91: @25 = @22' */
  for (i=0, rr=w25, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #92: {@20, @26, @27} = horzsplit(@25) */
  casadi_copy(w25, 3, w20);
  casadi_copy(w25+3, 3, w26);
  casadi_copy(w25+6, 3, w27);
  /* #93: @27 = @27' */
  /* #94: {@12, @7, @9} = horzsplit(@27) */
  w12 = w27[0];
  w7 = w27[1];
  w9 = w27[2];
  /* #95: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #96: @18 = (@11*@7) */
  w18  = (w11*w7);
  /* #97: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #98: @28 = (@6*@12) */
  w28  = (w6*w12);
  /* #99: @18 = (@18-@28) */
  w18 -= w28;
  /* #100: @26 = @26' */
  /* #101: {@28, @29, @30} = horzsplit(@26) */
  w28 = w26[0];
  w29 = w26[1];
  w30 = w26[2];
  /* #102: @30 = (2.*@30) */
  w30 = (2.* w30 );
  /* #103: @31 = (@11*@30) */
  w31  = (w11*w30);
  /* #104: @18 = (@18-@31) */
  w18 -= w31;
  /* #105: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #106: @31 = (@8*@28) */
  w31  = (w8*w28);
  /* #107: @18 = (@18+@31) */
  w18 += w31;
  /* #108: @20 = @20' */
  /* #109: {@31, @32, @33} = horzsplit(@20) */
  w31 = w20[0];
  w32 = w20[1];
  w33 = w20[2];
  /* #110: @33 = (2.*@33) */
  w33 = (2.* w33 );
  /* #111: @34 = (@6*@33) */
  w34  = (w6*w33);
  /* #112: @18 = (@18+@34) */
  w18 += w34;
  /* #113: @32 = (2.*@32) */
  w32 = (2.* w32 );
  /* #114: @34 = (@8*@32) */
  w34  = (w8*w32);
  /* #115: @18 = (@18-@34) */
  w18 -= w34;
  /* #116: (@24[2] = @18) */
  for (rr=w24+2, ss=(&w18); rr!=w24+3; rr+=1) *rr = *ss++;
  /* #117: @18 = (2.*@11) */
  w18 = (2.* w11 );
  /* #118: @9 = (-@9) */
  w9 = (- w9 );
  /* #119: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #120: @34 = (@18*@9) */
  w34  = (w18*w9);
  /* #121: @35 = (@13*@7) */
  w35  = (w13*w7);
  /* #122: @34 = (@34+@35) */
  w34 += w35;
  /* #123: @35 = (@8*@12) */
  w35  = (w8*w12);
  /* #124: @34 = (@34+@35) */
  w34 += w35;
  /* #125: @35 = (@13*@30) */
  w35  = (w13*w30);
  /* #126: @34 = (@34-@35) */
  w34 -= w35;
  /* #127: @29 = (-@29) */
  w29 = (- w29 );
  /* #128: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #129: @35 = (@18*@29) */
  w35  = (w18*w29);
  /* #130: @34 = (@34+@35) */
  w34 += w35;
  /* #131: @35 = (@6*@28) */
  w35  = (w6*w28);
  /* #132: @34 = (@34+@35) */
  w34 += w35;
  /* #133: @35 = (@8*@33) */
  w35  = (w8*w33);
  /* #134: @34 = (@34+@35) */
  w34 += w35;
  /* #135: @35 = (@6*@32) */
  w35  = (w6*w32);
  /* #136: @34 = (@34+@35) */
  w34 += w35;
  /* #137: (@24[3] = @34) */
  for (rr=w24+3, ss=(&w34); rr!=w24+4; rr+=1) *rr = *ss++;
  /* #138: @34 = (2.*@6) */
  w34 = (2.* w6 );
  /* #139: @9 = (@34*@9) */
  w9  = (w34*w9);
  /* #140: @35 = (@8*@7) */
  w35  = (w8*w7);
  /* #141: @9 = (@9+@35) */
  w9 += w35;
  /* #142: @35 = (@13*@12) */
  w35  = (w13*w12);
  /* #143: @9 = (@9-@35) */
  w9 -= w35;
  /* #144: @35 = (@8*@30) */
  w35  = (w8*w30);
  /* #145: @9 = (@9+@35) */
  w9 += w35;
  /* #146: @35 = (@11*@28) */
  w35  = (w11*w28);
  /* #147: @9 = (@9+@35) */
  w9 += w35;
  /* #148: @35 = (@13*@33) */
  w35  = (w13*w33);
  /* #149: @9 = (@9+@35) */
  w9 += w35;
  /* #150: @35 = (@11*@32) */
  w35  = (w11*w32);
  /* #151: @9 = (@9+@35) */
  w9 += w35;
  /* #152: @31 = (-@31) */
  w31 = (- w31 );
  /* #153: @31 = (2.*@31) */
  w31 = (2.* w31 );
  /* #154: @35 = (@34*@31) */
  w35  = (w34*w31);
  /* #155: @9 = (@9+@35) */
  w9 += w35;
  /* #156: (@24[4] = @9) */
  for (rr=w24+4, ss=(&w9); rr!=w24+5; rr+=1) *rr = *ss++;
  /* #157: @7 = (@6*@7) */
  w7  = (w6*w7);
  /* #158: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #159: @7 = (@7+@12) */
  w7 += w12;
  /* #160: @30 = (@6*@30) */
  w30  = (w6*w30);
  /* #161: @7 = (@7+@30) */
  w7 += w30;
  /* #162: @30 = (2.*@8) */
  w30 = (2.* w8 );
  /* #163: @29 = (@30*@29) */
  w29  = (w30*w29);
  /* #164: @7 = (@7+@29) */
  w7 += w29;
  /* #165: @28 = (@13*@28) */
  w28  = (w13*w28);
  /* #166: @7 = (@7+@28) */
  w7 += w28;
  /* #167: @33 = (@11*@33) */
  w33  = (w11*w33);
  /* #168: @7 = (@7+@33) */
  w7 += w33;
  /* #169: @32 = (@13*@32) */
  w32  = (w13*w32);
  /* #170: @7 = (@7-@32) */
  w7 -= w32;
  /* #171: @31 = (@30*@31) */
  w31  = (w30*w31);
  /* #172: @7 = (@7+@31) */
  w7 += w31;
  /* #173: (@24[5] = @7) */
  for (rr=w24+5, ss=(&w7); rr!=w24+6; rr+=1) *rr = *ss++;
  /* #174: @15 = (@15*@1) */
  w15 *= w1;
  /* #175: @20 = dense(@15) */
  casadi_densify((&w15), casadi_s0, w20, 0);
  /* #176: @26 = (@2*@17) */
  for (i=0, rr=w26, cr=w2; i<3; ++i) (*rr++)  = ((*cr++)*w17);
  /* #177: @20 = (@20+@26) */
  for (i=0, rr=w20, cs=w26; i<3; ++i) (*rr++) += (*cs++);
  /* #178: {@17, @15, @7} = vertsplit(@20) */
  w17 = w20[0];
  w15 = w20[1];
  w7 = w20[2];
  /* #179: @31 = (@5*@15) */
  w31  = (w5*w15);
  /* #180: @31 = (@16*@31) */
  w31  = (w16*w31);
  /* #181: @7 = (@10*@7) */
  w7  = (w10*w7);
  /* #182: @31 = (@31-@7) */
  w31 -= w7;
  /* #183: @7 = (@14*@17) */
  w7  = (w14*w17);
  /* #184: @7 = (@16*@7) */
  w7  = (w16*w7);
  /* #185: @31 = (@31+@7) */
  w31 += w7;
  /* #186: (@24[6] = @31) */
  for (rr=w24+6, ss=(&w31); rr!=w24+7; rr+=1) *rr = *ss++;
  /* #187: @15 = (@10*@15) */
  w15  = (w10*w15);
  /* #188: @15 = (@14*@15) */
  w15  = (w14*w15);
  /* #189: @17 = (@10*@17) */
  w17  = (w10*w17);
  /* #190: @17 = (@5*@17) */
  w17  = (w5*w17);
  /* #191: @15 = (@15-@17) */
  w15 -= w17;
  /* #192: (@24[7] = @15) */
  for (rr=w24+7, ss=(&w15); rr!=w24+8; rr+=1) *rr = *ss++;
  /* #193: @15 = project(@21) */
  casadi_sparsify(w21, (&w15), casadi_s1, 0);
  /* #194: @17 = all_0.5(3x1,1nz) */
  w17 = 5.0000000000000000e-01;
  /* #195: @31 = dot(@15, @17) */
  w31 = casadi_dot(1, (&w15), (&w17));
  /* #196: @20 = (@31*@0) */
  for (i=0, rr=w20, cs=w0; i<3; ++i) (*rr++)  = (w31*(*cs++));
  /* #197: @20 = @20' */
  /* #198: @15 = dot(@4, @20) */
  w15 = casadi_dot(3, w4, w20);
  /* #199: (@24[8] = @15) */
  for (rr=w24+8, ss=(&w15); rr!=w24+9; rr+=1) *rr = *ss++;
  /* #200: @15 = all_-0.05(3x1,1nz) */
  w15 = -5.0000000000000003e-02;
  /* #201: {NULL, @7, NULL} = vertsplit(@15) */
  w7 = w15;
  /* #202: (@24[9] = @7) */
  for (rr=w24+9, ss=(&w7); rr!=w24+10; rr+=1) *rr = *ss++;
  /* #203: @20 = (@3*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w3*(*cs++));
  /* #204: @25 = mac(@20,@19,@23) */
  casadi_copy(w23, 9, w25);
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w19+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #205: @22 = @25' */
  for (i=0, rr=w22, cs=w25; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #206: {@20, @26, @27} = horzsplit(@22) */
  casadi_copy(w22, 3, w20);
  casadi_copy(w22+3, 3, w26);
  casadi_copy(w22+6, 3, w27);
  /* #207: @27 = @27' */
  /* #208: {@7, @15, @32} = horzsplit(@27) */
  w7 = w27[0];
  w15 = w27[1];
  w32 = w27[2];
  /* #209: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #210: @33 = (@11*@15) */
  w33  = (w11*w15);
  /* #211: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #212: @28 = (@6*@7) */
  w28  = (w6*w7);
  /* #213: @33 = (@33-@28) */
  w33 -= w28;
  /* #214: @26 = @26' */
  /* #215: {@28, @29, @12} = horzsplit(@26) */
  w28 = w26[0];
  w29 = w26[1];
  w12 = w26[2];
  /* #216: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #217: @9 = (@11*@12) */
  w9  = (w11*w12);
  /* #218: @33 = (@33-@9) */
  w33 -= w9;
  /* #219: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #220: @9 = (@8*@28) */
  w9  = (w8*w28);
  /* #221: @33 = (@33+@9) */
  w33 += w9;
  /* #222: @20 = @20' */
  /* #223: {@9, @35, @36} = horzsplit(@20) */
  w9 = w20[0];
  w35 = w20[1];
  w36 = w20[2];
  /* #224: @36 = (2.*@36) */
  w36 = (2.* w36 );
  /* #225: @37 = (@6*@36) */
  w37  = (w6*w36);
  /* #226: @33 = (@33+@37) */
  w33 += w37;
  /* #227: @35 = (2.*@35) */
  w35 = (2.* w35 );
  /* #228: @37 = (@8*@35) */
  w37  = (w8*w35);
  /* #229: @33 = (@33-@37) */
  w33 -= w37;
  /* #230: (@24[10] = @33) */
  for (rr=w24+10, ss=(&w33); rr!=w24+11; rr+=1) *rr = *ss++;
  /* #231: @32 = (-@32) */
  w32 = (- w32 );
  /* #232: @32 = (2.*@32) */
  w32 = (2.* w32 );
  /* #233: @33 = (@18*@32) */
  w33  = (w18*w32);
  /* #234: @37 = (@13*@15) */
  w37  = (w13*w15);
  /* #235: @33 = (@33+@37) */
  w33 += w37;
  /* #236: @37 = (@8*@7) */
  w37  = (w8*w7);
  /* #237: @33 = (@33+@37) */
  w33 += w37;
  /* #238: @37 = (@13*@12) */
  w37  = (w13*w12);
  /* #239: @33 = (@33-@37) */
  w33 -= w37;
  /* #240: @29 = (-@29) */
  w29 = (- w29 );
  /* #241: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #242: @37 = (@18*@29) */
  w37  = (w18*w29);
  /* #243: @33 = (@33+@37) */
  w33 += w37;
  /* #244: @37 = (@6*@28) */
  w37  = (w6*w28);
  /* #245: @33 = (@33+@37) */
  w33 += w37;
  /* #246: @37 = (@8*@36) */
  w37  = (w8*w36);
  /* #247: @33 = (@33+@37) */
  w33 += w37;
  /* #248: @37 = (@6*@35) */
  w37  = (w6*w35);
  /* #249: @33 = (@33+@37) */
  w33 += w37;
  /* #250: (@24[11] = @33) */
  for (rr=w24+11, ss=(&w33); rr!=w24+12; rr+=1) *rr = *ss++;
  /* #251: @32 = (@34*@32) */
  w32  = (w34*w32);
  /* #252: @33 = (@8*@15) */
  w33  = (w8*w15);
  /* #253: @32 = (@32+@33) */
  w32 += w33;
  /* #254: @33 = (@13*@7) */
  w33  = (w13*w7);
  /* #255: @32 = (@32-@33) */
  w32 -= w33;
  /* #256: @33 = (@8*@12) */
  w33  = (w8*w12);
  /* #257: @32 = (@32+@33) */
  w32 += w33;
  /* #258: @33 = (@11*@28) */
  w33  = (w11*w28);
  /* #259: @32 = (@32+@33) */
  w32 += w33;
  /* #260: @33 = (@13*@36) */
  w33  = (w13*w36);
  /* #261: @32 = (@32+@33) */
  w32 += w33;
  /* #262: @33 = (@11*@35) */
  w33  = (w11*w35);
  /* #263: @32 = (@32+@33) */
  w32 += w33;
  /* #264: @9 = (-@9) */
  w9 = (- w9 );
  /* #265: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #266: @33 = (@34*@9) */
  w33  = (w34*w9);
  /* #267: @32 = (@32+@33) */
  w32 += w33;
  /* #268: (@24[12] = @32) */
  for (rr=w24+12, ss=(&w32); rr!=w24+13; rr+=1) *rr = *ss++;
  /* #269: @15 = (@6*@15) */
  w15  = (w6*w15);
  /* #270: @7 = (@11*@7) */
  w7  = (w11*w7);
  /* #271: @15 = (@15+@7) */
  w15 += w7;
  /* #272: @12 = (@6*@12) */
  w12  = (w6*w12);
  /* #273: @15 = (@15+@12) */
  w15 += w12;
  /* #274: @29 = (@30*@29) */
  w29  = (w30*w29);
  /* #275: @15 = (@15+@29) */
  w15 += w29;
  /* #276: @28 = (@13*@28) */
  w28  = (w13*w28);
  /* #277: @15 = (@15+@28) */
  w15 += w28;
  /* #278: @36 = (@11*@36) */
  w36  = (w11*w36);
  /* #279: @15 = (@15+@36) */
  w15 += w36;
  /* #280: @35 = (@13*@35) */
  w35  = (w13*w35);
  /* #281: @15 = (@15-@35) */
  w15 -= w35;
  /* #282: @9 = (@30*@9) */
  w9  = (w30*w9);
  /* #283: @15 = (@15+@9) */
  w15 += w9;
  /* #284: (@24[13] = @15) */
  for (rr=w24+13, ss=(&w15); rr!=w24+14; rr+=1) *rr = *ss++;
  /* #285: @17 = (@17*@1) */
  w17 *= w1;
  /* #286: @20 = dense(@17) */
  casadi_densify((&w17), casadi_s1, w20, 0);
  /* #287: @26 = (@2*@31) */
  for (i=0, rr=w26, cr=w2; i<3; ++i) (*rr++)  = ((*cr++)*w31);
  /* #288: @20 = (@20+@26) */
  for (i=0, rr=w20, cs=w26; i<3; ++i) (*rr++) += (*cs++);
  /* #289: {@31, @17, @15} = vertsplit(@20) */
  w31 = w20[0];
  w17 = w20[1];
  w15 = w20[2];
  /* #290: @9 = (@5*@17) */
  w9  = (w5*w17);
  /* #291: @9 = (@16*@9) */
  w9  = (w16*w9);
  /* #292: @15 = (@10*@15) */
  w15  = (w10*w15);
  /* #293: @9 = (@9-@15) */
  w9 -= w15;
  /* #294: @15 = (@14*@31) */
  w15  = (w14*w31);
  /* #295: @15 = (@16*@15) */
  w15  = (w16*w15);
  /* #296: @9 = (@9+@15) */
  w9 += w15;
  /* #297: (@24[14] = @9) */
  for (rr=w24+14, ss=(&w9); rr!=w24+15; rr+=1) *rr = *ss++;
  /* #298: @17 = (@10*@17) */
  w17  = (w10*w17);
  /* #299: @17 = (@14*@17) */
  w17  = (w14*w17);
  /* #300: @31 = (@10*@31) */
  w31  = (w10*w31);
  /* #301: @31 = (@5*@31) */
  w31  = (w5*w31);
  /* #302: @17 = (@17-@31) */
  w17 -= w31;
  /* #303: (@24[15] = @17) */
  for (rr=w24+15, ss=(&w17); rr!=w24+16; rr+=1) *rr = *ss++;
  /* #304: @17 = project(@21) */
  casadi_sparsify(w21, (&w17), casadi_s2, 0);
  /* #305: @31 = all_0.5(3x1,1nz) */
  w31 = 5.0000000000000000e-01;
  /* #306: @9 = dot(@17, @31) */
  w9 = casadi_dot(1, (&w17), (&w31));
  /* #307: @0 = (@9*@0) */
  for (i=0, rr=w0, cs=w0; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #308: @0 = @0' */
  /* #309: @17 = dot(@4, @0) */
  w17 = casadi_dot(3, w4, w0);
  /* #310: (@24[16] = @17) */
  for (rr=w24+16, ss=(&w17); rr!=w24+17; rr+=1) *rr = *ss++;
  /* #311: @17 = all_-0.05(3x1,1nz) */
  w17 = -5.0000000000000003e-02;
  /* #312: {NULL, NULL, @15} = vertsplit(@17) */
  w15 = w17;
  /* #313: (@24[17] = @15) */
  for (rr=w24+17, ss=(&w15); rr!=w24+18; rr+=1) *rr = *ss++;
  /* #314: @0 = (@3*@0) */
  for (i=0, rr=w0, cs=w0; i<3; ++i) (*rr++)  = (w3*(*cs++));
  /* #315: @23 = mac(@0,@19,@23) */
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w0+j, tt=w19+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #316: @22 = @23' */
  for (i=0, rr=w22, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #317: {@0, @19, @4} = horzsplit(@22) */
  casadi_copy(w22, 3, w0);
  casadi_copy(w22+3, 3, w19);
  casadi_copy(w22+6, 3, w4);
  /* #318: @4 = @4' */
  /* #319: {@3, @15, @17} = horzsplit(@4) */
  w3 = w4[0];
  w15 = w4[1];
  w17 = w4[2];
  /* #320: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #321: @35 = (@11*@15) */
  w35  = (w11*w15);
  /* #322: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #323: @36 = (@6*@3) */
  w36  = (w6*w3);
  /* #324: @35 = (@35-@36) */
  w35 -= w36;
  /* #325: @19 = @19' */
  /* #326: {@36, @28, @29} = horzsplit(@19) */
  w36 = w19[0];
  w28 = w19[1];
  w29 = w19[2];
  /* #327: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #328: @12 = (@11*@29) */
  w12  = (w11*w29);
  /* #329: @35 = (@35-@12) */
  w35 -= w12;
  /* #330: @36 = (2.*@36) */
  w36 = (2.* w36 );
  /* #331: @12 = (@8*@36) */
  w12  = (w8*w36);
  /* #332: @35 = (@35+@12) */
  w35 += w12;
  /* #333: @0 = @0' */
  /* #334: {@12, @7, @32} = horzsplit(@0) */
  w12 = w0[0];
  w7 = w0[1];
  w32 = w0[2];
  /* #335: @32 = (2.*@32) */
  w32 = (2.* w32 );
  /* #336: @33 = (@6*@32) */
  w33  = (w6*w32);
  /* #337: @35 = (@35+@33) */
  w35 += w33;
  /* #338: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #339: @33 = (@8*@7) */
  w33  = (w8*w7);
  /* #340: @35 = (@35-@33) */
  w35 -= w33;
  /* #341: (@24[18] = @35) */
  for (rr=w24+18, ss=(&w35); rr!=w24+19; rr+=1) *rr = *ss++;
  /* #342: @17 = (-@17) */
  w17 = (- w17 );
  /* #343: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #344: @35 = (@18*@17) */
  w35  = (w18*w17);
  /* #345: @33 = (@13*@15) */
  w33  = (w13*w15);
  /* #346: @35 = (@35+@33) */
  w35 += w33;
  /* #347: @33 = (@8*@3) */
  w33  = (w8*w3);
  /* #348: @35 = (@35+@33) */
  w35 += w33;
  /* #349: @33 = (@13*@29) */
  w33  = (w13*w29);
  /* #350: @35 = (@35-@33) */
  w35 -= w33;
  /* #351: @28 = (-@28) */
  w28 = (- w28 );
  /* #352: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #353: @18 = (@18*@28) */
  w18 *= w28;
  /* #354: @35 = (@35+@18) */
  w35 += w18;
  /* #355: @18 = (@6*@36) */
  w18  = (w6*w36);
  /* #356: @35 = (@35+@18) */
  w35 += w18;
  /* #357: @18 = (@8*@32) */
  w18  = (w8*w32);
  /* #358: @35 = (@35+@18) */
  w35 += w18;
  /* #359: @18 = (@6*@7) */
  w18  = (w6*w7);
  /* #360: @35 = (@35+@18) */
  w35 += w18;
  /* #361: (@24[19] = @35) */
  for (rr=w24+19, ss=(&w35); rr!=w24+20; rr+=1) *rr = *ss++;
  /* #362: @17 = (@34*@17) */
  w17  = (w34*w17);
  /* #363: @35 = (@8*@15) */
  w35  = (w8*w15);
  /* #364: @17 = (@17+@35) */
  w17 += w35;
  /* #365: @35 = (@13*@3) */
  w35  = (w13*w3);
  /* #366: @17 = (@17-@35) */
  w17 -= w35;
  /* #367: @8 = (@8*@29) */
  w8 *= w29;
  /* #368: @17 = (@17+@8) */
  w17 += w8;
  /* #369: @8 = (@11*@36) */
  w8  = (w11*w36);
  /* #370: @17 = (@17+@8) */
  w17 += w8;
  /* #371: @8 = (@13*@32) */
  w8  = (w13*w32);
  /* #372: @17 = (@17+@8) */
  w17 += w8;
  /* #373: @8 = (@11*@7) */
  w8  = (w11*w7);
  /* #374: @17 = (@17+@8) */
  w17 += w8;
  /* #375: @12 = (-@12) */
  w12 = (- w12 );
  /* #376: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #377: @34 = (@34*@12) */
  w34 *= w12;
  /* #378: @17 = (@17+@34) */
  w17 += w34;
  /* #379: (@24[20] = @17) */
  for (rr=w24+20, ss=(&w17); rr!=w24+21; rr+=1) *rr = *ss++;
  /* #380: @15 = (@6*@15) */
  w15  = (w6*w15);
  /* #381: @3 = (@11*@3) */
  w3  = (w11*w3);
  /* #382: @15 = (@15+@3) */
  w15 += w3;
  /* #383: @6 = (@6*@29) */
  w6 *= w29;
  /* #384: @15 = (@15+@6) */
  w15 += w6;
  /* #385: @28 = (@30*@28) */
  w28  = (w30*w28);
  /* #386: @15 = (@15+@28) */
  w15 += w28;
  /* #387: @36 = (@13*@36) */
  w36  = (w13*w36);
  /* #388: @15 = (@15+@36) */
  w15 += w36;
  /* #389: @11 = (@11*@32) */
  w11 *= w32;
  /* #390: @15 = (@15+@11) */
  w15 += w11;
  /* #391: @13 = (@13*@7) */
  w13 *= w7;
  /* #392: @15 = (@15-@13) */
  w15 -= w13;
  /* #393: @30 = (@30*@12) */
  w30 *= w12;
  /* #394: @15 = (@15+@30) */
  w15 += w30;
  /* #395: (@24[21] = @15) */
  for (rr=w24+21, ss=(&w15); rr!=w24+22; rr+=1) *rr = *ss++;
  /* #396: @31 = (@31*@1) */
  w31 *= w1;
  /* #397: @0 = dense(@31) */
  casadi_densify((&w31), casadi_s2, w0, 0);
  /* #398: @2 = (@2*@9) */
  for (i=0, rr=w2; i<3; ++i) (*rr++) *= w9;
  /* #399: @0 = (@0+@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) += (*cs++);
  /* #400: {@9, @31, @1} = vertsplit(@0) */
  w9 = w0[0];
  w31 = w0[1];
  w1 = w0[2];
  /* #401: @15 = (@5*@31) */
  w15  = (w5*w31);
  /* #402: @15 = (@16*@15) */
  w15  = (w16*w15);
  /* #403: @1 = (@10*@1) */
  w1  = (w10*w1);
  /* #404: @15 = (@15-@1) */
  w15 -= w1;
  /* #405: @1 = (@14*@9) */
  w1  = (w14*w9);
  /* #406: @16 = (@16*@1) */
  w16 *= w1;
  /* #407: @15 = (@15+@16) */
  w15 += w16;
  /* #408: (@24[22] = @15) */
  for (rr=w24+22, ss=(&w15); rr!=w24+23; rr+=1) *rr = *ss++;
  /* #409: @31 = (@10*@31) */
  w31  = (w10*w31);
  /* #410: @14 = (@14*@31) */
  w14 *= w31;
  /* #411: @10 = (@10*@9) */
  w10 *= w9;
  /* #412: @5 = (@5*@10) */
  w5 *= w10;
  /* #413: @14 = (@14-@5) */
  w14 -= w5;
  /* #414: (@24[23] = @14) */
  for (rr=w24+23, ss=(&w14); rr!=w24+24; rr+=1) *rr = *ss++;
  /* #415: output[1][0] = @24 */
  casadi_copy(w24, 24, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_accel_cost_y_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int payload_accel_cost_y_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_accel_cost_y_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void payload_accel_cost_y_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int payload_accel_cost_y_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void payload_accel_cost_y_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void payload_accel_cost_y_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void payload_accel_cost_y_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int payload_accel_cost_y_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int payload_accel_cost_y_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real payload_accel_cost_y_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* payload_accel_cost_y_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* payload_accel_cost_y_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* payload_accel_cost_y_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    case 4: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* payload_accel_cost_y_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    case 2: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int payload_accel_cost_y_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 104;
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_accel_cost_y_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 6*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 104*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
