/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) payload_accel_cost_y_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[3] = {0, 0, 0};
static const casadi_int casadi_s4[7] = {3, 1, 0, 3, 0, 1, 2};

static const casadi_real casadi_c0[3] = {0., 0., -1.9613299999999999e+01};
static const casadi_real casadi_c1[3] = {0., 0., -2.4516624999999999e+00};
static const casadi_real casadi_c2[3] = {0., 0., 1.};

/* payload_accel_cost_y_fun:(i0[24],i1[4],i2[0],i3[],i4[0])->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+3, w1, *w2=w+7, w3, *w4=w+11, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+28, *w20=w+31, *w21=w+34, *w22=w+37, *w23=w+46;
  /* #0: @0 = [0, 0, -19.6133] */
  casadi_copy(casadi_c0, 3, w0);
  /* #1: @1 = 0 */
  w1 = 0.;
  /* #2: @2 = [0, 0, -2.45166] */
  casadi_copy(casadi_c1, 3, w2);
  /* #3: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #4: @4 = zeros(3x1) */
  casadi_clear(w4, 3);
  /* #5: @5 = 1 */
  w5 = 1.;
  /* #6: @6 = input[0][15] */
  w6 = arg[0] ? arg[0][15] : 0;
  /* #7: @7 = sq(@6) */
  w7 = casadi_sq( w6 );
  /* #8: @8 = input[0][16] */
  w8 = arg[0] ? arg[0][16] : 0;
  /* #9: @9 = sq(@8) */
  w9 = casadi_sq( w8 );
  /* #10: @10 = (@7+@9) */
  w10  = (w7+w9);
  /* #11: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #12: @10 = (@5-@10) */
  w10  = (w5-w10);
  /* #13: @11 = input[0][14] */
  w11 = arg[0] ? arg[0][14] : 0;
  /* #14: @12 = (@11*@6) */
  w12  = (w11*w6);
  /* #15: @13 = input[0][13] */
  w13 = arg[0] ? arg[0][13] : 0;
  /* #16: @14 = (@8*@13) */
  w14  = (w8*w13);
  /* #17: @15 = (@12-@14) */
  w15  = (w12-w14);
  /* #18: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #19: @16 = (@11*@8) */
  w16  = (w11*w8);
  /* #20: @17 = (@6*@13) */
  w17  = (w6*w13);
  /* #21: @18 = (@16+@17) */
  w18  = (w16+w17);
  /* #22: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #23: @19 = horzcat(@10, @15, @18) */
  rr=w19;
  *rr++ = w10;
  *rr++ = w15;
  *rr++ = w18;
  /* #24: @19 = @19' */
  /* #25: @12 = (@12+@14) */
  w12 += w14;
  /* #26: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #27: @14 = sq(@11) */
  w14 = casadi_sq( w11 );
  /* #28: @9 = (@14+@9) */
  w9  = (w14+w9);
  /* #29: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #30: @9 = (@5-@9) */
  w9  = (w5-w9);
  /* #31: @6 = (@6*@8) */
  w6 *= w8;
  /* #32: @11 = (@11*@13) */
  w11 *= w13;
  /* #33: @13 = (@6-@11) */
  w13  = (w6-w11);
  /* #34: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #35: @20 = horzcat(@12, @9, @13) */
  rr=w20;
  *rr++ = w12;
  *rr++ = w9;
  *rr++ = w13;
  /* #36: @20 = @20' */
  /* #37: @16 = (@16-@17) */
  w16 -= w17;
  /* #38: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #39: @6 = (@6+@11) */
  w6 += w11;
  /* #40: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #41: @14 = (@14+@7) */
  w14 += w7;
  /* #42: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #43: @5 = (@5-@14) */
  w5 -= w14;
  /* #44: @21 = horzcat(@16, @6, @5) */
  rr=w21;
  *rr++ = w16;
  *rr++ = w6;
  *rr++ = w5;
  /* #45: @21 = @21' */
  /* #46: @22 = horzcat(@19, @20, @21) */
  rr=w22;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  /* #47: @23 = @22' */
  for (i=0, rr=w23, cs=w22; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #48: @19 = [0, 0, 1] */
  casadi_copy(casadi_c2, 3, w19);
  /* #49: @4 = mac(@23,@19,@4) */
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #50: @4 = (@3*@4) */
  for (i=0, rr=w4, cs=w4; i<3; ++i) (*rr++)  = (w3*(*cs++));
  /* #51: @2 = (@2+@4) */
  for (i=0, rr=w2, cs=w4; i<3; ++i) (*rr++) += (*cs++);
  /* #52: @2 = @2' */
  /* #53: @3 = input[0][20] */
  w3 = arg[0] ? arg[0][20] : 0;
  /* #54: @16 = sin(@3) */
  w16 = sin( w3 );
  /* #55: @6 = input[0][21] */
  w6 = arg[0] ? arg[0][21] : 0;
  /* #56: @5 = cos(@6) */
  w5 = cos( w6 );
  /* #57: @5 = (@16*@5) */
  w5  = (w16*w5);
  /* #58: @6 = sin(@6) */
  w6 = sin( w6 );
  /* #59: @16 = (@16*@6) */
  w16 *= w6;
  /* #60: @3 = cos(@3) */
  w3 = cos( w3 );
  /* #61: @4 = vertcat(@5, @16, @3) */
  rr=w4;
  *rr++ = w5;
  *rr++ = w16;
  *rr++ = w3;
  /* #62: @1 = mac(@2,@4,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #63: @4 = (@1*@4) */
  for (i=0, rr=w4, cs=w4; i<3; ++i) (*rr++)  = (w1*(*cs++));
  /* #64: @0 = (@0+@4) */
  for (i=0, rr=w0, cs=w4; i<3; ++i) (*rr++) += (*cs++);
  /* #65: @1 = 0.1 */
  w1 = 1.0000000000000001e-01;
  /* #66: @5 = input[0][7] */
  w5 = arg[0] ? arg[0][7] : 0;
  /* #67: @16 = input[0][8] */
  w16 = arg[0] ? arg[0][8] : 0;
  /* #68: @3 = input[0][9] */
  w3 = arg[0] ? arg[0][9] : 0;
  /* #69: @4 = vertcat(@5, @16, @3) */
  rr=w4;
  *rr++ = w5;
  *rr++ = w16;
  *rr++ = w3;
  /* #70: @4 = (@1*@4) */
  for (i=0, rr=w4, cs=w4; i<3; ++i) (*rr++)  = (w1*(*cs++));
  /* #71: @0 = (@0-@4) */
  for (i=0, rr=w0, cs=w4; i<3; ++i) (*rr++) -= (*cs++);
  /* #72: @1 = 2 */
  w1 = 2.;
  /* #73: @0 = (@0/@1) */
  for (i=0, rr=w0; i<3; ++i) (*rr++) /= w1;
  /* #74: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_accel_cost_y_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int payload_accel_cost_y_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_accel_cost_y_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void payload_accel_cost_y_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int payload_accel_cost_y_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void payload_accel_cost_y_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void payload_accel_cost_y_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void payload_accel_cost_y_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int payload_accel_cost_y_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int payload_accel_cost_y_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real payload_accel_cost_y_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* payload_accel_cost_y_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* payload_accel_cost_y_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* payload_accel_cost_y_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* payload_accel_cost_y_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int payload_accel_cost_y_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 55;
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_accel_cost_y_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 55*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
