/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_FrenSer_cost_y_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[61] = {57, 1, 0, 57, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56};
static const casadi_int casadi_s1[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[3] = {0, 0, 0};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[81] = {77, 1, 0, 77, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76};

static const casadi_real casadi_c0[3] = {0., 0., -1.9613299999999999e+01};
static const casadi_real casadi_c1[3] = {0., 0., -2.4516624999999999e+00};
static const casadi_real casadi_c2[3] = {0., 0., 1.};

/* drone_FrenSer_cost_y_fun:(i0[57],i1[16],i2[0],i3[],i4)->(o0[77]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, *w32=w+35, *w33=w+38, *w34=w+41, w35, w36, w37, w38, w39, w40, w41, w42, w43, w44, *w45=w+54, *w46=w+57, *w47=w+60, *w48=w+63, *w49=w+72, *w50=w+81;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #4: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #6: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #7: output[0][3] = @0 */
  if (res[0]) res[0][3] = w0;
  /* #8: @0 = input[0][4] */
  w0 = arg[0] ? arg[0][4] : 0;
  /* #9: output[0][4] = @0 */
  if (res[0]) res[0][4] = w0;
  /* #10: @0 = input[0][5] */
  w0 = arg[0] ? arg[0][5] : 0;
  /* #11: output[0][5] = @0 */
  if (res[0]) res[0][5] = w0;
  /* #12: @0 = input[0][6] */
  w0 = arg[0] ? arg[0][6] : 0;
  /* #13: output[0][6] = @0 */
  if (res[0]) res[0][6] = w0;
  /* #14: @0 = input[0][7] */
  w0 = arg[0] ? arg[0][7] : 0;
  /* #15: output[0][7] = @0 */
  if (res[0]) res[0][7] = w0;
  /* #16: @1 = input[0][8] */
  w1 = arg[0] ? arg[0][8] : 0;
  /* #17: output[0][8] = @1 */
  if (res[0]) res[0][8] = w1;
  /* #18: @2 = input[0][9] */
  w2 = arg[0] ? arg[0][9] : 0;
  /* #19: output[0][9] = @2 */
  if (res[0]) res[0][9] = w2;
  /* #20: @3 = input[0][10] */
  w3 = arg[0] ? arg[0][10] : 0;
  /* #21: output[0][10] = @3 */
  if (res[0]) res[0][10] = w3;
  /* #22: @3 = input[0][11] */
  w3 = arg[0] ? arg[0][11] : 0;
  /* #23: output[0][11] = @3 */
  if (res[0]) res[0][11] = w3;
  /* #24: @3 = input[0][12] */
  w3 = arg[0] ? arg[0][12] : 0;
  /* #25: output[0][12] = @3 */
  if (res[0]) res[0][12] = w3;
  /* #26: @3 = input[0][13] */
  w3 = arg[0] ? arg[0][13] : 0;
  /* #27: output[0][13] = @3 */
  if (res[0]) res[0][13] = w3;
  /* #28: @4 = input[0][14] */
  w4 = arg[0] ? arg[0][14] : 0;
  /* #29: output[0][14] = @4 */
  if (res[0]) res[0][14] = w4;
  /* #30: @5 = input[0][15] */
  w5 = arg[0] ? arg[0][15] : 0;
  /* #31: output[0][15] = @5 */
  if (res[0]) res[0][15] = w5;
  /* #32: @6 = input[0][16] */
  w6 = arg[0] ? arg[0][16] : 0;
  /* #33: output[0][16] = @6 */
  if (res[0]) res[0][16] = w6;
  /* #34: @7 = input[0][17] */
  w7 = arg[0] ? arg[0][17] : 0;
  /* #35: output[0][17] = @7 */
  if (res[0]) res[0][17] = w7;
  /* #36: @7 = input[0][18] */
  w7 = arg[0] ? arg[0][18] : 0;
  /* #37: output[0][18] = @7 */
  if (res[0]) res[0][18] = w7;
  /* #38: @7 = input[0][19] */
  w7 = arg[0] ? arg[0][19] : 0;
  /* #39: output[0][19] = @7 */
  if (res[0]) res[0][19] = w7;
  /* #40: @7 = input[0][20] */
  w7 = arg[0] ? arg[0][20] : 0;
  /* #41: output[0][20] = @7 */
  if (res[0]) res[0][20] = w7;
  /* #42: @8 = input[0][21] */
  w8 = arg[0] ? arg[0][21] : 0;
  /* #43: output[0][21] = @8 */
  if (res[0]) res[0][21] = w8;
  /* #44: @9 = input[0][22] */
  w9 = arg[0] ? arg[0][22] : 0;
  /* #45: output[0][22] = @9 */
  if (res[0]) res[0][22] = w9;
  /* #46: @9 = input[0][23] */
  w9 = arg[0] ? arg[0][23] : 0;
  /* #47: output[0][23] = @9 */
  if (res[0]) res[0][23] = w9;
  /* #48: @9 = input[0][24] */
  w9 = arg[0] ? arg[0][24] : 0;
  /* #49: output[0][24] = @9 */
  if (res[0]) res[0][24] = w9;
  /* #50: @10 = input[0][25] */
  w10 = arg[0] ? arg[0][25] : 0;
  /* #51: output[0][25] = @10 */
  if (res[0]) res[0][25] = w10;
  /* #52: @11 = input[0][26] */
  w11 = arg[0] ? arg[0][26] : 0;
  /* #53: output[0][26] = @11 */
  if (res[0]) res[0][26] = w11;
  /* #54: @12 = input[0][27] */
  w12 = arg[0] ? arg[0][27] : 0;
  /* #55: output[0][27] = @12 */
  if (res[0]) res[0][27] = w12;
  /* #56: @13 = input[0][28] */
  w13 = arg[0] ? arg[0][28] : 0;
  /* #57: output[0][28] = @13 */
  if (res[0]) res[0][28] = w13;
  /* #58: @13 = input[0][29] */
  w13 = arg[0] ? arg[0][29] : 0;
  /* #59: output[0][29] = @13 */
  if (res[0]) res[0][29] = w13;
  /* #60: @13 = input[0][30] */
  w13 = arg[0] ? arg[0][30] : 0;
  /* #61: output[0][30] = @13 */
  if (res[0]) res[0][30] = w13;
  /* #62: @13 = input[0][31] */
  w13 = arg[0] ? arg[0][31] : 0;
  /* #63: output[0][31] = @13 */
  if (res[0]) res[0][31] = w13;
  /* #64: @14 = input[0][32] */
  w14 = arg[0] ? arg[0][32] : 0;
  /* #65: output[0][32] = @14 */
  if (res[0]) res[0][32] = w14;
  /* #66: @15 = input[0][33] */
  w15 = arg[0] ? arg[0][33] : 0;
  /* #67: output[0][33] = @15 */
  if (res[0]) res[0][33] = w15;
  /* #68: @15 = input[0][34] */
  w15 = arg[0] ? arg[0][34] : 0;
  /* #69: output[0][34] = @15 */
  if (res[0]) res[0][34] = w15;
  /* #70: @15 = input[0][35] */
  w15 = arg[0] ? arg[0][35] : 0;
  /* #71: output[0][35] = @15 */
  if (res[0]) res[0][35] = w15;
  /* #72: @16 = input[0][36] */
  w16 = arg[0] ? arg[0][36] : 0;
  /* #73: output[0][36] = @16 */
  if (res[0]) res[0][36] = w16;
  /* #74: @17 = input[0][37] */
  w17 = arg[0] ? arg[0][37] : 0;
  /* #75: output[0][37] = @17 */
  if (res[0]) res[0][37] = w17;
  /* #76: @18 = input[0][38] */
  w18 = arg[0] ? arg[0][38] : 0;
  /* #77: output[0][38] = @18 */
  if (res[0]) res[0][38] = w18;
  /* #78: @19 = input[0][39] */
  w19 = arg[0] ? arg[0][39] : 0;
  /* #79: output[0][39] = @19 */
  if (res[0]) res[0][39] = w19;
  /* #80: @19 = input[0][40] */
  w19 = arg[0] ? arg[0][40] : 0;
  /* #81: output[0][40] = @19 */
  if (res[0]) res[0][40] = w19;
  /* #82: @19 = input[0][41] */
  w19 = arg[0] ? arg[0][41] : 0;
  /* #83: output[0][41] = @19 */
  if (res[0]) res[0][41] = w19;
  /* #84: @19 = input[0][42] */
  w19 = arg[0] ? arg[0][42] : 0;
  /* #85: output[0][42] = @19 */
  if (res[0]) res[0][42] = w19;
  /* #86: @20 = input[0][43] */
  w20 = arg[0] ? arg[0][43] : 0;
  /* #87: output[0][43] = @20 */
  if (res[0]) res[0][43] = w20;
  /* #88: @21 = input[0][44] */
  w21 = arg[0] ? arg[0][44] : 0;
  /* #89: output[0][44] = @21 */
  if (res[0]) res[0][44] = w21;
  /* #90: @21 = input[0][45] */
  w21 = arg[0] ? arg[0][45] : 0;
  /* #91: output[0][45] = @21 */
  if (res[0]) res[0][45] = w21;
  /* #92: @21 = input[0][46] */
  w21 = arg[0] ? arg[0][46] : 0;
  /* #93: output[0][46] = @21 */
  if (res[0]) res[0][46] = w21;
  /* #94: @22 = input[0][47] */
  w22 = arg[0] ? arg[0][47] : 0;
  /* #95: output[0][47] = @22 */
  if (res[0]) res[0][47] = w22;
  /* #96: @23 = input[0][48] */
  w23 = arg[0] ? arg[0][48] : 0;
  /* #97: output[0][48] = @23 */
  if (res[0]) res[0][48] = w23;
  /* #98: @24 = input[0][49] */
  w24 = arg[0] ? arg[0][49] : 0;
  /* #99: output[0][49] = @24 */
  if (res[0]) res[0][49] = w24;
  /* #100: @25 = input[0][50] */
  w25 = arg[0] ? arg[0][50] : 0;
  /* #101: output[0][50] = @25 */
  if (res[0]) res[0][50] = w25;
  /* #102: @25 = input[0][51] */
  w25 = arg[0] ? arg[0][51] : 0;
  /* #103: output[0][51] = @25 */
  if (res[0]) res[0][51] = w25;
  /* #104: @25 = input[0][52] */
  w25 = arg[0] ? arg[0][52] : 0;
  /* #105: output[0][52] = @25 */
  if (res[0]) res[0][52] = w25;
  /* #106: @25 = input[0][53] */
  w25 = arg[0] ? arg[0][53] : 0;
  /* #107: output[0][53] = @25 */
  if (res[0]) res[0][53] = w25;
  /* #108: @26 = input[0][54] */
  w26 = arg[0] ? arg[0][54] : 0;
  /* #109: output[0][54] = @26 */
  if (res[0]) res[0][54] = w26;
  /* #110: @27 = input[0][55] */
  w27 = arg[0] ? arg[0][55] : 0;
  /* #111: output[0][55] = @27 */
  if (res[0]) res[0][55] = w27;
  /* #112: @27 = input[0][56] */
  w27 = arg[0] ? arg[0][56] : 0;
  /* #113: output[0][56] = @27 */
  if (res[0]) res[0][56] = w27;
  /* #114: @27 = input[1][0] */
  w27 = arg[1] ? arg[1][0] : 0;
  /* #115: output[0][57] = @27 */
  if (res[0]) res[0][57] = w27;
  /* #116: @28 = input[1][1] */
  w28 = arg[1] ? arg[1][1] : 0;
  /* #117: output[0][58] = @28 */
  if (res[0]) res[0][58] = w28;
  /* #118: @28 = input[1][2] */
  w28 = arg[1] ? arg[1][2] : 0;
  /* #119: output[0][59] = @28 */
  if (res[0]) res[0][59] = w28;
  /* #120: @28 = input[1][3] */
  w28 = arg[1] ? arg[1][3] : 0;
  /* #121: output[0][60] = @28 */
  if (res[0]) res[0][60] = w28;
  /* #122: @28 = input[1][4] */
  w28 = arg[1] ? arg[1][4] : 0;
  /* #123: output[0][61] = @28 */
  if (res[0]) res[0][61] = w28;
  /* #124: @29 = input[1][5] */
  w29 = arg[1] ? arg[1][5] : 0;
  /* #125: output[0][62] = @29 */
  if (res[0]) res[0][62] = w29;
  /* #126: @29 = input[1][6] */
  w29 = arg[1] ? arg[1][6] : 0;
  /* #127: output[0][63] = @29 */
  if (res[0]) res[0][63] = w29;
  /* #128: @29 = input[1][7] */
  w29 = arg[1] ? arg[1][7] : 0;
  /* #129: output[0][64] = @29 */
  if (res[0]) res[0][64] = w29;
  /* #130: @29 = input[1][8] */
  w29 = arg[1] ? arg[1][8] : 0;
  /* #131: output[0][65] = @29 */
  if (res[0]) res[0][65] = w29;
  /* #132: @30 = input[1][9] */
  w30 = arg[1] ? arg[1][9] : 0;
  /* #133: output[0][66] = @30 */
  if (res[0]) res[0][66] = w30;
  /* #134: @30 = input[1][10] */
  w30 = arg[1] ? arg[1][10] : 0;
  /* #135: output[0][67] = @30 */
  if (res[0]) res[0][67] = w30;
  /* #136: @30 = input[1][11] */
  w30 = arg[1] ? arg[1][11] : 0;
  /* #137: output[0][68] = @30 */
  if (res[0]) res[0][68] = w30;
  /* #138: @30 = input[1][12] */
  w30 = arg[1] ? arg[1][12] : 0;
  /* #139: output[0][69] = @30 */
  if (res[0]) res[0][69] = w30;
  /* #140: @31 = input[1][13] */
  w31 = arg[1] ? arg[1][13] : 0;
  /* #141: output[0][70] = @31 */
  if (res[0]) res[0][70] = w31;
  /* #142: @31 = input[1][14] */
  w31 = arg[1] ? arg[1][14] : 0;
  /* #143: output[0][71] = @31 */
  if (res[0]) res[0][71] = w31;
  /* #144: @31 = input[1][15] */
  w31 = arg[1] ? arg[1][15] : 0;
  /* #145: output[0][72] = @31 */
  if (res[0]) res[0][72] = w31;
  /* #146: @32 = [0, 0, -19.6133] */
  casadi_copy(casadi_c0, 3, w32);
  /* #147: @31 = 0 */
  w31 = 0.;
  /* #148: @33 = [0, 0, -2.45166] */
  casadi_copy(casadi_c1, 3, w33);
  /* #149: @34 = zeros(3x1) */
  casadi_clear(w34, 3);
  /* #150: @35 = 1 */
  w35 = 1.;
  /* #151: @36 = sq(@5) */
  w36 = casadi_sq( w5 );
  /* #152: @37 = sq(@6) */
  w37 = casadi_sq( w6 );
  /* #153: @38 = (@36+@37) */
  w38  = (w36+w37);
  /* #154: @38 = (2.*@38) */
  w38 = (2.* w38 );
  /* #155: @38 = (@35-@38) */
  w38  = (w35-w38);
  /* #156: @39 = (@4*@5) */
  w39  = (w4*w5);
  /* #157: @40 = (@6*@3) */
  w40  = (w6*w3);
  /* #158: @41 = (@39-@40) */
  w41  = (w39-w40);
  /* #159: @41 = (2.*@41) */
  w41 = (2.* w41 );
  /* #160: @42 = (@4*@6) */
  w42  = (w4*w6);
  /* #161: @43 = (@5*@3) */
  w43  = (w5*w3);
  /* #162: @44 = (@42+@43) */
  w44  = (w42+w43);
  /* #163: @44 = (2.*@44) */
  w44 = (2.* w44 );
  /* #164: @45 = horzcat(@38, @41, @44) */
  rr=w45;
  *rr++ = w38;
  *rr++ = w41;
  *rr++ = w44;
  /* #165: @45 = @45' */
  /* #166: @39 = (@39+@40) */
  w39 += w40;
  /* #167: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #168: @40 = sq(@4) */
  w40 = casadi_sq( w4 );
  /* #169: @37 = (@40+@37) */
  w37  = (w40+w37);
  /* #170: @37 = (2.*@37) */
  w37 = (2.* w37 );
  /* #171: @37 = (@35-@37) */
  w37  = (w35-w37);
  /* #172: @5 = (@5*@6) */
  w5 *= w6;
  /* #173: @4 = (@4*@3) */
  w4 *= w3;
  /* #174: @3 = (@5-@4) */
  w3  = (w5-w4);
  /* #175: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #176: @46 = horzcat(@39, @37, @3) */
  rr=w46;
  *rr++ = w39;
  *rr++ = w37;
  *rr++ = w3;
  /* #177: @46 = @46' */
  /* #178: @42 = (@42-@43) */
  w42 -= w43;
  /* #179: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #180: @5 = (@5+@4) */
  w5 += w4;
  /* #181: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #182: @40 = (@40+@36) */
  w40 += w36;
  /* #183: @40 = (2.*@40) */
  w40 = (2.* w40 );
  /* #184: @40 = (@35-@40) */
  w40  = (w35-w40);
  /* #185: @47 = horzcat(@42, @5, @40) */
  rr=w47;
  *rr++ = w42;
  *rr++ = w5;
  *rr++ = w40;
  /* #186: @47 = @47' */
  /* #187: @48 = horzcat(@45, @46, @47) */
  rr=w48;
  for (i=0, cs=w45; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w47; i<3; ++i) *rr++ = *cs++;
  /* #188: @49 = @48' */
  for (i=0, rr=w49, cs=w48; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #189: @45 = [0, 0, 1] */
  casadi_copy(casadi_c2, 3, w45);
  /* #190: @46 = mac(@49,@45,@34) */
  casadi_copy(w34, 3, w46);
  for (i=0, rr=w46; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w49+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #191: @46 = (@27*@46) */
  for (i=0, rr=w46, cs=w46; i<3; ++i) (*rr++)  = (w27*(*cs++));
  /* #192: @46 = (@33+@46) */
  for (i=0, rr=w46, cr=w33, cs=w46; i<3; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #193: @46 = @46' */
  /* #194: @27 = sin(@7) */
  w27 = sin( w7 );
  /* #195: @42 = cos(@8) */
  w42 = cos( w8 );
  /* #196: @42 = (@27*@42) */
  w42  = (w27*w42);
  /* #197: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #198: @7 = (-@7) */
  w7 = (- w7 );
  /* #199: @8 = sin(@8) */
  w8 = sin( w8 );
  /* #200: @27 = (@27*@8) */
  w27 *= w8;
  /* #201: @47 = vertcat(@42, @7, @27) */
  rr=w47;
  *rr++ = w42;
  *rr++ = w7;
  *rr++ = w27;
  /* #202: @42 = mac(@46,@47,@31) */
  casadi_copy((&w31), 1, (&w42));
  for (i=0, rr=(&w42); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w46+j, tt=w47+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #203: @47 = (@42*@47) */
  for (i=0, rr=w47, cs=w47; i<3; ++i) (*rr++)  = (w42*(*cs++));
  /* #204: @32 = (@32+@47) */
  for (i=0, rr=w32, cs=w47; i<3; ++i) (*rr++) += (*cs++);
  /* #205: @42 = sq(@11) */
  w42 = casadi_sq( w11 );
  /* #206: @7 = sq(@12) */
  w7 = casadi_sq( w12 );
  /* #207: @27 = (@42+@7) */
  w27  = (w42+w7);
  /* #208: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #209: @27 = (@35-@27) */
  w27  = (w35-w27);
  /* #210: @8 = (@10*@11) */
  w8  = (w10*w11);
  /* #211: @5 = (@12*@9) */
  w5  = (w12*w9);
  /* #212: @40 = (@8-@5) */
  w40  = (w8-w5);
  /* #213: @40 = (2.*@40) */
  w40 = (2.* w40 );
  /* #214: @36 = (@10*@12) */
  w36  = (w10*w12);
  /* #215: @4 = (@11*@9) */
  w4  = (w11*w9);
  /* #216: @43 = (@36+@4) */
  w43  = (w36+w4);
  /* #217: @43 = (2.*@43) */
  w43 = (2.* w43 );
  /* #218: @47 = horzcat(@27, @40, @43) */
  rr=w47;
  *rr++ = w27;
  *rr++ = w40;
  *rr++ = w43;
  /* #219: @47 = @47' */
  /* #220: @8 = (@8+@5) */
  w8 += w5;
  /* #221: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #222: @5 = sq(@10) */
  w5 = casadi_sq( w10 );
  /* #223: @7 = (@5+@7) */
  w7  = (w5+w7);
  /* #224: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #225: @7 = (@35-@7) */
  w7  = (w35-w7);
  /* #226: @11 = (@11*@12) */
  w11 *= w12;
  /* #227: @10 = (@10*@9) */
  w10 *= w9;
  /* #228: @9 = (@11-@10) */
  w9  = (w11-w10);
  /* #229: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #230: @46 = horzcat(@8, @7, @9) */
  rr=w46;
  *rr++ = w8;
  *rr++ = w7;
  *rr++ = w9;
  /* #231: @46 = @46' */
  /* #232: @36 = (@36-@4) */
  w36 -= w4;
  /* #233: @36 = (2.*@36) */
  w36 = (2.* w36 );
  /* #234: @11 = (@11+@10) */
  w11 += w10;
  /* #235: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #236: @5 = (@5+@42) */
  w5 += w42;
  /* #237: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #238: @5 = (@35-@5) */
  w5  = (w35-w5);
  /* #239: @50 = horzcat(@36, @11, @5) */
  rr=w50;
  *rr++ = w36;
  *rr++ = w11;
  *rr++ = w5;
  /* #240: @50 = @50' */
  /* #241: @49 = horzcat(@47, @46, @50) */
  rr=w49;
  for (i=0, cs=w47; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w50; i<3; ++i) *rr++ = *cs++;
  /* #242: @48 = @49' */
  for (i=0, rr=w48, cs=w49; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #243: @47 = mac(@48,@45,@34) */
  casadi_copy(w34, 3, w47);
  for (i=0, rr=w47; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w48+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #244: @47 = (@28*@47) */
  for (i=0, rr=w47, cs=w47; i<3; ++i) (*rr++)  = (w28*(*cs++));
  /* #245: @47 = (@33+@47) */
  for (i=0, rr=w47, cr=w33, cs=w47; i<3; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #246: @47 = @47' */
  /* #247: @28 = sin(@13) */
  w28 = sin( w13 );
  /* #248: @36 = cos(@14) */
  w36 = cos( w14 );
  /* #249: @36 = (@28*@36) */
  w36  = (w28*w36);
  /* #250: @13 = cos(@13) */
  w13 = cos( w13 );
  /* #251: @13 = (-@13) */
  w13 = (- w13 );
  /* #252: @14 = sin(@14) */
  w14 = sin( w14 );
  /* #253: @28 = (@28*@14) */
  w28 *= w14;
  /* #254: @46 = vertcat(@36, @13, @28) */
  rr=w46;
  *rr++ = w36;
  *rr++ = w13;
  *rr++ = w28;
  /* #255: @36 = mac(@47,@46,@31) */
  casadi_copy((&w31), 1, (&w36));
  for (i=0, rr=(&w36); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w47+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #256: @46 = (@36*@46) */
  for (i=0, rr=w46, cs=w46; i<3; ++i) (*rr++)  = (w36*(*cs++));
  /* #257: @32 = (@32+@46) */
  for (i=0, rr=w32, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #258: @36 = sq(@17) */
  w36 = casadi_sq( w17 );
  /* #259: @13 = sq(@18) */
  w13 = casadi_sq( w18 );
  /* #260: @28 = (@36+@13) */
  w28  = (w36+w13);
  /* #261: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #262: @28 = (@35-@28) */
  w28  = (w35-w28);
  /* #263: @14 = (@16*@17) */
  w14  = (w16*w17);
  /* #264: @11 = (@18*@15) */
  w11  = (w18*w15);
  /* #265: @5 = (@14-@11) */
  w5  = (w14-w11);
  /* #266: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #267: @42 = (@16*@18) */
  w42  = (w16*w18);
  /* #268: @10 = (@17*@15) */
  w10  = (w17*w15);
  /* #269: @4 = (@42+@10) */
  w4  = (w42+w10);
  /* #270: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #271: @46 = horzcat(@28, @5, @4) */
  rr=w46;
  *rr++ = w28;
  *rr++ = w5;
  *rr++ = w4;
  /* #272: @46 = @46' */
  /* #273: @14 = (@14+@11) */
  w14 += w11;
  /* #274: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #275: @11 = sq(@16) */
  w11 = casadi_sq( w16 );
  /* #276: @13 = (@11+@13) */
  w13  = (w11+w13);
  /* #277: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #278: @13 = (@35-@13) */
  w13  = (w35-w13);
  /* #279: @17 = (@17*@18) */
  w17 *= w18;
  /* #280: @16 = (@16*@15) */
  w16 *= w15;
  /* #281: @15 = (@17-@16) */
  w15  = (w17-w16);
  /* #282: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #283: @47 = horzcat(@14, @13, @15) */
  rr=w47;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w15;
  /* #284: @47 = @47' */
  /* #285: @42 = (@42-@10) */
  w42 -= w10;
  /* #286: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #287: @17 = (@17+@16) */
  w17 += w16;
  /* #288: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #289: @11 = (@11+@36) */
  w11 += w36;
  /* #290: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #291: @11 = (@35-@11) */
  w11  = (w35-w11);
  /* #292: @50 = horzcat(@42, @17, @11) */
  rr=w50;
  *rr++ = w42;
  *rr++ = w17;
  *rr++ = w11;
  /* #293: @50 = @50' */
  /* #294: @48 = horzcat(@46, @47, @50) */
  rr=w48;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w47; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w50; i<3; ++i) *rr++ = *cs++;
  /* #295: @49 = @48' */
  for (i=0, rr=w49, cs=w48; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #296: @46 = mac(@49,@45,@34) */
  casadi_copy(w34, 3, w46);
  for (i=0, rr=w46; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w49+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #297: @46 = (@29*@46) */
  for (i=0, rr=w46, cs=w46; i<3; ++i) (*rr++)  = (w29*(*cs++));
  /* #298: @46 = (@33+@46) */
  for (i=0, rr=w46, cr=w33, cs=w46; i<3; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #299: @46 = @46' */
  /* #300: @29 = sin(@19) */
  w29 = sin( w19 );
  /* #301: @42 = cos(@20) */
  w42 = cos( w20 );
  /* #302: @42 = (@29*@42) */
  w42  = (w29*w42);
  /* #303: @19 = cos(@19) */
  w19 = cos( w19 );
  /* #304: @19 = (-@19) */
  w19 = (- w19 );
  /* #305: @20 = sin(@20) */
  w20 = sin( w20 );
  /* #306: @29 = (@29*@20) */
  w29 *= w20;
  /* #307: @47 = vertcat(@42, @19, @29) */
  rr=w47;
  *rr++ = w42;
  *rr++ = w19;
  *rr++ = w29;
  /* #308: @42 = mac(@46,@47,@31) */
  casadi_copy((&w31), 1, (&w42));
  for (i=0, rr=(&w42); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w46+j, tt=w47+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #309: @47 = (@42*@47) */
  for (i=0, rr=w47, cs=w47; i<3; ++i) (*rr++)  = (w42*(*cs++));
  /* #310: @32 = (@32+@47) */
  for (i=0, rr=w32, cs=w47; i<3; ++i) (*rr++) += (*cs++);
  /* #311: @42 = sq(@23) */
  w42 = casadi_sq( w23 );
  /* #312: @19 = sq(@24) */
  w19 = casadi_sq( w24 );
  /* #313: @29 = (@42+@19) */
  w29  = (w42+w19);
  /* #314: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #315: @29 = (@35-@29) */
  w29  = (w35-w29);
  /* #316: @20 = (@22*@23) */
  w20  = (w22*w23);
  /* #317: @17 = (@24*@21) */
  w17  = (w24*w21);
  /* #318: @11 = (@20-@17) */
  w11  = (w20-w17);
  /* #319: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #320: @36 = (@22*@24) */
  w36  = (w22*w24);
  /* #321: @16 = (@23*@21) */
  w16  = (w23*w21);
  /* #322: @10 = (@36+@16) */
  w10  = (w36+w16);
  /* #323: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #324: @47 = horzcat(@29, @11, @10) */
  rr=w47;
  *rr++ = w29;
  *rr++ = w11;
  *rr++ = w10;
  /* #325: @47 = @47' */
  /* #326: @20 = (@20+@17) */
  w20 += w17;
  /* #327: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #328: @17 = sq(@22) */
  w17 = casadi_sq( w22 );
  /* #329: @19 = (@17+@19) */
  w19  = (w17+w19);
  /* #330: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #331: @19 = (@35-@19) */
  w19  = (w35-w19);
  /* #332: @23 = (@23*@24) */
  w23 *= w24;
  /* #333: @22 = (@22*@21) */
  w22 *= w21;
  /* #334: @21 = (@23-@22) */
  w21  = (w23-w22);
  /* #335: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #336: @46 = horzcat(@20, @19, @21) */
  rr=w46;
  *rr++ = w20;
  *rr++ = w19;
  *rr++ = w21;
  /* #337: @46 = @46' */
  /* #338: @36 = (@36-@16) */
  w36 -= w16;
  /* #339: @36 = (2.*@36) */
  w36 = (2.* w36 );
  /* #340: @23 = (@23+@22) */
  w23 += w22;
  /* #341: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #342: @17 = (@17+@42) */
  w17 += w42;
  /* #343: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #344: @35 = (@35-@17) */
  w35 -= w17;
  /* #345: @50 = horzcat(@36, @23, @35) */
  rr=w50;
  *rr++ = w36;
  *rr++ = w23;
  *rr++ = w35;
  /* #346: @50 = @50' */
  /* #347: @49 = horzcat(@47, @46, @50) */
  rr=w49;
  for (i=0, cs=w47; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w50; i<3; ++i) *rr++ = *cs++;
  /* #348: @48 = @49' */
  for (i=0, rr=w48, cs=w49; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #349: @34 = mac(@48,@45,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w48+j, tt=w45+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #350: @34 = (@30*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) (*rr++)  = (w30*(*cs++));
  /* #351: @33 = (@33+@34) */
  for (i=0, rr=w33, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #352: @33 = @33' */
  /* #353: @30 = sin(@25) */
  w30 = sin( w25 );
  /* #354: @36 = cos(@26) */
  w36 = cos( w26 );
  /* #355: @36 = (@30*@36) */
  w36  = (w30*w36);
  /* #356: @25 = cos(@25) */
  w25 = cos( w25 );
  /* #357: @25 = (-@25) */
  w25 = (- w25 );
  /* #358: @26 = sin(@26) */
  w26 = sin( w26 );
  /* #359: @30 = (@30*@26) */
  w30 *= w26;
  /* #360: @34 = vertcat(@36, @25, @30) */
  rr=w34;
  *rr++ = w36;
  *rr++ = w25;
  *rr++ = w30;
  /* #361: @31 = mac(@33,@34,@31) */
  for (i=0, rr=(&w31); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w33+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #362: @34 = (@31*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) (*rr++)  = (w31*(*cs++));
  /* #363: @32 = (@32+@34) */
  for (i=0, rr=w32, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #364: @31 = 0.1 */
  w31 = 1.0000000000000001e-01;
  /* #365: @34 = vertcat(@0, @1, @2) */
  rr=w34;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  /* #366: @34 = (@31*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) (*rr++)  = (w31*(*cs++));
  /* #367: @32 = (@32-@34) */
  for (i=0, rr=w32, cs=w34; i<3; ++i) (*rr++) -= (*cs++);
  /* #368: @31 = 2 */
  w31 = 2.;
  /* #369: @32 = (@32/@31) */
  for (i=0, rr=w32; i<3; ++i) (*rr++) /= w31;
  /* #370: output[0][73] = @32 */
  if (res[0]) casadi_copy(w32, 3, res[0]+73);
  /* #371: @31 = input[4][0] */
  w31 = arg[4] ? arg[4][0] : 0;
  /* #372: output[0][74] = @31 */
  if (res[0]) res[0][76] = w31;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_cost_y_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_cost_y_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_cost_y_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_FrenSer_cost_y_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_cost_y_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_FrenSer_cost_y_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_FrenSer_cost_y_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_FrenSer_cost_y_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_FrenSer_cost_y_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int drone_FrenSer_cost_y_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real drone_FrenSer_cost_y_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_FrenSer_cost_y_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_FrenSer_cost_y_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_FrenSer_cost_y_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_FrenSer_cost_y_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_cost_y_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 84;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_cost_y_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 84*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
